// Code generated by protoc-gen-go.
// source: steammessages_deviceauth.steamclient.proto
// DO NOT EDIT!

package unified

import proto "github.com/golang/protobuf/proto"
import fmt "fmt"
import math "math"
import _ "github.com/golang/protobuf/protoc-gen-go/descriptor"

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package unified is being compiled against.
const _ = proto.ProtoPackageIsVersion1

type CDeviceAuth_GetOwnAuthorizedDevices_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IncludeCanceled  *bool   `protobuf:"varint,2,opt,name=include_canceled" json:"include_canceled,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) Reset() {
	*m = CDeviceAuth_GetOwnAuthorizedDevices_Request{}
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Request) ProtoMessage() {}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{0}
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) GetIncludeCanceled() bool {
	if m != nil && m.IncludeCanceled != nil {
		return *m.IncludeCanceled
	}
	return false
}

type CDeviceAuth_GetOwnAuthorizedDevices_Response struct {
	Devices          []*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	XXX_unrecognized []byte                                                 `json:"-"`
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) Reset() {
	*m = CDeviceAuth_GetOwnAuthorizedDevices_Response{}
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response) ProtoMessage() {}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1}
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) GetDevices() []*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type CDeviceAuth_GetOwnAuthorizedDevices_Response_Device struct {
	AuthDeviceToken  *uint64 `protobuf:"fixed64,1,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	DeviceName       *string `protobuf:"bytes,2,opt,name=device_name" json:"device_name,omitempty"`
	IsPending        *bool   `protobuf:"varint,3,opt,name=is_pending" json:"is_pending,omitempty"`
	IsCanceled       *bool   `protobuf:"varint,4,opt,name=is_canceled" json:"is_canceled,omitempty"`
	LastTimeUsed     *uint32 `protobuf:"varint,5,opt,name=last_time_used" json:"last_time_used,omitempty"`
	LastBorrowerId   *uint64 `protobuf:"fixed64,6,opt,name=last_borrower_id" json:"last_borrower_id,omitempty"`
	LastAppPlayed    *uint32 `protobuf:"varint,7,opt,name=last_app_played" json:"last_app_played,omitempty"`
	IsLimited        *bool   `protobuf:"varint,8,opt,name=is_limited" json:"is_limited,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) Reset() {
	*m = CDeviceAuth_GetOwnAuthorizedDevices_Response_Device{}
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) ProtoMessage() {}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{1, 0}
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetIsPending() bool {
	if m != nil && m.IsPending != nil {
		return *m.IsPending
	}
	return false
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetIsCanceled() bool {
	if m != nil && m.IsCanceled != nil {
		return *m.IsCanceled
	}
	return false
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetLastTimeUsed() uint32 {
	if m != nil && m.LastTimeUsed != nil {
		return *m.LastTimeUsed
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetLastBorrowerId() uint64 {
	if m != nil && m.LastBorrowerId != nil {
		return *m.LastBorrowerId
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetLastAppPlayed() uint32 {
	if m != nil && m.LastAppPlayed != nil {
		return *m.LastAppPlayed
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetIsLimited() bool {
	if m != nil && m.IsLimited != nil {
		return *m.IsLimited
	}
	return false
}

type CDeviceAuth_AcceptAuthorizationRequest_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthDeviceToken  *uint64 `protobuf:"fixed64,2,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	AuthCode         *uint64 `protobuf:"fixed64,3,opt,name=auth_code" json:"auth_code,omitempty"`
	FromSteamid      *uint64 `protobuf:"fixed64,4,opt,name=from_steamid" json:"from_steamid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) Reset() {
	*m = CDeviceAuth_AcceptAuthorizationRequest_Request{}
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AcceptAuthorizationRequest_Request) ProtoMessage() {}
func (*CDeviceAuth_AcceptAuthorizationRequest_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{2}
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetAuthCode() uint64 {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return 0
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetFromSteamid() uint64 {
	if m != nil && m.FromSteamid != nil {
		return *m.FromSteamid
	}
	return 0
}

type CDeviceAuth_AcceptAuthorizationRequest_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) Reset() {
	*m = CDeviceAuth_AcceptAuthorizationRequest_Response{}
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AcceptAuthorizationRequest_Response) ProtoMessage() {}
func (*CDeviceAuth_AcceptAuthorizationRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{3}
}

type CDeviceAuth_AuthorizeRemoteDevice_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthDeviceToken  *uint64 `protobuf:"fixed64,2,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) Reset() {
	*m = CDeviceAuth_AuthorizeRemoteDevice_Request{}
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) String() string { return proto.CompactTextString(m) }
func (*CDeviceAuth_AuthorizeRemoteDevice_Request) ProtoMessage()    {}
func (*CDeviceAuth_AuthorizeRemoteDevice_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{4}
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

type CDeviceAuth_AuthorizeRemoteDevice_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) Reset() {
	*m = CDeviceAuth_AuthorizeRemoteDevice_Response{}
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AuthorizeRemoteDevice_Response) ProtoMessage() {}
func (*CDeviceAuth_AuthorizeRemoteDevice_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{5}
}

type CDeviceAuth_DeauthorizeRemoteDevice_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthDeviceToken  *uint64 `protobuf:"fixed64,2,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) Reset() {
	*m = CDeviceAuth_DeauthorizeRemoteDevice_Request{}
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Request) ProtoMessage() {}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{6}
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

type CDeviceAuth_DeauthorizeRemoteDevice_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) Reset() {
	*m = CDeviceAuth_DeauthorizeRemoteDevice_Response{}
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Response) ProtoMessage() {}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{7}
}

type CDeviceAuth_GetUsedAuthorizedDevices_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) Reset() {
	*m = CDeviceAuth_GetUsedAuthorizedDevices_Request{}
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Request) ProtoMessage() {}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{8}
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CDeviceAuth_GetUsedAuthorizedDevices_Response struct {
	Devices          []*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	XXX_unrecognized []byte                                                  `json:"-"`
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) Reset() {
	*m = CDeviceAuth_GetUsedAuthorizedDevices_Response{}
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response) ProtoMessage() {}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9}
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) GetDevices() []*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type CDeviceAuth_GetUsedAuthorizedDevices_Response_Device struct {
	AuthDeviceToken  *uint64 `protobuf:"fixed64,1,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	DeviceName       *string `protobuf:"bytes,2,opt,name=device_name" json:"device_name,omitempty"`
	OwnerSteamid     *uint64 `protobuf:"fixed64,3,opt,name=owner_steamid" json:"owner_steamid,omitempty"`
	LastTimeUsed     *uint32 `protobuf:"varint,4,opt,name=last_time_used" json:"last_time_used,omitempty"`
	LastAppPlayed    *uint32 `protobuf:"varint,5,opt,name=last_app_played" json:"last_app_played,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) Reset() {
	*m = CDeviceAuth_GetUsedAuthorizedDevices_Response_Device{}
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) ProtoMessage() {}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{9, 0}
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetOwnerSteamid() uint64 {
	if m != nil && m.OwnerSteamid != nil {
		return *m.OwnerSteamid
	}
	return 0
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetLastTimeUsed() uint32 {
	if m != nil && m.LastTimeUsed != nil {
		return *m.LastTimeUsed
	}
	return 0
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetLastAppPlayed() uint32 {
	if m != nil && m.LastAppPlayed != nil {
		return *m.LastAppPlayed
	}
	return 0
}

type CDeviceAuth_GetAuthorizedBorrowers_Request struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IncludeCanceled  *bool   `protobuf:"varint,2,opt,name=include_canceled" json:"include_canceled,omitempty"`
	IncludePending   *bool   `protobuf:"varint,3,opt,name=include_pending" json:"include_pending,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) Reset() {
	*m = CDeviceAuth_GetAuthorizedBorrowers_Request{}
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedBorrowers_Request) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedBorrowers_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{10}
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) GetIncludeCanceled() bool {
	if m != nil && m.IncludeCanceled != nil {
		return *m.IncludeCanceled
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) GetIncludePending() bool {
	if m != nil && m.IncludePending != nil {
		return *m.IncludePending
	}
	return false
}

type CDeviceAuth_GetAuthorizedBorrowers_Response struct {
	Borrowers        []*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower `protobuf:"bytes,1,rep,name=borrowers" json:"borrowers,omitempty"`
	XXX_unrecognized []byte                                                  `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) Reset() {
	*m = CDeviceAuth_GetAuthorizedBorrowers_Response{}
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11}
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) GetBorrowers() []*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower {
	if m != nil {
		return m.Borrowers
	}
	return nil
}

type CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower struct {
	Steamid          *uint64 `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IsPending        *bool   `protobuf:"varint,2,opt,name=is_pending" json:"is_pending,omitempty"`
	IsCanceled       *bool   `protobuf:"varint,3,opt,name=is_canceled" json:"is_canceled,omitempty"`
	TimeCreated      *uint32 `protobuf:"varint,4,opt,name=time_created" json:"time_created,omitempty"`
	XXX_unrecognized []byte  `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) Reset() {
	*m = CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower{}
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{11, 0}
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetIsPending() bool {
	if m != nil && m.IsPending != nil {
		return *m.IsPending
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetIsCanceled() bool {
	if m != nil && m.IsCanceled != nil {
		return *m.IsCanceled
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetTimeCreated() uint32 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

type CDeviceAuth_AddAuthorizedBorrowers_Request struct {
	Steamid          *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	SteamidBorrower  []uint64 `protobuf:"fixed64,2,rep,name=steamid_borrower" json:"steamid_borrower,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) Reset() {
	*m = CDeviceAuth_AddAuthorizedBorrowers_Request{}
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AddAuthorizedBorrowers_Request) ProtoMessage() {}
func (*CDeviceAuth_AddAuthorizedBorrowers_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{12}
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) GetSteamidBorrower() []uint64 {
	if m != nil {
		return m.SteamidBorrower
	}
	return nil
}

type CDeviceAuth_AddAuthorizedBorrowers_Response struct {
	SecondsToWait    *int32 `protobuf:"varint,1,opt,name=seconds_to_wait" json:"seconds_to_wait,omitempty"`
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) Reset() {
	*m = CDeviceAuth_AddAuthorizedBorrowers_Response{}
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AddAuthorizedBorrowers_Response) ProtoMessage() {}
func (*CDeviceAuth_AddAuthorizedBorrowers_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{13}
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) GetSecondsToWait() int32 {
	if m != nil && m.SecondsToWait != nil {
		return *m.SecondsToWait
	}
	return 0
}

type CDeviceAuth_RemoveAuthorizedBorrowers_Request struct {
	Steamid          *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	SteamidBorrower  []uint64 `protobuf:"fixed64,2,rep,name=steamid_borrower" json:"steamid_borrower,omitempty"`
	XXX_unrecognized []byte   `json:"-"`
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) Reset() {
	*m = CDeviceAuth_RemoveAuthorizedBorrowers_Request{}
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Request) ProtoMessage() {}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{14}
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) GetSteamidBorrower() []uint64 {
	if m != nil {
		return m.SteamidBorrower
	}
	return nil
}

type CDeviceAuth_RemoveAuthorizedBorrowers_Response struct {
	XXX_unrecognized []byte `json:"-"`
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) Reset() {
	*m = CDeviceAuth_RemoveAuthorizedBorrowers_Response{}
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Response) ProtoMessage() {}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor0, []int{15}
}

func init() {
	proto.RegisterType((*CDeviceAuth_GetOwnAuthorizedDevices_Request)(nil), "CDeviceAuth_GetOwnAuthorizedDevices_Request")
	proto.RegisterType((*CDeviceAuth_GetOwnAuthorizedDevices_Response)(nil), "CDeviceAuth_GetOwnAuthorizedDevices_Response")
	proto.RegisterType((*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device)(nil), "CDeviceAuth_GetOwnAuthorizedDevices_Response.Device")
	proto.RegisterType((*CDeviceAuth_AcceptAuthorizationRequest_Request)(nil), "CDeviceAuth_AcceptAuthorizationRequest_Request")
	proto.RegisterType((*CDeviceAuth_AcceptAuthorizationRequest_Response)(nil), "CDeviceAuth_AcceptAuthorizationRequest_Response")
	proto.RegisterType((*CDeviceAuth_AuthorizeRemoteDevice_Request)(nil), "CDeviceAuth_AuthorizeRemoteDevice_Request")
	proto.RegisterType((*CDeviceAuth_AuthorizeRemoteDevice_Response)(nil), "CDeviceAuth_AuthorizeRemoteDevice_Response")
	proto.RegisterType((*CDeviceAuth_DeauthorizeRemoteDevice_Request)(nil), "CDeviceAuth_DeauthorizeRemoteDevice_Request")
	proto.RegisterType((*CDeviceAuth_DeauthorizeRemoteDevice_Response)(nil), "CDeviceAuth_DeauthorizeRemoteDevice_Response")
	proto.RegisterType((*CDeviceAuth_GetUsedAuthorizedDevices_Request)(nil), "CDeviceAuth_GetUsedAuthorizedDevices_Request")
	proto.RegisterType((*CDeviceAuth_GetUsedAuthorizedDevices_Response)(nil), "CDeviceAuth_GetUsedAuthorizedDevices_Response")
	proto.RegisterType((*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device)(nil), "CDeviceAuth_GetUsedAuthorizedDevices_Response.Device")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedBorrowers_Request)(nil), "CDeviceAuth_GetAuthorizedBorrowers_Request")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedBorrowers_Response)(nil), "CDeviceAuth_GetAuthorizedBorrowers_Response")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower)(nil), "CDeviceAuth_GetAuthorizedBorrowers_Response.Borrower")
	proto.RegisterType((*CDeviceAuth_AddAuthorizedBorrowers_Request)(nil), "CDeviceAuth_AddAuthorizedBorrowers_Request")
	proto.RegisterType((*CDeviceAuth_AddAuthorizedBorrowers_Response)(nil), "CDeviceAuth_AddAuthorizedBorrowers_Response")
	proto.RegisterType((*CDeviceAuth_RemoveAuthorizedBorrowers_Request)(nil), "CDeviceAuth_RemoveAuthorizedBorrowers_Request")
	proto.RegisterType((*CDeviceAuth_RemoveAuthorizedBorrowers_Response)(nil), "CDeviceAuth_RemoveAuthorizedBorrowers_Response")
}

var fileDescriptor0 = []byte{
	// 953 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x09, 0x6e, 0x88, 0x02, 0xff, 0xac, 0x56, 0xcd, 0x6e, 0x1c, 0x45,
	0x10, 0xd6, 0xd8, 0xc9, 0xda, 0x6e, 0x13, 0x42, 0x1a, 0x92, 0x6c, 0xe6, 0x00, 0xad, 0x81, 0x43,
	0xb0, 0xd7, 0xbd, 0x26, 0x32, 0xe2, 0xff, 0x27, 0x10, 0x02, 0x07, 0x24, 0x24, 0x23, 0x04, 0xe4,
	0x32, 0xea, 0x9d, 0x29, 0xef, 0xb6, 0xd8, 0x9d, 0x1e, 0xba, 0x7b, 0x6d, 0x99, 0x13, 0x42, 0xe2,
	0x25, 0xe0, 0x0d, 0x38, 0x21, 0xa4, 0x08, 0x24, 0x38, 0xf0, 0x0e, 0xbc, 0x0d, 0xa7, 0xd4, 0xf4,
	0xf4, 0x6c, 0x32, 0xbb, 0x3b, 0xf6, 0x8e, 0x95, 0x93, 0xc7, 0x55, 0xd5, 0xd5, 0x5f, 0x55, 0xd7,
	0xf7, 0xd5, 0x92, 0x1d, 0x63, 0x41, 0x4c, 0x26, 0x60, 0x8c, 0x18, 0x82, 0x89, 0x53, 0x38, 0x96,
	0x09, 0x88, 0xa9, 0x1d, 0x71, 0xe7, 0x48, 0xc6, 0x12, 0x32, 0xcb, 0x73, 0xad, 0xac, 0x0a, 0xd9,
	0x50, 0xa9, 0xe1, 0x18, 0xfa, 0xee, 0xbf, 0xc1, 0xf4, 0xa8, 0x9f, 0x82, 0x49, 0xb4, 0xcc, 0xad,
	0xd2, 0x3e, 0xa2, 0x57, 0xcf, 0x36, 0xcd, 0xe4, 0x91, 0x84, 0x34, 0x1e, 0x08, 0x03, 0x8b, 0xf9,
	0xa2, 0x6f, 0xc8, 0xee, 0xc7, 0xf7, 0xdc, 0x85, 0x77, 0xf1, 0xc2, 0xf8, 0x53, 0xb0, 0x5f, 0x9c,
	0x64, 0xc5, 0xa7, 0xd2, 0xf2, 0x07, 0x48, 0x4b, 0x97, 0x89, 0x0f, 0xe1, 0xfb, 0x29, 0x18, 0x4b,
	0xaf, 0x92, 0x0d, 0x97, 0x43, 0xa6, 0xdd, 0x80, 0x05, 0xb7, 0x3b, 0xb4, 0x4b, 0x9e, 0x93, 0x59,
	0x32, 0x9e, 0xa6, 0x10, 0x27, 0x22, 0x4b, 0x60, 0x0c, 0x69, 0x77, 0x0d, 0x3d, 0x9b, 0xd1, 0x5f,
	0x6b, 0xa4, 0xb7, 0x5a, 0x6a, 0x93, 0xab, 0xcc, 0x00, 0xfd, 0x84, 0x6c, 0x94, 0xa5, 0x1b, 0xcc,
	0xbd, 0x7e, 0x7b, 0xfb, 0xce, 0x01, 0x6f, 0x73, 0x9e, 0x97, 0x86, 0xf0, 0xdf, 0x80, 0x74, 0xca,
	0x4f, 0x7a, 0x8b, 0x5c, 0x2b, 0xda, 0xe8, 0x3b, 0x1a, 0x5b, 0xf5, 0x1d, 0x64, 0x1e, 0xf7, 0xf3,
	0x64, 0xdb, 0x5b, 0x33, 0x31, 0x01, 0x07, 0x79, 0x8b, 0x52, 0x42, 0xa4, 0x89, 0x73, 0xc8, 0x52,
	0x99, 0x0d, 0xbb, 0xeb, 0x45, 0x19, 0x45, 0x20, 0xda, 0x66, 0xb5, 0x5d, 0x72, 0xc6, 0x1b, 0xe4,
	0xd9, 0xb1, 0x30, 0x36, 0xb6, 0x72, 0x02, 0xf1, 0xd4, 0xa0, 0xfd, 0x32, 0xda, 0xaf, 0x14, 0xdd,
	0x70, 0xf6, 0x81, 0xd2, 0x5a, 0x9d, 0x80, 0x8e, 0xb1, 0x4f, 0x1d, 0x77, 0xdf, 0x4d, 0x72, 0xd5,
	0x79, 0x44, 0x9e, 0xc7, 0xf9, 0x58, 0x9c, 0xe2, 0x91, 0x0d, 0x77, 0xa4, 0xbc, 0x73, 0x2c, 0x27,
	0xd2, 0xa2, 0x6d, 0xd3, 0xb5, 0xee, 0xe7, 0x80, 0xd4, 0x4a, 0xbf, 0x9b, 0x24, 0x90, 0xdb, 0xaa,
	0x74, 0x61, 0xa5, 0xca, 0xfc, 0x83, 0x34, 0x3f, 0xcc, 0xd2, 0xda, 0xd7, 0x9c, 0xeb, 0x1a, 0xd9,
	0x72, 0xae, 0x44, 0xa5, 0xe0, 0xaa, 0xec, 0xd0, 0x17, 0xc8, 0x33, 0x47, 0x5a, 0x4d, 0xe2, 0x2a,
	0x47, 0x51, 0x66, 0x27, 0x7a, 0x8d, 0xf4, 0x57, 0x86, 0x51, 0x3e, 0x42, 0xf4, 0x35, 0x79, 0xb5,
	0x76, 0xa4, 0x7a, 0xae, 0x43, 0x98, 0x28, 0x0b, 0xa5, 0xe7, 0x22, 0xa0, 0xa3, 0x1e, 0xd9, 0x59,
	0x25, 0xb1, 0x87, 0xf1, 0x6d, 0x7d, 0xac, 0xef, 0x39, 0x3a, 0x3d, 0x1d, 0x20, 0xbc, 0x3e, 0xd6,
	0xcd, 0xa9, 0x3d, 0x94, 0x0f, 0x16, 0x68, 0xf0, 0x15, 0x0e, 0xcc, 0xea, 0x14, 0x8b, 0xfe, 0x0f,
	0xc8, 0xde, 0x8a, 0x19, 0x3c, 0x93, 0xee, 0xcf, 0x33, 0xe9, 0x75, 0xde, 0x2a, 0x41, 0x45, 0xa5,
	0x1f, 0x2f, 0x4e, 0xa5, 0xeb, 0xe4, 0x8a, 0x3a, 0xc9, 0x90, 0x01, 0x55, 0x2d, 0xe5, 0x9c, 0x2d,
	0x12, 0xe7, 0x92, 0x63, 0xc1, 0x12, 0x7a, 0x38, 0x46, 0x45, 0x79, 0xfd, 0xd9, 0x11, 0xfa, 0x63,
	0xd8, 0x1f, 0x79, 0x96, 0x5d, 0x44, 0x9e, 0x8a, 0x1b, 0x2b, 0x4f, 0x8d, 0xf0, 0xd1, 0x7f, 0xc1,
	0x82, 0x24, 0x2e, 0xbf, 0xd2, 0x37, 0xfb, 0x33, 0xb2, 0x55, 0xd1, 0xbd, 0xb1, 0xdd, 0x67, 0x25,
	0xe0, 0x95, 0x29, 0x7c, 0x40, 0x36, 0xab, 0xef, 0xc5, 0x4a, 0xea, 0xda, 0xb4, 0xb6, 0x4c, 0x9b,
	0x4a, 0xc1, 0x42, 0x2a, 0xbb, 0xee, 0x26, 0x1a, 0x84, 0xad, 0x1a, 0x8c, 0xbc, 0xac, 0xd3, 0x27,
	0x4d, 0xdb, 0xf6, 0xd1, 0x1b, 0x66, 0xda, 0x86, 0x18, 0xd6, 0x71, 0x3a, 0xef, 0xd7, 0xbb, 0xd5,
	0x98, 0xd8, 0x77, 0x0b, 0xdb, 0x6e, 0x20, 0x51, 0x59, 0x6a, 0x70, 0x86, 0xe2, 0x13, 0x21, 0xad,
	0xbb, 0xe1, 0x72, 0xf4, 0xa0, 0x3e, 0xe4, 0x05, 0x97, 0x8e, 0xe1, 0x29, 0x61, 0xdc, 0xaf, 0xcb,
	0xe9, 0x59, 0xb9, 0x4b, 0x98, 0x77, 0xfe, 0xdc, 0x26, 0xe4, 0xf1, 0x09, 0xfa, 0x4b, 0x40, 0x6e,
	0x36, 0xec, 0x1f, 0xda, 0xe3, 0x2d, 0x16, 0x68, 0xb8, 0xd7, 0x6a, 0xa7, 0x45, 0xd1, 0x4f, 0x0f,
	0xbb, 0x2f, 0x62, 0x14, 0x1b, 0x4b, 0x63, 0x99, 0x3a, 0x62, 0x33, 0xb1, 0x49, 0x99, 0xa7, 0x38,
	0x7d, 0x18, 0x90, 0xb0, 0x59, 0x9a, 0x69, 0xbf, 0xe5, 0x2a, 0x09, 0xf7, 0x79, 0x5b, 0xd1, 0x3f,
	0x40, 0x94, 0xfb, 0x65, 0x20, 0x13, 0xd9, 0x0c, 0xa3, 0x0b, 0x66, 0xba, 0x8c, 0x66, 0x83, 0x53,
	0xf4, 0x29, 0x3b, 0x02, 0xcd, 0x90, 0xf8, 0xda, 0xd0, 0xdf, 0x02, 0x72, 0x7d, 0xa9, 0x8c, 0xd3,
	0x1d, 0xbe, 0xf2, 0x0e, 0x09, 0x77, 0x79, 0x8b, 0xb5, 0xf0, 0x26, 0x02, 0x3d, 0x98, 0xc5, 0x30,
	0x54, 0x28, 0x84, 0x57, 0x04, 0xfa, 0x66, 0x32, 0x3b, 0x12, 0x96, 0x8d, 0x84, 0x61, 0x9e, 0x68,
	0x15, 0x7a, 0xfa, 0x2b, 0x4e, 0x40, 0x83, 0xd4, 0xcf, 0x4d, 0xc0, 0x39, 0xbb, 0x66, 0x6e, 0x02,
	0xce, 0x5d, 0x1f, 0x2f, 0x23, 0xe4, 0x97, 0x0e, 0xe1, 0x18, 0x05, 0xd7, 0xe1, 0xf5, 0x40, 0x6b,
	0x3d, 0xa6, 0x7f, 0x07, 0xa4, 0xdb, 0xa4, 0xea, 0x74, 0x8f, 0xb7, 0xd9, 0x3f, 0x21, 0x6f, 0xb7,
	0x2b, 0xa2, 0x0f, 0x11, 0xe0, 0xbb, 0x67, 0x8f, 0xa8, 0x7b, 0x70, 0x56, 0xea, 0x3a, 0xf3, 0xdc,
	0x4c, 0xd9, 0x10, 0xb7, 0x85, 0x61, 0x88, 0xfe, 0x8f, 0x80, 0xdc, 0x58, 0x2e, 0x92, 0x74, 0x97,
	0xaf, 0xae, 0xfe, 0x61, 0xaf, 0x8d, 0xec, 0x46, 0xef, 0x21, 0xee, 0xb7, 0x9e, 0xc4, 0xed, 0xa6,
	0xb2, 0x9c, 0x00, 0x94, 0x54, 0x8f, 0x13, 0xf1, 0x3d, 0x39, 0xd2, 0xb3, 0x9a, 0xe8, 0xef, 0x08,
	0x7a, 0xb9, 0xd8, 0xcd, 0x81, 0x3e, 0x5b, 0x6a, 0xe7, 0x40, 0x9f, 0x23, 0x9f, 0xd1, 0x3b, 0x08,
	0xfa, 0x0d, 0x0c, 0x6a, 0x06, 0xeb, 0x7f, 0x49, 0x2e, 0x13, 0x8a, 0x7f, 0x02, 0x72, 0xab, 0x51,
	0xfb, 0x28, 0xe7, 0xad, 0xf4, 0x37, 0xec, 0xb7, 0xd4, 0xd4, 0xe8, 0x7d, 0xc4, 0xfe, 0x76, 0x19,
	0x77, 0x11, 0xf8, 0xe1, 0x2b, 0x78, 0x9e, 0x7d, 0x2e, 0x07, 0x5a, 0xe8, 0x53, 0xf6, 0xe5, 0x48,
	0xe8, 0x82, 0x9f, 0x06, 0xac, 0xc5, 0xbf, 0x06, 0x3f, 0x74, 0x11, 0xf6, 0x28, 0x00, 0x00, 0xff,
	0xff, 0xf4, 0xd4, 0xe7, 0x93, 0x4d, 0x0d, 0x00, 0x00,
}
