// Code generated by protoc-gen-go. DO NOT EDIT.
// source: gcsystemmsgs.proto

package protobuf

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package protobuf is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package protobuf to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type EGCSystemMsg int32

const (
	EGCSystemMsg_k_EGCMsgInvalid                                  EGCSystemMsg = 0
	EGCSystemMsg_k_EGCMsgMulti                                    EGCSystemMsg = 1
	EGCSystemMsg_k_EGCMsgGenericReply                             EGCSystemMsg = 10
	EGCSystemMsg_k_EGCMsgSystemBase                               EGCSystemMsg = 50
	EGCSystemMsg_k_EGCMsgAchievementAwarded                       EGCSystemMsg = 51
	EGCSystemMsg_k_EGCMsgConCommand                               EGCSystemMsg = 52
	EGCSystemMsg_k_EGCMsgStartPlaying                             EGCSystemMsg = 53
	EGCSystemMsg_k_EGCMsgStopPlaying                              EGCSystemMsg = 54
	EGCSystemMsg_k_EGCMsgStartGameserver                          EGCSystemMsg = 55
	EGCSystemMsg_k_EGCMsgStopGameserver                           EGCSystemMsg = 56
	EGCSystemMsg_k_EGCMsgWGRequest                                EGCSystemMsg = 57
	EGCSystemMsg_k_EGCMsgWGResponse                               EGCSystemMsg = 58
	EGCSystemMsg_k_EGCMsgGetUserGameStatsSchema                   EGCSystemMsg = 59
	EGCSystemMsg_k_EGCMsgGetUserGameStatsSchemaResponse           EGCSystemMsg = 60
	EGCSystemMsg_k_EGCMsgGetUserStatsDEPRECATED                   EGCSystemMsg = 61
	EGCSystemMsg_k_EGCMsgGetUserStatsResponse                     EGCSystemMsg = 62
	EGCSystemMsg_k_EGCMsgAppInfoUpdated                           EGCSystemMsg = 63
	EGCSystemMsg_k_EGCMsgValidateSession                          EGCSystemMsg = 64
	EGCSystemMsg_k_EGCMsgValidateSessionResponse                  EGCSystemMsg = 65
	EGCSystemMsg_k_EGCMsgLookupAccountFromInput                   EGCSystemMsg = 66
	EGCSystemMsg_k_EGCMsgSendHTTPRequest                          EGCSystemMsg = 67
	EGCSystemMsg_k_EGCMsgSendHTTPRequestResponse                  EGCSystemMsg = 68
	EGCSystemMsg_k_EGCMsgPreTestSetup                             EGCSystemMsg = 69
	EGCSystemMsg_k_EGCMsgRecordSupportAction                      EGCSystemMsg = 70
	EGCSystemMsg_k_EGCMsgGetAccountDetails_DEPRECATED             EGCSystemMsg = 71
	EGCSystemMsg_k_EGCMsgReceiveInterAppMessage                   EGCSystemMsg = 73
	EGCSystemMsg_k_EGCMsgFindAccounts                             EGCSystemMsg = 74
	EGCSystemMsg_k_EGCMsgPostAlert                                EGCSystemMsg = 75
	EGCSystemMsg_k_EGCMsgGetLicenses                              EGCSystemMsg = 76
	EGCSystemMsg_k_EGCMsgGetUserStats                             EGCSystemMsg = 77
	EGCSystemMsg_k_EGCMsgGetCommands                              EGCSystemMsg = 78
	EGCSystemMsg_k_EGCMsgGetCommandsResponse                      EGCSystemMsg = 79
	EGCSystemMsg_k_EGCMsgAddFreeLicense                           EGCSystemMsg = 80
	EGCSystemMsg_k_EGCMsgAddFreeLicenseResponse                   EGCSystemMsg = 81
	EGCSystemMsg_k_EGCMsgGetIPLocation                            EGCSystemMsg = 82
	EGCSystemMsg_k_EGCMsgGetIPLocationResponse                    EGCSystemMsg = 83
	EGCSystemMsg_k_EGCMsgSystemStatsSchema                        EGCSystemMsg = 84
	EGCSystemMsg_k_EGCMsgGetSystemStats                           EGCSystemMsg = 85
	EGCSystemMsg_k_EGCMsgGetSystemStatsResponse                   EGCSystemMsg = 86
	EGCSystemMsg_k_EGCMsgSendEmail                                EGCSystemMsg = 87
	EGCSystemMsg_k_EGCMsgSendEmailResponse                        EGCSystemMsg = 88
	EGCSystemMsg_k_EGCMsgGetEmailTemplate                         EGCSystemMsg = 89
	EGCSystemMsg_k_EGCMsgGetEmailTemplateResponse                 EGCSystemMsg = 90
	EGCSystemMsg_k_EGCMsgGrantGuestPass                           EGCSystemMsg = 91
	EGCSystemMsg_k_EGCMsgGrantGuestPassResponse                   EGCSystemMsg = 92
	EGCSystemMsg_k_EGCMsgGetAccountDetails                        EGCSystemMsg = 93
	EGCSystemMsg_k_EGCMsgGetAccountDetailsResponse                EGCSystemMsg = 94
	EGCSystemMsg_k_EGCMsgGetPersonaNames                          EGCSystemMsg = 95
	EGCSystemMsg_k_EGCMsgGetPersonaNamesResponse                  EGCSystemMsg = 96
	EGCSystemMsg_k_EGCMsgMultiplexMsg                             EGCSystemMsg = 97
	EGCSystemMsg_k_EGCMsgMultiplexMsgResponse                     EGCSystemMsg = 98
	EGCSystemMsg_k_EGCMsgWebAPIRegisterInterfaces                 EGCSystemMsg = 101
	EGCSystemMsg_k_EGCMsgWebAPIJobRequest                         EGCSystemMsg = 102
	EGCSystemMsg_k_EGCMsgWebAPIJobRequestHttpResponse             EGCSystemMsg = 104
	EGCSystemMsg_k_EGCMsgWebAPIJobRequestForwardResponse          EGCSystemMsg = 105
	EGCSystemMsg_k_EGCMsgMemCachedGet                             EGCSystemMsg = 200
	EGCSystemMsg_k_EGCMsgMemCachedGetResponse                     EGCSystemMsg = 201
	EGCSystemMsg_k_EGCMsgMemCachedSet                             EGCSystemMsg = 202
	EGCSystemMsg_k_EGCMsgMemCachedDelete                          EGCSystemMsg = 203
	EGCSystemMsg_k_EGCMsgMemCachedStats                           EGCSystemMsg = 204
	EGCSystemMsg_k_EGCMsgMemCachedStatsResponse                   EGCSystemMsg = 205
	EGCSystemMsg_k_EGCMsgMasterSetDirectory                       EGCSystemMsg = 220
	EGCSystemMsg_k_EGCMsgMasterSetDirectoryResponse               EGCSystemMsg = 221
	EGCSystemMsg_k_EGCMsgMasterSetWebAPIRouting                   EGCSystemMsg = 222
	EGCSystemMsg_k_EGCMsgMasterSetWebAPIRoutingResponse           EGCSystemMsg = 223
	EGCSystemMsg_k_EGCMsgMasterSetClientMsgRouting                EGCSystemMsg = 224
	EGCSystemMsg_k_EGCMsgMasterSetClientMsgRoutingResponse        EGCSystemMsg = 225
	EGCSystemMsg_k_EGCMsgSetOptions                               EGCSystemMsg = 226
	EGCSystemMsg_k_EGCMsgSetOptionsResponse                       EGCSystemMsg = 227
	EGCSystemMsg_k_EGCMsgSystemBase2                              EGCSystemMsg = 500
	EGCSystemMsg_k_EGCMsgGetPurchaseTrustStatus                   EGCSystemMsg = 501
	EGCSystemMsg_k_EGCMsgGetPurchaseTrustStatusResponse           EGCSystemMsg = 502
	EGCSystemMsg_k_EGCMsgUpdateSession                            EGCSystemMsg = 503
	EGCSystemMsg_k_EGCMsgGCAccountVacStatusChange                 EGCSystemMsg = 504
	EGCSystemMsg_k_EGCMsgCheckFriendship                          EGCSystemMsg = 505
	EGCSystemMsg_k_EGCMsgCheckFriendshipResponse                  EGCSystemMsg = 506
	EGCSystemMsg_k_EGCMsgGetPartnerAccountLink                    EGCSystemMsg = 507
	EGCSystemMsg_k_EGCMsgGetPartnerAccountLinkResponse            EGCSystemMsg = 508
	EGCSystemMsg_k_EGCMsgDPPartnerMicroTxns                       EGCSystemMsg = 512
	EGCSystemMsg_k_EGCMsgDPPartnerMicroTxnsResponse               EGCSystemMsg = 513
	EGCSystemMsg_k_EGCMsgVacVerificationChange                    EGCSystemMsg = 518
	EGCSystemMsg_k_EGCMsgAccountPhoneNumberChange                 EGCSystemMsg = 519
	EGCSystemMsg_k_EGCMsgInviteUserToLobby                        EGCSystemMsg = 523
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataCategoriesRequest     EGCSystemMsg = 524
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataCategoriesResponse    EGCSystemMsg = 525
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataEntriesRequest        EGCSystemMsg = 526
	EGCSystemMsg_k_EGCMsgGetGamePersonalDataEntriesResponse       EGCSystemMsg = 527
	EGCSystemMsg_k_EGCMsgTerminateGamePersonalDataEntriesRequest  EGCSystemMsg = 528
	EGCSystemMsg_k_EGCMsgTerminateGamePersonalDataEntriesResponse EGCSystemMsg = 529
)

var EGCSystemMsg_name = map[int32]string{
	0:   "k_EGCMsgInvalid",
	1:   "k_EGCMsgMulti",
	10:  "k_EGCMsgGenericReply",
	50:  "k_EGCMsgSystemBase",
	51:  "k_EGCMsgAchievementAwarded",
	52:  "k_EGCMsgConCommand",
	53:  "k_EGCMsgStartPlaying",
	54:  "k_EGCMsgStopPlaying",
	55:  "k_EGCMsgStartGameserver",
	56:  "k_EGCMsgStopGameserver",
	57:  "k_EGCMsgWGRequest",
	58:  "k_EGCMsgWGResponse",
	59:  "k_EGCMsgGetUserGameStatsSchema",
	60:  "k_EGCMsgGetUserGameStatsSchemaResponse",
	61:  "k_EGCMsgGetUserStatsDEPRECATED",
	62:  "k_EGCMsgGetUserStatsResponse",
	63:  "k_EGCMsgAppInfoUpdated",
	64:  "k_EGCMsgValidateSession",
	65:  "k_EGCMsgValidateSessionResponse",
	66:  "k_EGCMsgLookupAccountFromInput",
	67:  "k_EGCMsgSendHTTPRequest",
	68:  "k_EGCMsgSendHTTPRequestResponse",
	69:  "k_EGCMsgPreTestSetup",
	70:  "k_EGCMsgRecordSupportAction",
	71:  "k_EGCMsgGetAccountDetails_DEPRECATED",
	73:  "k_EGCMsgReceiveInterAppMessage",
	74:  "k_EGCMsgFindAccounts",
	75:  "k_EGCMsgPostAlert",
	76:  "k_EGCMsgGetLicenses",
	77:  "k_EGCMsgGetUserStats",
	78:  "k_EGCMsgGetCommands",
	79:  "k_EGCMsgGetCommandsResponse",
	80:  "k_EGCMsgAddFreeLicense",
	81:  "k_EGCMsgAddFreeLicenseResponse",
	82:  "k_EGCMsgGetIPLocation",
	83:  "k_EGCMsgGetIPLocationResponse",
	84:  "k_EGCMsgSystemStatsSchema",
	85:  "k_EGCMsgGetSystemStats",
	86:  "k_EGCMsgGetSystemStatsResponse",
	87:  "k_EGCMsgSendEmail",
	88:  "k_EGCMsgSendEmailResponse",
	89:  "k_EGCMsgGetEmailTemplate",
	90:  "k_EGCMsgGetEmailTemplateResponse",
	91:  "k_EGCMsgGrantGuestPass",
	92:  "k_EGCMsgGrantGuestPassResponse",
	93:  "k_EGCMsgGetAccountDetails",
	94:  "k_EGCMsgGetAccountDetailsResponse",
	95:  "k_EGCMsgGetPersonaNames",
	96:  "k_EGCMsgGetPersonaNamesResponse",
	97:  "k_EGCMsgMultiplexMsg",
	98:  "k_EGCMsgMultiplexMsgResponse",
	101: "k_EGCMsgWebAPIRegisterInterfaces",
	102: "k_EGCMsgWebAPIJobRequest",
	104: "k_EGCMsgWebAPIJobRequestHttpResponse",
	105: "k_EGCMsgWebAPIJobRequestForwardResponse",
	200: "k_EGCMsgMemCachedGet",
	201: "k_EGCMsgMemCachedGetResponse",
	202: "k_EGCMsgMemCachedSet",
	203: "k_EGCMsgMemCachedDelete",
	204: "k_EGCMsgMemCachedStats",
	205: "k_EGCMsgMemCachedStatsResponse",
	220: "k_EGCMsgMasterSetDirectory",
	221: "k_EGCMsgMasterSetDirectoryResponse",
	222: "k_EGCMsgMasterSetWebAPIRouting",
	223: "k_EGCMsgMasterSetWebAPIRoutingResponse",
	224: "k_EGCMsgMasterSetClientMsgRouting",
	225: "k_EGCMsgMasterSetClientMsgRoutingResponse",
	226: "k_EGCMsgSetOptions",
	227: "k_EGCMsgSetOptionsResponse",
	500: "k_EGCMsgSystemBase2",
	501: "k_EGCMsgGetPurchaseTrustStatus",
	502: "k_EGCMsgGetPurchaseTrustStatusResponse",
	503: "k_EGCMsgUpdateSession",
	504: "k_EGCMsgGCAccountVacStatusChange",
	505: "k_EGCMsgCheckFriendship",
	506: "k_EGCMsgCheckFriendshipResponse",
	507: "k_EGCMsgGetPartnerAccountLink",
	508: "k_EGCMsgGetPartnerAccountLinkResponse",
	512: "k_EGCMsgDPPartnerMicroTxns",
	513: "k_EGCMsgDPPartnerMicroTxnsResponse",
	518: "k_EGCMsgVacVerificationChange",
	519: "k_EGCMsgAccountPhoneNumberChange",
	523: "k_EGCMsgInviteUserToLobby",
	524: "k_EGCMsgGetGamePersonalDataCategoriesRequest",
	525: "k_EGCMsgGetGamePersonalDataCategoriesResponse",
	526: "k_EGCMsgGetGamePersonalDataEntriesRequest",
	527: "k_EGCMsgGetGamePersonalDataEntriesResponse",
	528: "k_EGCMsgTerminateGamePersonalDataEntriesRequest",
	529: "k_EGCMsgTerminateGamePersonalDataEntriesResponse",
}

var EGCSystemMsg_value = map[string]int32{
	"k_EGCMsgInvalid":                                  0,
	"k_EGCMsgMulti":                                    1,
	"k_EGCMsgGenericReply":                             10,
	"k_EGCMsgSystemBase":                               50,
	"k_EGCMsgAchievementAwarded":                       51,
	"k_EGCMsgConCommand":                               52,
	"k_EGCMsgStartPlaying":                             53,
	"k_EGCMsgStopPlaying":                              54,
	"k_EGCMsgStartGameserver":                          55,
	"k_EGCMsgStopGameserver":                           56,
	"k_EGCMsgWGRequest":                                57,
	"k_EGCMsgWGResponse":                               58,
	"k_EGCMsgGetUserGameStatsSchema":                   59,
	"k_EGCMsgGetUserGameStatsSchemaResponse":           60,
	"k_EGCMsgGetUserStatsDEPRECATED":                   61,
	"k_EGCMsgGetUserStatsResponse":                     62,
	"k_EGCMsgAppInfoUpdated":                           63,
	"k_EGCMsgValidateSession":                          64,
	"k_EGCMsgValidateSessionResponse":                  65,
	"k_EGCMsgLookupAccountFromInput":                   66,
	"k_EGCMsgSendHTTPRequest":                          67,
	"k_EGCMsgSendHTTPRequestResponse":                  68,
	"k_EGCMsgPreTestSetup":                             69,
	"k_EGCMsgRecordSupportAction":                      70,
	"k_EGCMsgGetAccountDetails_DEPRECATED":             71,
	"k_EGCMsgReceiveInterAppMessage":                   73,
	"k_EGCMsgFindAccounts":                             74,
	"k_EGCMsgPostAlert":                                75,
	"k_EGCMsgGetLicenses":                              76,
	"k_EGCMsgGetUserStats":                             77,
	"k_EGCMsgGetCommands":                              78,
	"k_EGCMsgGetCommandsResponse":                      79,
	"k_EGCMsgAddFreeLicense":                           80,
	"k_EGCMsgAddFreeLicenseResponse":                   81,
	"k_EGCMsgGetIPLocation":                            82,
	"k_EGCMsgGetIPLocationResponse":                    83,
	"k_EGCMsgSystemStatsSchema":                        84,
	"k_EGCMsgGetSystemStats":                           85,
	"k_EGCMsgGetSystemStatsResponse":                   86,
	"k_EGCMsgSendEmail":                                87,
	"k_EGCMsgSendEmailResponse":                        88,
	"k_EGCMsgGetEmailTemplate":                         89,
	"k_EGCMsgGetEmailTemplateResponse":                 90,
	"k_EGCMsgGrantGuestPass":                           91,
	"k_EGCMsgGrantGuestPassResponse":                   92,
	"k_EGCMsgGetAccountDetails":                        93,
	"k_EGCMsgGetAccountDetailsResponse":                94,
	"k_EGCMsgGetPersonaNames":                          95,
	"k_EGCMsgGetPersonaNamesResponse":                  96,
	"k_EGCMsgMultiplexMsg":                             97,
	"k_EGCMsgMultiplexMsgResponse":                     98,
	"k_EGCMsgWebAPIRegisterInterfaces":                 101,
	"k_EGCMsgWebAPIJobRequest":                         102,
	"k_EGCMsgWebAPIJobRequestHttpResponse":             104,
	"k_EGCMsgWebAPIJobRequestForwardResponse":          105,
	"k_EGCMsgMemCachedGet":                             200,
	"k_EGCMsgMemCachedGetResponse":                     201,
	"k_EGCMsgMemCachedSet":                             202,
	"k_EGCMsgMemCachedDelete":                          203,
	"k_EGCMsgMemCachedStats":                           204,
	"k_EGCMsgMemCachedStatsResponse":                   205,
	"k_EGCMsgMasterSetDirectory":                       220,
	"k_EGCMsgMasterSetDirectoryResponse":               221,
	"k_EGCMsgMasterSetWebAPIRouting":                   222,
	"k_EGCMsgMasterSetWebAPIRoutingResponse":           223,
	"k_EGCMsgMasterSetClientMsgRouting":                224,
	"k_EGCMsgMasterSetClientMsgRoutingResponse":        225,
	"k_EGCMsgSetOptions":                               226,
	"k_EGCMsgSetOptionsResponse":                       227,
	"k_EGCMsgSystemBase2":                              500,
	"k_EGCMsgGetPurchaseTrustStatus":                   501,
	"k_EGCMsgGetPurchaseTrustStatusResponse":           502,
	"k_EGCMsgUpdateSession":                            503,
	"k_EGCMsgGCAccountVacStatusChange":                 504,
	"k_EGCMsgCheckFriendship":                          505,
	"k_EGCMsgCheckFriendshipResponse":                  506,
	"k_EGCMsgGetPartnerAccountLink":                    507,
	"k_EGCMsgGetPartnerAccountLinkResponse":            508,
	"k_EGCMsgDPPartnerMicroTxns":                       512,
	"k_EGCMsgDPPartnerMicroTxnsResponse":               513,
	"k_EGCMsgVacVerificationChange":                    518,
	"k_EGCMsgAccountPhoneNumberChange":                 519,
	"k_EGCMsgInviteUserToLobby":                        523,
	"k_EGCMsgGetGamePersonalDataCategoriesRequest":     524,
	"k_EGCMsgGetGamePersonalDataCategoriesResponse":    525,
	"k_EGCMsgGetGamePersonalDataEntriesRequest":        526,
	"k_EGCMsgGetGamePersonalDataEntriesResponse":       527,
	"k_EGCMsgTerminateGamePersonalDataEntriesRequest":  528,
	"k_EGCMsgTerminateGamePersonalDataEntriesResponse": 529,
}

func (x EGCSystemMsg) Enum() *EGCSystemMsg {
	p := new(EGCSystemMsg)
	*p = x
	return p
}

func (x EGCSystemMsg) String() string {
	return proto.EnumName(EGCSystemMsg_name, int32(x))
}

func (x *EGCSystemMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCSystemMsg_value, data, "EGCSystemMsg")
	if err != nil {
		return err
	}
	*x = EGCSystemMsg(value)
	return nil
}

func (EGCSystemMsg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{0}
}

type ESOMsg int32

const (
	ESOMsg_k_ESOMsg_Create                   ESOMsg = 21
	ESOMsg_k_ESOMsg_Update                   ESOMsg = 22
	ESOMsg_k_ESOMsg_Destroy                  ESOMsg = 23
	ESOMsg_k_ESOMsg_CacheSubscribed          ESOMsg = 24
	ESOMsg_k_ESOMsg_CacheUnsubscribed        ESOMsg = 25
	ESOMsg_k_ESOMsg_UpdateMultiple           ESOMsg = 26
	ESOMsg_k_ESOMsg_CacheSubscriptionCheck   ESOMsg = 27
	ESOMsg_k_ESOMsg_CacheSubscriptionRefresh ESOMsg = 28
)

var ESOMsg_name = map[int32]string{
	21: "k_ESOMsg_Create",
	22: "k_ESOMsg_Update",
	23: "k_ESOMsg_Destroy",
	24: "k_ESOMsg_CacheSubscribed",
	25: "k_ESOMsg_CacheUnsubscribed",
	26: "k_ESOMsg_UpdateMultiple",
	27: "k_ESOMsg_CacheSubscriptionCheck",
	28: "k_ESOMsg_CacheSubscriptionRefresh",
}

var ESOMsg_value = map[string]int32{
	"k_ESOMsg_Create":                   21,
	"k_ESOMsg_Update":                   22,
	"k_ESOMsg_Destroy":                  23,
	"k_ESOMsg_CacheSubscribed":          24,
	"k_ESOMsg_CacheUnsubscribed":        25,
	"k_ESOMsg_UpdateMultiple":           26,
	"k_ESOMsg_CacheSubscriptionCheck":   27,
	"k_ESOMsg_CacheSubscriptionRefresh": 28,
}

func (x ESOMsg) Enum() *ESOMsg {
	p := new(ESOMsg)
	*p = x
	return p
}

func (x ESOMsg) String() string {
	return proto.EnumName(ESOMsg_name, int32(x))
}

func (x *ESOMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ESOMsg_value, data, "ESOMsg")
	if err != nil {
		return err
	}
	*x = ESOMsg(value)
	return nil
}

func (ESOMsg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{1}
}

type EGCBaseClientMsg int32

const (
	EGCBaseClientMsg_k_EMsgGCClientWelcome          EGCBaseClientMsg = 4004
	EGCBaseClientMsg_k_EMsgGCServerWelcome          EGCBaseClientMsg = 4005
	EGCBaseClientMsg_k_EMsgGCClientHello            EGCBaseClientMsg = 4006
	EGCBaseClientMsg_k_EMsgGCServerHello            EGCBaseClientMsg = 4007
	EGCBaseClientMsg_k_EMsgGCClientConnectionStatus EGCBaseClientMsg = 4009
	EGCBaseClientMsg_k_EMsgGCServerConnectionStatus EGCBaseClientMsg = 4010
	EGCBaseClientMsg_k_EMsgGCClientHelloPartner     EGCBaseClientMsg = 4011
	EGCBaseClientMsg_k_EMsgGCClientHelloPW          EGCBaseClientMsg = 4012
	EGCBaseClientMsg_k_EMsgGCClientHelloR2          EGCBaseClientMsg = 4013
	EGCBaseClientMsg_k_EMsgGCClientHelloR3          EGCBaseClientMsg = 4014
	EGCBaseClientMsg_k_EMsgGCClientHelloR4          EGCBaseClientMsg = 4015
)

var EGCBaseClientMsg_name = map[int32]string{
	4004: "k_EMsgGCClientWelcome",
	4005: "k_EMsgGCServerWelcome",
	4006: "k_EMsgGCClientHello",
	4007: "k_EMsgGCServerHello",
	4009: "k_EMsgGCClientConnectionStatus",
	4010: "k_EMsgGCServerConnectionStatus",
	4011: "k_EMsgGCClientHelloPartner",
	4012: "k_EMsgGCClientHelloPW",
	4013: "k_EMsgGCClientHelloR2",
	4014: "k_EMsgGCClientHelloR3",
	4015: "k_EMsgGCClientHelloR4",
}

var EGCBaseClientMsg_value = map[string]int32{
	"k_EMsgGCClientWelcome":          4004,
	"k_EMsgGCServerWelcome":          4005,
	"k_EMsgGCClientHello":            4006,
	"k_EMsgGCServerHello":            4007,
	"k_EMsgGCClientConnectionStatus": 4009,
	"k_EMsgGCServerConnectionStatus": 4010,
	"k_EMsgGCClientHelloPartner":     4011,
	"k_EMsgGCClientHelloPW":          4012,
	"k_EMsgGCClientHelloR2":          4013,
	"k_EMsgGCClientHelloR3":          4014,
	"k_EMsgGCClientHelloR4":          4015,
}

func (x EGCBaseClientMsg) Enum() *EGCBaseClientMsg {
	p := new(EGCBaseClientMsg)
	*p = x
	return p
}

func (x EGCBaseClientMsg) String() string {
	return proto.EnumName(EGCBaseClientMsg_name, int32(x))
}

func (x *EGCBaseClientMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCBaseClientMsg_value, data, "EGCBaseClientMsg")
	if err != nil {
		return err
	}
	*x = EGCBaseClientMsg(value)
	return nil
}

func (EGCBaseClientMsg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{2}
}

type EGCToGCMsg int32

const (
	EGCToGCMsg_k_EGCToGCMsgMasterAck             EGCToGCMsg = 150
	EGCToGCMsg_k_EGCToGCMsgMasterAckResponse     EGCToGCMsg = 151
	EGCToGCMsg_k_EGCToGCMsgRouted                EGCToGCMsg = 152
	EGCToGCMsg_k_EGCToGCMsgRoutedReply           EGCToGCMsg = 153
	EGCToGCMsg_k_EMsgUpdateSessionIP             EGCToGCMsg = 154
	EGCToGCMsg_k_EMsgRequestSessionIP            EGCToGCMsg = 155
	EGCToGCMsg_k_EMsgRequestSessionIPResponse    EGCToGCMsg = 156
	EGCToGCMsg_k_EGCToGCMsgMasterStartupComplete EGCToGCMsg = 157
)

var EGCToGCMsg_name = map[int32]string{
	150: "k_EGCToGCMsgMasterAck",
	151: "k_EGCToGCMsgMasterAckResponse",
	152: "k_EGCToGCMsgRouted",
	153: "k_EGCToGCMsgRoutedReply",
	154: "k_EMsgUpdateSessionIP",
	155: "k_EMsgRequestSessionIP",
	156: "k_EMsgRequestSessionIPResponse",
	157: "k_EGCToGCMsgMasterStartupComplete",
}

var EGCToGCMsg_value = map[string]int32{
	"k_EGCToGCMsgMasterAck":             150,
	"k_EGCToGCMsgMasterAckResponse":     151,
	"k_EGCToGCMsgRouted":                152,
	"k_EGCToGCMsgRoutedReply":           153,
	"k_EMsgUpdateSessionIP":             154,
	"k_EMsgRequestSessionIP":            155,
	"k_EMsgRequestSessionIPResponse":    156,
	"k_EGCToGCMsgMasterStartupComplete": 157,
}

func (x EGCToGCMsg) Enum() *EGCToGCMsg {
	p := new(EGCToGCMsg)
	*p = x
	return p
}

func (x EGCToGCMsg) String() string {
	return proto.EnumName(EGCToGCMsg_name, int32(x))
}

func (x *EGCToGCMsg) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(EGCToGCMsg_value, data, "EGCToGCMsg")
	if err != nil {
		return err
	}
	*x = EGCToGCMsg(value)
	return nil
}

func (EGCToGCMsg) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{3}
}

type ECommunityItemClass int32

const (
	ECommunityItemClass_k_ECommunityItemClass_Invalid           ECommunityItemClass = 0
	ECommunityItemClass_k_ECommunityItemClass_Badge             ECommunityItemClass = 1
	ECommunityItemClass_k_ECommunityItemClass_GameCard          ECommunityItemClass = 2
	ECommunityItemClass_k_ECommunityItemClass_ProfileBackground ECommunityItemClass = 3
	ECommunityItemClass_k_ECommunityItemClass_Emoticon          ECommunityItemClass = 4
	ECommunityItemClass_k_ECommunityItemClass_BoosterPack       ECommunityItemClass = 5
	ECommunityItemClass_k_ECommunityItemClass_Consumable        ECommunityItemClass = 6
	ECommunityItemClass_k_ECommunityItemClass_GameGoo           ECommunityItemClass = 7
	ECommunityItemClass_k_ECommunityItemClass_ProfileModifier   ECommunityItemClass = 8
	ECommunityItemClass_k_ECommunityItemClass_Scene             ECommunityItemClass = 9
	ECommunityItemClass_k_ECommunityItemClass_SalienItem        ECommunityItemClass = 10
)

var ECommunityItemClass_name = map[int32]string{
	0:  "k_ECommunityItemClass_Invalid",
	1:  "k_ECommunityItemClass_Badge",
	2:  "k_ECommunityItemClass_GameCard",
	3:  "k_ECommunityItemClass_ProfileBackground",
	4:  "k_ECommunityItemClass_Emoticon",
	5:  "k_ECommunityItemClass_BoosterPack",
	6:  "k_ECommunityItemClass_Consumable",
	7:  "k_ECommunityItemClass_GameGoo",
	8:  "k_ECommunityItemClass_ProfileModifier",
	9:  "k_ECommunityItemClass_Scene",
	10: "k_ECommunityItemClass_SalienItem",
}

var ECommunityItemClass_value = map[string]int32{
	"k_ECommunityItemClass_Invalid":           0,
	"k_ECommunityItemClass_Badge":             1,
	"k_ECommunityItemClass_GameCard":          2,
	"k_ECommunityItemClass_ProfileBackground": 3,
	"k_ECommunityItemClass_Emoticon":          4,
	"k_ECommunityItemClass_BoosterPack":       5,
	"k_ECommunityItemClass_Consumable":        6,
	"k_ECommunityItemClass_GameGoo":           7,
	"k_ECommunityItemClass_ProfileModifier":   8,
	"k_ECommunityItemClass_Scene":             9,
	"k_ECommunityItemClass_SalienItem":        10,
}

func (x ECommunityItemClass) Enum() *ECommunityItemClass {
	p := new(ECommunityItemClass)
	*p = x
	return p
}

func (x ECommunityItemClass) String() string {
	return proto.EnumName(ECommunityItemClass_name, int32(x))
}

func (x *ECommunityItemClass) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ECommunityItemClass_value, data, "ECommunityItemClass")
	if err != nil {
		return err
	}
	*x = ECommunityItemClass(value)
	return nil
}

func (ECommunityItemClass) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{4}
}

type ECommunityItemAttribute int32

const (
	ECommunityItemAttribute_k_ECommunityItemAttribute_Invalid               ECommunityItemAttribute = 0
	ECommunityItemAttribute_k_ECommunityItemAttribute_CardBorder            ECommunityItemAttribute = 1
	ECommunityItemAttribute_k_ECommunityItemAttribute_Level                 ECommunityItemAttribute = 2
	ECommunityItemAttribute_k_ECommunityItemAttribute_IssueNumber           ECommunityItemAttribute = 3
	ECommunityItemAttribute_k_ECommunityItemAttribute_TradableTime          ECommunityItemAttribute = 4
	ECommunityItemAttribute_k_ECommunityItemAttribute_StorePackageID        ECommunityItemAttribute = 5
	ECommunityItemAttribute_k_ECommunityItemAttribute_CommunityItemAppID    ECommunityItemAttribute = 6
	ECommunityItemAttribute_k_ECommunityItemAttribute_CommunityItemType     ECommunityItemAttribute = 7
	ECommunityItemAttribute_k_ECommunityItemAttribute_ProfileModiferEnabled ECommunityItemAttribute = 8
	ECommunityItemAttribute_k_ECommunityItemAttribute_ExpiryTime            ECommunityItemAttribute = 9
)

var ECommunityItemAttribute_name = map[int32]string{
	0: "k_ECommunityItemAttribute_Invalid",
	1: "k_ECommunityItemAttribute_CardBorder",
	2: "k_ECommunityItemAttribute_Level",
	3: "k_ECommunityItemAttribute_IssueNumber",
	4: "k_ECommunityItemAttribute_TradableTime",
	5: "k_ECommunityItemAttribute_StorePackageID",
	6: "k_ECommunityItemAttribute_CommunityItemAppID",
	7: "k_ECommunityItemAttribute_CommunityItemType",
	8: "k_ECommunityItemAttribute_ProfileModiferEnabled",
	9: "k_ECommunityItemAttribute_ExpiryTime",
}

var ECommunityItemAttribute_value = map[string]int32{
	"k_ECommunityItemAttribute_Invalid":               0,
	"k_ECommunityItemAttribute_CardBorder":            1,
	"k_ECommunityItemAttribute_Level":                 2,
	"k_ECommunityItemAttribute_IssueNumber":           3,
	"k_ECommunityItemAttribute_TradableTime":          4,
	"k_ECommunityItemAttribute_StorePackageID":        5,
	"k_ECommunityItemAttribute_CommunityItemAppID":    6,
	"k_ECommunityItemAttribute_CommunityItemType":     7,
	"k_ECommunityItemAttribute_ProfileModiferEnabled": 8,
	"k_ECommunityItemAttribute_ExpiryTime":            9,
}

func (x ECommunityItemAttribute) Enum() *ECommunityItemAttribute {
	p := new(ECommunityItemAttribute)
	*p = x
	return p
}

func (x ECommunityItemAttribute) String() string {
	return proto.EnumName(ECommunityItemAttribute_name, int32(x))
}

func (x *ECommunityItemAttribute) UnmarshalJSON(data []byte) error {
	value, err := proto.UnmarshalJSONEnum(ECommunityItemAttribute_value, data, "ECommunityItemAttribute")
	if err != nil {
		return err
	}
	*x = ECommunityItemAttribute(value)
	return nil
}

func (ECommunityItemAttribute) EnumDescriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{5}
}

type CMsgGCHVacVerificationChange struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid                *uint32  `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	IsVerified           *bool    `protobuf:"varint,3,opt,name=is_verified,json=isVerified" json:"is_verified,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGCHVacVerificationChange) Reset()         { *m = CMsgGCHVacVerificationChange{} }
func (m *CMsgGCHVacVerificationChange) String() string { return proto.CompactTextString(m) }
func (*CMsgGCHVacVerificationChange) ProtoMessage()    {}
func (*CMsgGCHVacVerificationChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{0}
}

func (m *CMsgGCHVacVerificationChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCHVacVerificationChange.Unmarshal(m, b)
}
func (m *CMsgGCHVacVerificationChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCHVacVerificationChange.Marshal(b, m, deterministic)
}
func (m *CMsgGCHVacVerificationChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCHVacVerificationChange.Merge(m, src)
}
func (m *CMsgGCHVacVerificationChange) XXX_Size() int {
	return xxx_messageInfo_CMsgGCHVacVerificationChange.Size(m)
}
func (m *CMsgGCHVacVerificationChange) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCHVacVerificationChange.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCHVacVerificationChange proto.InternalMessageInfo

func (m *CMsgGCHVacVerificationChange) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgGCHVacVerificationChange) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CMsgGCHVacVerificationChange) GetIsVerified() bool {
	if m != nil && m.IsVerified != nil {
		return *m.IsVerified
	}
	return false
}

type CMsgGCHAccountPhoneNumberChange struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid                *uint32  `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	PhoneId              *uint64  `protobuf:"varint,3,opt,name=phone_id,json=phoneId" json:"phone_id,omitempty"`
	IsVerified           *bool    `protobuf:"varint,4,opt,name=is_verified,json=isVerified" json:"is_verified,omitempty"`
	IsIdentifying        *bool    `protobuf:"varint,5,opt,name=is_identifying,json=isIdentifying" json:"is_identifying,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGCHAccountPhoneNumberChange) Reset()         { *m = CMsgGCHAccountPhoneNumberChange{} }
func (m *CMsgGCHAccountPhoneNumberChange) String() string { return proto.CompactTextString(m) }
func (*CMsgGCHAccountPhoneNumberChange) ProtoMessage()    {}
func (*CMsgGCHAccountPhoneNumberChange) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{1}
}

func (m *CMsgGCHAccountPhoneNumberChange) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCHAccountPhoneNumberChange.Unmarshal(m, b)
}
func (m *CMsgGCHAccountPhoneNumberChange) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCHAccountPhoneNumberChange.Marshal(b, m, deterministic)
}
func (m *CMsgGCHAccountPhoneNumberChange) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCHAccountPhoneNumberChange.Merge(m, src)
}
func (m *CMsgGCHAccountPhoneNumberChange) XXX_Size() int {
	return xxx_messageInfo_CMsgGCHAccountPhoneNumberChange.Size(m)
}
func (m *CMsgGCHAccountPhoneNumberChange) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCHAccountPhoneNumberChange.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCHAccountPhoneNumberChange proto.InternalMessageInfo

func (m *CMsgGCHAccountPhoneNumberChange) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgGCHAccountPhoneNumberChange) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CMsgGCHAccountPhoneNumberChange) GetPhoneId() uint64 {
	if m != nil && m.PhoneId != nil {
		return *m.PhoneId
	}
	return 0
}

func (m *CMsgGCHAccountPhoneNumberChange) GetIsVerified() bool {
	if m != nil && m.IsVerified != nil {
		return *m.IsVerified
	}
	return false
}

func (m *CMsgGCHAccountPhoneNumberChange) GetIsIdentifying() bool {
	if m != nil && m.IsIdentifying != nil {
		return *m.IsIdentifying
	}
	return false
}

type CMsgGCHInviteUserToLobby struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid                *uint32  `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	SteamidInvited       *uint64  `protobuf:"fixed64,3,opt,name=steamid_invited,json=steamidInvited" json:"steamid_invited,omitempty"`
	SteamidLobby         *uint64  `protobuf:"fixed64,4,opt,name=steamid_lobby,json=steamidLobby" json:"steamid_lobby,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CMsgGCHInviteUserToLobby) Reset()         { *m = CMsgGCHInviteUserToLobby{} }
func (m *CMsgGCHInviteUserToLobby) String() string { return proto.CompactTextString(m) }
func (*CMsgGCHInviteUserToLobby) ProtoMessage()    {}
func (*CMsgGCHInviteUserToLobby) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{2}
}

func (m *CMsgGCHInviteUserToLobby) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CMsgGCHInviteUserToLobby.Unmarshal(m, b)
}
func (m *CMsgGCHInviteUserToLobby) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CMsgGCHInviteUserToLobby.Marshal(b, m, deterministic)
}
func (m *CMsgGCHInviteUserToLobby) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CMsgGCHInviteUserToLobby.Merge(m, src)
}
func (m *CMsgGCHInviteUserToLobby) XXX_Size() int {
	return xxx_messageInfo_CMsgGCHInviteUserToLobby.Size(m)
}
func (m *CMsgGCHInviteUserToLobby) XXX_DiscardUnknown() {
	xxx_messageInfo_CMsgGCHInviteUserToLobby.DiscardUnknown(m)
}

var xxx_messageInfo_CMsgGCHInviteUserToLobby proto.InternalMessageInfo

func (m *CMsgGCHInviteUserToLobby) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CMsgGCHInviteUserToLobby) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CMsgGCHInviteUserToLobby) GetSteamidInvited() uint64 {
	if m != nil && m.SteamidInvited != nil {
		return *m.SteamidInvited
	}
	return 0
}

func (m *CMsgGCHInviteUserToLobby) GetSteamidLobby() uint64 {
	if m != nil && m.SteamidLobby != nil {
		return *m.SteamidLobby
	}
	return 0
}

type CQuest_PublisherAddCommunityItemsToPlayer_Request struct {
	Steamid              *uint64                                                        `protobuf:"varint,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid                *uint32                                                        `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	MatchItemType        *uint32                                                        `protobuf:"varint,3,opt,name=match_item_type,json=matchItemType" json:"match_item_type,omitempty"`
	MatchItemClass       *uint32                                                        `protobuf:"varint,4,opt,name=match_item_class,json=matchItemClass" json:"match_item_class,omitempty"`
	PrefixItemName       *string                                                        `protobuf:"bytes,5,opt,name=prefix_item_name,json=prefixItemName" json:"prefix_item_name,omitempty"`
	Attributes           []*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute `protobuf:"bytes,6,rep,name=attributes" json:"attributes,omitempty"`
	Note                 *string                                                        `protobuf:"bytes,7,opt,name=note" json:"note,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                       `json:"-"`
	XXX_unrecognized     []byte                                                         `json:"-"`
	XXX_sizecache        int32                                                          `json:"-"`
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) Reset() {
	*m = CQuest_PublisherAddCommunityItemsToPlayer_Request{}
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CQuest_PublisherAddCommunityItemsToPlayer_Request) ProtoMessage() {}
func (*CQuest_PublisherAddCommunityItemsToPlayer_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{3}
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request.Unmarshal(m, b)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request.Marshal(b, m, deterministic)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request.Merge(m, src)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) XXX_Size() int {
	return xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request.Size(m)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request proto.InternalMessageInfo

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetMatchItemType() uint32 {
	if m != nil && m.MatchItemType != nil {
		return *m.MatchItemType
	}
	return 0
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetMatchItemClass() uint32 {
	if m != nil && m.MatchItemClass != nil {
		return *m.MatchItemClass
	}
	return 0
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetPrefixItemName() string {
	if m != nil && m.PrefixItemName != nil {
		return *m.PrefixItemName
	}
	return ""
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetAttributes() []*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute {
	if m != nil {
		return m.Attributes
	}
	return nil
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request) GetNote() string {
	if m != nil && m.Note != nil {
		return *m.Note
	}
	return ""
}

type CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute struct {
	Attribute            *uint32  `protobuf:"varint,1,opt,name=attribute" json:"attribute,omitempty"`
	Value                *uint64  `protobuf:"varint,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) Reset() {
	*m = CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute{}
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) String() string {
	return proto.CompactTextString(m)
}
func (*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) ProtoMessage() {}
func (*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{3, 0}
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute.Unmarshal(m, b)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute.Marshal(b, m, deterministic)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute.Merge(m, src)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) XXX_Size() int {
	return xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute.Size(m)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) XXX_DiscardUnknown() {
	xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute.DiscardUnknown(m)
}

var xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute proto.InternalMessageInfo

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) GetAttribute() uint32 {
	if m != nil && m.Attribute != nil {
		return *m.Attribute
	}
	return 0
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute) GetValue() uint64 {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return 0
}

type CQuest_PublisherAddCommunityItemsToPlayer_Response struct {
	ItemsMatched         *uint32  `protobuf:"varint,1,opt,name=items_matched,json=itemsMatched" json:"items_matched,omitempty"`
	ItemsGranted         *uint32  `protobuf:"varint,2,opt,name=items_granted,json=itemsGranted" json:"items_granted,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Response) Reset() {
	*m = CQuest_PublisherAddCommunityItemsToPlayer_Response{}
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CQuest_PublisherAddCommunityItemsToPlayer_Response) ProtoMessage() {}
func (*CQuest_PublisherAddCommunityItemsToPlayer_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{4}
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Response.Unmarshal(m, b)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Response.Marshal(b, m, deterministic)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Response.Merge(m, src)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Response) XXX_Size() int {
	return xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Response.Size(m)
}
func (m *CQuest_PublisherAddCommunityItemsToPlayer_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CQuest_PublisherAddCommunityItemsToPlayer_Response proto.InternalMessageInfo

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Response) GetItemsMatched() uint32 {
	if m != nil && m.ItemsMatched != nil {
		return *m.ItemsMatched
	}
	return 0
}

func (m *CQuest_PublisherAddCommunityItemsToPlayer_Response) GetItemsGranted() uint32 {
	if m != nil && m.ItemsGranted != nil {
		return *m.ItemsGranted
	}
	return 0
}

type CCommunity_GamePersonalDataCategoryInfo struct {
	Type                 *string  `protobuf:"bytes,1,opt,name=type" json:"type,omitempty"`
	LocalizationToken    *string  `protobuf:"bytes,2,opt,name=localization_token,json=localizationToken" json:"localization_token,omitempty"`
	TemplateFile         *string  `protobuf:"bytes,3,opt,name=template_file,json=templateFile" json:"template_file,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCommunity_GamePersonalDataCategoryInfo) Reset() {
	*m = CCommunity_GamePersonalDataCategoryInfo{}
}
func (m *CCommunity_GamePersonalDataCategoryInfo) String() string { return proto.CompactTextString(m) }
func (*CCommunity_GamePersonalDataCategoryInfo) ProtoMessage()    {}
func (*CCommunity_GamePersonalDataCategoryInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{5}
}

func (m *CCommunity_GamePersonalDataCategoryInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCommunity_GamePersonalDataCategoryInfo.Unmarshal(m, b)
}
func (m *CCommunity_GamePersonalDataCategoryInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCommunity_GamePersonalDataCategoryInfo.Marshal(b, m, deterministic)
}
func (m *CCommunity_GamePersonalDataCategoryInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCommunity_GamePersonalDataCategoryInfo.Merge(m, src)
}
func (m *CCommunity_GamePersonalDataCategoryInfo) XXX_Size() int {
	return xxx_messageInfo_CCommunity_GamePersonalDataCategoryInfo.Size(m)
}
func (m *CCommunity_GamePersonalDataCategoryInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_CCommunity_GamePersonalDataCategoryInfo.DiscardUnknown(m)
}

var xxx_messageInfo_CCommunity_GamePersonalDataCategoryInfo proto.InternalMessageInfo

func (m *CCommunity_GamePersonalDataCategoryInfo) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *CCommunity_GamePersonalDataCategoryInfo) GetLocalizationToken() string {
	if m != nil && m.LocalizationToken != nil {
		return *m.LocalizationToken
	}
	return ""
}

func (m *CCommunity_GamePersonalDataCategoryInfo) GetTemplateFile() string {
	if m != nil && m.TemplateFile != nil {
		return *m.TemplateFile
	}
	return ""
}

type CCommunity_GetGamePersonalDataCategories_Request struct {
	Appid                *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCommunity_GetGamePersonalDataCategories_Request) Reset() {
	*m = CCommunity_GetGamePersonalDataCategories_Request{}
}
func (m *CCommunity_GetGamePersonalDataCategories_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_GetGamePersonalDataCategories_Request) ProtoMessage() {}
func (*CCommunity_GetGamePersonalDataCategories_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{6}
}

func (m *CCommunity_GetGamePersonalDataCategories_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Request.Unmarshal(m, b)
}
func (m *CCommunity_GetGamePersonalDataCategories_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Request.Marshal(b, m, deterministic)
}
func (m *CCommunity_GetGamePersonalDataCategories_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Request.Merge(m, src)
}
func (m *CCommunity_GetGamePersonalDataCategories_Request) XXX_Size() int {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Request.Size(m)
}
func (m *CCommunity_GetGamePersonalDataCategories_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Request proto.InternalMessageInfo

func (m *CCommunity_GetGamePersonalDataCategories_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

type CCommunity_GetGamePersonalDataCategories_Response struct {
	Categories           []*CCommunity_GamePersonalDataCategoryInfo `protobuf:"bytes,1,rep,name=categories" json:"categories,omitempty"`
	AppAssetsBasename    *string                                    `protobuf:"bytes,2,opt,name=app_assets_basename,json=appAssetsBasename" json:"app_assets_basename,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                   `json:"-"`
	XXX_unrecognized     []byte                                     `json:"-"`
	XXX_sizecache        int32                                      `json:"-"`
}

func (m *CCommunity_GetGamePersonalDataCategories_Response) Reset() {
	*m = CCommunity_GetGamePersonalDataCategories_Response{}
}
func (m *CCommunity_GetGamePersonalDataCategories_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_GetGamePersonalDataCategories_Response) ProtoMessage() {}
func (*CCommunity_GetGamePersonalDataCategories_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{7}
}

func (m *CCommunity_GetGamePersonalDataCategories_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Response.Unmarshal(m, b)
}
func (m *CCommunity_GetGamePersonalDataCategories_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Response.Marshal(b, m, deterministic)
}
func (m *CCommunity_GetGamePersonalDataCategories_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Response.Merge(m, src)
}
func (m *CCommunity_GetGamePersonalDataCategories_Response) XXX_Size() int {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Response.Size(m)
}
func (m *CCommunity_GetGamePersonalDataCategories_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCommunity_GetGamePersonalDataCategories_Response proto.InternalMessageInfo

func (m *CCommunity_GetGamePersonalDataCategories_Response) GetCategories() []*CCommunity_GamePersonalDataCategoryInfo {
	if m != nil {
		return m.Categories
	}
	return nil
}

func (m *CCommunity_GetGamePersonalDataCategories_Response) GetAppAssetsBasename() string {
	if m != nil && m.AppAssetsBasename != nil {
		return *m.AppAssetsBasename
	}
	return ""
}

type CCommunity_GetGamePersonalDataEntries_Request struct {
	Appid                *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Steamid              *uint64  `protobuf:"varint,2,opt,name=steamid" json:"steamid,omitempty"`
	Type                 *string  `protobuf:"bytes,3,opt,name=type" json:"type,omitempty"`
	ContinueToken        *string  `protobuf:"bytes,4,opt,name=continue_token,json=continueToken" json:"continue_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) Reset() {
	*m = CCommunity_GetGamePersonalDataEntries_Request{}
}
func (m *CCommunity_GetGamePersonalDataEntries_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_GetGamePersonalDataEntries_Request) ProtoMessage() {}
func (*CCommunity_GetGamePersonalDataEntries_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{8}
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Request.Unmarshal(m, b)
}
func (m *CCommunity_GetGamePersonalDataEntries_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Request.Marshal(b, m, deterministic)
}
func (m *CCommunity_GetGamePersonalDataEntries_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Request.Merge(m, src)
}
func (m *CCommunity_GetGamePersonalDataEntries_Request) XXX_Size() int {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Request.Size(m)
}
func (m *CCommunity_GetGamePersonalDataEntries_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Request proto.InternalMessageInfo

func (m *CCommunity_GetGamePersonalDataEntries_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) GetType() string {
	if m != nil && m.Type != nil {
		return *m.Type
	}
	return ""
}

func (m *CCommunity_GetGamePersonalDataEntries_Request) GetContinueToken() string {
	if m != nil && m.ContinueToken != nil {
		return *m.ContinueToken
	}
	return ""
}

type CCommunity_GetGamePersonalDataEntries_Response struct {
	Gceresult            *uint32  `protobuf:"varint,1,opt,name=gceresult" json:"gceresult,omitempty"`
	Entries              []string `protobuf:"bytes,2,rep,name=entries" json:"entries,omitempty"`
	ContinueToken        *string  `protobuf:"bytes,3,opt,name=continue_token,json=continueToken" json:"continue_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCommunity_GetGamePersonalDataEntries_Response) Reset() {
	*m = CCommunity_GetGamePersonalDataEntries_Response{}
}
func (m *CCommunity_GetGamePersonalDataEntries_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_GetGamePersonalDataEntries_Response) ProtoMessage() {}
func (*CCommunity_GetGamePersonalDataEntries_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{9}
}

func (m *CCommunity_GetGamePersonalDataEntries_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Response.Unmarshal(m, b)
}
func (m *CCommunity_GetGamePersonalDataEntries_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Response.Marshal(b, m, deterministic)
}
func (m *CCommunity_GetGamePersonalDataEntries_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Response.Merge(m, src)
}
func (m *CCommunity_GetGamePersonalDataEntries_Response) XXX_Size() int {
	return xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Response.Size(m)
}
func (m *CCommunity_GetGamePersonalDataEntries_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCommunity_GetGamePersonalDataEntries_Response proto.InternalMessageInfo

func (m *CCommunity_GetGamePersonalDataEntries_Response) GetGceresult() uint32 {
	if m != nil && m.Gceresult != nil {
		return *m.Gceresult
	}
	return 0
}

func (m *CCommunity_GetGamePersonalDataEntries_Response) GetEntries() []string {
	if m != nil {
		return m.Entries
	}
	return nil
}

func (m *CCommunity_GetGamePersonalDataEntries_Response) GetContinueToken() string {
	if m != nil && m.ContinueToken != nil {
		return *m.ContinueToken
	}
	return ""
}

type CCommunity_TerminateGamePersonalDataEntries_Request struct {
	Appid                *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Steamid              *uint64  `protobuf:"varint,2,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Request) Reset() {
	*m = CCommunity_TerminateGamePersonalDataEntries_Request{}
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_TerminateGamePersonalDataEntries_Request) ProtoMessage() {}
func (*CCommunity_TerminateGamePersonalDataEntries_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{10}
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Request.Unmarshal(m, b)
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Request.Marshal(b, m, deterministic)
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Request.Merge(m, src)
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Request) XXX_Size() int {
	return xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Request.Size(m)
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Request proto.InternalMessageInfo

func (m *CCommunity_TerminateGamePersonalDataEntries_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CCommunity_TerminateGamePersonalDataEntries_Response struct {
	Gceresult            *uint32  `protobuf:"varint,1,opt,name=gceresult" json:"gceresult,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Response) Reset() {
	*m = CCommunity_TerminateGamePersonalDataEntries_Response{}
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CCommunity_TerminateGamePersonalDataEntries_Response) ProtoMessage() {}
func (*CCommunity_TerminateGamePersonalDataEntries_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d00de04f4cda8072, []int{11}
}

func (m *CCommunity_TerminateGamePersonalDataEntries_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Response.Unmarshal(m, b)
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Response.Marshal(b, m, deterministic)
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Response.Merge(m, src)
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Response) XXX_Size() int {
	return xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Response.Size(m)
}
func (m *CCommunity_TerminateGamePersonalDataEntries_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CCommunity_TerminateGamePersonalDataEntries_Response proto.InternalMessageInfo

func (m *CCommunity_TerminateGamePersonalDataEntries_Response) GetGceresult() uint32 {
	if m != nil && m.Gceresult != nil {
		return *m.Gceresult
	}
	return 0
}

func init() {
	proto.RegisterEnum("EGCSystemMsg", EGCSystemMsg_name, EGCSystemMsg_value)
	proto.RegisterEnum("ESOMsg", ESOMsg_name, ESOMsg_value)
	proto.RegisterEnum("EGCBaseClientMsg", EGCBaseClientMsg_name, EGCBaseClientMsg_value)
	proto.RegisterEnum("EGCToGCMsg", EGCToGCMsg_name, EGCToGCMsg_value)
	proto.RegisterEnum("ECommunityItemClass", ECommunityItemClass_name, ECommunityItemClass_value)
	proto.RegisterEnum("ECommunityItemAttribute", ECommunityItemAttribute_name, ECommunityItemAttribute_value)
	proto.RegisterType((*CMsgGCHVacVerificationChange)(nil), "CMsgGCHVacVerificationChange")
	proto.RegisterType((*CMsgGCHAccountPhoneNumberChange)(nil), "CMsgGCHAccountPhoneNumberChange")
	proto.RegisterType((*CMsgGCHInviteUserToLobby)(nil), "CMsgGCHInviteUserToLobby")
	proto.RegisterType((*CQuest_PublisherAddCommunityItemsToPlayer_Request)(nil), "CQuest_PublisherAddCommunityItemsToPlayer_Request")
	proto.RegisterType((*CQuest_PublisherAddCommunityItemsToPlayer_Request_Attribute)(nil), "CQuest_PublisherAddCommunityItemsToPlayer_Request.Attribute")
	proto.RegisterType((*CQuest_PublisherAddCommunityItemsToPlayer_Response)(nil), "CQuest_PublisherAddCommunityItemsToPlayer_Response")
	proto.RegisterType((*CCommunity_GamePersonalDataCategoryInfo)(nil), "CCommunity_GamePersonalDataCategoryInfo")
	proto.RegisterType((*CCommunity_GetGamePersonalDataCategories_Request)(nil), "CCommunity_GetGamePersonalDataCategories_Request")
	proto.RegisterType((*CCommunity_GetGamePersonalDataCategories_Response)(nil), "CCommunity_GetGamePersonalDataCategories_Response")
	proto.RegisterType((*CCommunity_GetGamePersonalDataEntries_Request)(nil), "CCommunity_GetGamePersonalDataEntries_Request")
	proto.RegisterType((*CCommunity_GetGamePersonalDataEntries_Response)(nil), "CCommunity_GetGamePersonalDataEntries_Response")
	proto.RegisterType((*CCommunity_TerminateGamePersonalDataEntries_Request)(nil), "CCommunity_TerminateGamePersonalDataEntries_Request")
	proto.RegisterType((*CCommunity_TerminateGamePersonalDataEntries_Response)(nil), "CCommunity_TerminateGamePersonalDataEntries_Response")
}

func init() { proto.RegisterFile("gcsystemmsgs.proto", fileDescriptor_d00de04f4cda8072) }

var fileDescriptor_d00de04f4cda8072 = []byte{
	// 2385 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x58, 0x5b, 0x73, 0x1c, 0x47,
	0xf5, 0xcf, 0x68, 0xd7, 0xb2, 0xd5, 0xb1, 0x9c, 0x4e, 0x3b, 0x89, 0xd7, 0xb6, 0x12, 0x29, 0x9b,
	0x38, 0x56, 0x94, 0x44, 0x49, 0x6c, 0xe7, 0xff, 0xe7, 0x12, 0x08, 0xeb, 0xd5, 0x6a, 0xb5, 0x41,
	0x8a, 0x37, 0xb3, 0x6b, 0x9b, 0x4b, 0x60, 0xe9, 0x9d, 0x39, 0x5a, 0x75, 0x69, 0x76, 0x7a, 0xe8,
	0xee, 0x15, 0x5e, 0x1e, 0xa8, 0xf0, 0x02, 0x45, 0x71, 0x09, 0xe1, 0x01, 0x42, 0x80, 0x37, 0x2e,
	0xc5, 0x25, 0xc0, 0x03, 0x9f, 0x81, 0xe2, 0xfa, 0x4a, 0x15, 0x55, 0xdc, 0xf9, 0x00, 0xbc, 0x70,
	0x87, 0x07, 0xaa, 0x67, 0x7a, 0x66, 0x7a, 0xa5, 0x1d, 0x5b, 0xa6, 0x78, 0xdb, 0x39, 0xbf, 0xdf,
	0xb9, 0xf4, 0xe9, 0xd3, 0xe7, 0xf4, 0x36, 0x22, 0x03, 0x4f, 0x8e, 0xa5, 0x82, 0xe1, 0x50, 0x0e,
	0xe4, 0x6a, 0x24, 0xb8, 0xe2, 0x55, 0x8e, 0x16, 0xea, 0x5b, 0x72, 0xd0, 0xac, 0x6f, 0x5c, 0xa3,
	0xde, 0x35, 0x10, 0x6c, 0x9b, 0x79, 0x54, 0x31, 0x1e, 0xd6, 0x77, 0x68, 0x38, 0x00, 0x52, 0x41,
	0x47, 0xa5, 0x02, 0x3a, 0x64, 0x7e, 0xc5, 0x59, 0x72, 0x96, 0x67, 0xdd, 0xf4, 0x93, 0xdc, 0x83,
	0x8e, 0xd0, 0x28, 0x62, 0x7e, 0x65, 0x66, 0xc9, 0x59, 0x9e, 0x77, 0x93, 0x0f, 0xb2, 0x88, 0xee,
	0x64, 0xb2, 0xb7, 0x17, 0x1b, 0x02, 0xbf, 0x52, 0x5a, 0x72, 0x96, 0x8f, 0xb9, 0x88, 0xc9, 0x6b,
	0x46, 0x52, 0xfd, 0x81, 0x83, 0x16, 0x8d, 0xc7, 0x9a, 0xe7, 0xf1, 0x51, 0xa8, 0xda, 0x3b, 0x3c,
	0x84, 0x17, 0x46, 0xc3, 0x3e, 0x88, 0xff, 0xd2, 0xe9, 0x69, 0x74, 0x2c, 0xd2, 0x46, 0x7a, 0x2c,
	0xf1, 0x58, 0x76, 0x8f, 0xc6, 0xdf, 0xad, 0x03, 0xf1, 0x94, 0xf7, 0xc7, 0x43, 0xce, 0xa1, 0x13,
	0x4c, 0xf6, 0x98, 0x0f, 0xa1, 0x62, 0xdb, 0x63, 0x16, 0x0e, 0x2a, 0x47, 0x62, 0xce, 0x3c, 0x93,
	0xad, 0x5c, 0x58, 0x7d, 0xcd, 0x41, 0x15, 0x13, 0x76, 0x2b, 0xdc, 0x63, 0x0a, 0xae, 0x4a, 0x10,
	0x5d, 0xbe, 0xc9, 0xfb, 0xfd, 0xf1, 0x6d, 0xc7, 0x7b, 0x1e, 0xdd, 0x65, 0x08, 0x3d, 0x16, 0x1b,
	0x4b, 0xc2, 0x9e, 0x75, 0x4f, 0x18, 0x71, 0xe2, 0xc2, 0x27, 0x0f, 0xa1, 0xf9, 0x94, 0x18, 0x68,
	0x4f, 0x71, 0xfc, 0xb3, 0xee, 0x71, 0x23, 0x8c, 0xbd, 0x57, 0x3f, 0x57, 0x42, 0x4f, 0xd7, 0x5f,
	0x1c, 0x81, 0x54, 0xbd, 0xf6, 0xa8, 0x1f, 0x30, 0xb9, 0x03, 0xa2, 0xe6, 0xfb, 0x75, 0x3e, 0x1c,
	0x8e, 0x42, 0xa6, 0xc6, 0x2d, 0x05, 0x43, 0xd9, 0xe5, 0xed, 0x80, 0x8e, 0x41, 0xf4, 0x5c, 0xf8,
	0xa0, 0xa6, 0xee, 0x8f, 0xb9, 0x7c, 0xab, 0x98, 0x1f, 0x41, 0x77, 0x0d, 0xa9, 0xf2, 0x76, 0x7a,
	0x4c, 0xc1, 0xb0, 0xa7, 0xc6, 0x11, 0xc4, 0x31, 0xcf, 0xbb, 0xf3, 0xb1, 0x58, 0x3b, 0xe9, 0x8e,
	0x23, 0x20, 0xcb, 0x08, 0x5b, 0x3c, 0x2f, 0xa0, 0x52, 0xc6, 0x51, 0xcf, 0xbb, 0x27, 0x32, 0x62,
	0x5d, 0x4b, 0x35, 0x33, 0x12, 0xb0, 0xcd, 0x6e, 0x24, 0xd4, 0x90, 0x0e, 0x21, 0xce, 0xfd, 0x9c,
	0x7b, 0x22, 0x91, 0x6b, 0xea, 0x0b, 0x74, 0x08, 0xe4, 0x25, 0x84, 0xa8, 0x52, 0x82, 0xf5, 0x47,
	0x0a, 0x64, 0x65, 0x76, 0xa9, 0xb4, 0x7c, 0xe7, 0x85, 0x67, 0x57, 0x6f, 0x7b, 0xcd, 0xab, 0xb5,
	0xd4, 0x88, 0x6b, 0xd9, 0x23, 0x04, 0x95, 0x43, 0xae, 0xa0, 0x72, 0x34, 0xf6, 0x1d, 0xff, 0x3e,
	0xf3, 0x1c, 0x9a, 0xcb, 0xc8, 0x64, 0x01, 0xcd, 0x65, 0xf4, 0x38, 0x59, 0xf3, 0x6e, 0x2e, 0xd0,
	0xe9, 0xda, 0xa3, 0xc1, 0x08, 0xe2, 0x74, 0x95, 0xdd, 0xe4, 0xa3, 0xfa, 0x11, 0x74, 0xe1, 0x76,
	0xe2, 0x93, 0x11, 0x0f, 0x25, 0xe8, 0xfd, 0xd6, 0xb9, 0x90, 0xbd, 0x38, 0x55, 0xe0, 0x1b, 0x6f,
	0xc7, 0x63, 0xe1, 0x56, 0x22, 0xcb, 0x49, 0x03, 0x41, 0x43, 0x5d, 0x3b, 0x33, 0x16, 0xa9, 0x99,
	0xc8, 0xaa, 0xaf, 0x3a, 0xe8, 0x7c, 0x3d, 0x73, 0xd7, 0x6b, 0xd2, 0x21, 0xb4, 0x41, 0x48, 0x1e,
	0xd2, 0x60, 0x8d, 0x2a, 0x5a, 0xa7, 0x0a, 0x06, 0x5c, 0x8c, 0x5b, 0xe1, 0x36, 0xd7, 0x09, 0x88,
	0xf7, 0xd3, 0x49, 0x12, 0xa0, 0x7f, 0x93, 0x27, 0x10, 0x09, 0xb8, 0x47, 0x03, 0xf6, 0xe1, 0xb8,
	0x1b, 0xf4, 0x14, 0xdf, 0x85, 0x30, 0xf6, 0x34, 0xe7, 0xde, 0x6d, 0x23, 0x5d, 0x0d, 0xe8, 0x98,
	0x14, 0x0c, 0xa3, 0x80, 0x2a, 0xe8, 0x6d, 0xb3, 0x20, 0xa9, 0x8d, 0x39, 0xf7, 0x78, 0x2a, 0x5c,
	0x67, 0x01, 0x54, 0x37, 0xd0, 0x53, 0x76, 0x48, 0xa0, 0x0a, 0xa2, 0x62, 0x20, 0xb3, 0x32, 0xcd,
	0x8a, 0xd1, 0xb1, 0x8a, 0xb1, 0xfa, 0x86, 0x83, 0x9e, 0xbe, 0x0d, 0x53, 0x26, 0xbb, 0x1b, 0x08,
	0x79, 0x99, 0xb8, 0xe2, 0xc4, 0x65, 0xb4, 0xbc, 0x7a, 0xc8, 0x2c, 0xb9, 0x96, 0x2e, 0x59, 0x45,
	0x27, 0x69, 0x14, 0xf5, 0xa8, 0x94, 0xa0, 0x64, 0xaf, 0x4f, 0x25, 0xc4, 0xd5, 0x6b, 0xd2, 0x43,
	0xa3, 0xa8, 0x16, 0x23, 0x97, 0x0d, 0x50, 0x7d, 0xdd, 0x41, 0x4f, 0xdc, 0x3c, 0xde, 0x46, 0xa8,
	0x6e, 0xbd, 0x6e, 0xfb, 0xd0, 0xce, 0x4c, 0x1e, 0xda, 0x74, 0x0f, 0x4b, 0xd6, 0x1e, 0x9e, 0x43,
	0x27, 0x3c, 0x1e, 0x2a, 0x16, 0x8e, 0xc0, 0xec, 0x5f, 0x39, 0x46, 0xe7, 0x53, 0x69, 0xbc, 0x77,
	0xd5, 0x57, 0x1c, 0xb4, 0x7a, 0xd8, 0xe0, 0x4c, 0x26, 0x17, 0xd0, 0xdc, 0xc0, 0x03, 0x01, 0x72,
	0x14, 0xa8, 0xf4, 0x44, 0x64, 0x02, 0x1d, 0x25, 0x24, 0x1a, 0x95, 0x99, 0xa5, 0xd2, 0xf2, 0x9c,
	0x9b, 0x7e, 0x4e, 0x89, 0xa8, 0x34, 0x2d, 0x22, 0x40, 0x17, 0xad, 0x80, 0xba, 0x20, 0x86, 0x2c,
	0xa4, 0x0a, 0xfe, 0xc7, 0x39, 0xab, 0x76, 0xd1, 0xa5, 0xdb, 0x73, 0x73, 0x98, 0xd5, 0xaf, 0xfc,
	0xf0, 0x14, 0x3a, 0xde, 0x68, 0xd6, 0x3b, 0xf1, 0xa4, 0xdd, 0x92, 0x03, 0x72, 0x12, 0xdd, 0xb5,
	0xdb, 0x6b, 0x34, 0xf5, 0xf4, 0x68, 0x85, 0x7b, 0x34, 0x60, 0x3e, 0xbe, 0x83, 0xdc, 0x8d, 0xe6,
	0x53, 0xe1, 0xd6, 0x28, 0x50, 0x0c, 0x3b, 0xa4, 0x82, 0xee, 0x49, 0x45, 0x4d, 0x08, 0x41, 0x30,
	0xcf, 0x85, 0x28, 0x18, 0x63, 0x44, 0xee, 0x43, 0x24, 0x45, 0x12, 0xb3, 0xba, 0xb0, 0xf0, 0x05,
	0xf2, 0x00, 0x3a, 0x93, 0xca, 0x6b, 0xde, 0x0e, 0x83, 0x3d, 0x18, 0x42, 0xa8, 0x6a, 0x1f, 0xa2,
	0xc2, 0x07, 0x1f, 0x5f, 0xb4, 0xf5, 0xea, 0x3c, 0xd4, 0x4b, 0xa5, 0xa1, 0x8f, 0x2f, 0xd9, 0x9e,
	0x3a, 0x8a, 0x0a, 0xa5, 0xdb, 0x10, 0x0b, 0x07, 0xf8, 0x19, 0x72, 0x0a, 0x9d, 0xcc, 0x11, 0x1e,
	0xa5, 0xc0, 0xff, 0x91, 0xb3, 0xe8, 0xd4, 0x84, 0x8a, 0x4e, 0x92, 0x04, 0xb1, 0x07, 0x02, 0xff,
	0x3f, 0x39, 0x83, 0xee, 0xb3, 0xb5, 0x2c, 0xec, 0x4d, 0xe4, 0x5e, 0x74, 0x77, 0x8a, 0x5d, 0x6f,
	0x9a, 0x9d, 0xc2, 0x6f, 0xb6, 0x43, 0xd3, 0xe2, 0x24, 0xb3, 0xf8, 0x2d, 0xa4, 0x8a, 0x1e, 0xc8,
	0x93, 0xa0, 0xf4, 0x90, 0xd5, 0xd6, 0x3a, 0x8a, 0x2a, 0xd9, 0xf1, 0x76, 0x60, 0x48, 0xf1, 0x5b,
	0xc9, 0x0a, 0x7a, 0xe4, 0xe6, 0x9c, 0xcc, 0xde, 0xb3, 0x53, 0xec, 0xc5, 0xbc, 0xb5, 0x46, 0xdb,
	0x6d, 0xd4, 0x6b, 0xdd, 0xc6, 0x1a, 0x7e, 0x1b, 0x59, 0x42, 0x0b, 0xd3, 0x38, 0x99, 0x95, 0xb7,
	0xdb, 0x0b, 0xac, 0x45, 0x91, 0x6e, 0x07, 0x57, 0x23, 0x9f, 0x2a, 0xf0, 0xf1, 0x73, 0x76, 0x66,
	0xae, 0xe9, 0xcd, 0xa5, 0x0a, 0x3a, 0x20, 0x25, 0xe3, 0x21, 0x7e, 0x07, 0x79, 0x08, 0x2d, 0x16,
	0x80, 0x99, 0xf5, 0x9a, 0x1d, 0xe3, 0x26, 0xe7, 0xbb, 0xa3, 0xc8, 0x5c, 0x8c, 0xd6, 0x05, 0x1f,
	0xb6, 0xc2, 0x68, 0xa4, 0xf0, 0xe5, 0x89, 0xfc, 0x43, 0xe8, 0x6f, 0x74, 0xbb, 0xed, 0x34, 0x99,
	0x75, 0xdb, 0xcb, 0x3e, 0x30, 0xf3, 0xb2, 0x66, 0x6f, 0x7a, 0x5b, 0x40, 0x17, 0xa4, 0xea, 0x80,
	0x1a, 0x45, 0xb8, 0x41, 0x16, 0xd1, 0xd9, 0x14, 0x71, 0xc1, 0xe3, 0xc2, 0xef, 0x8c, 0xa2, 0x88,
	0x0b, 0x55, 0xf3, 0x74, 0x83, 0xc7, 0xeb, 0x64, 0x19, 0x3d, 0x6c, 0x25, 0xc8, 0x44, 0xb7, 0x06,
	0x8a, 0xb2, 0x40, 0xf6, 0xac, 0x54, 0x36, 0xed, 0xa5, 0xb8, 0xe0, 0x01, 0xdb, 0x83, 0x56, 0xa8,
	0x40, 0xd4, 0xa2, 0x68, 0x0b, 0xa4, 0xa4, 0x03, 0xc0, 0x2d, 0x3b, 0x90, 0x75, 0x16, 0xfa, 0xc6,
	0x9c, 0xc4, 0xcf, 0xdb, 0xb5, 0xd2, 0xe6, 0x52, 0xd5, 0x02, 0x10, 0x0a, 0xbf, 0xd3, 0x2e, 0xca,
	0x26, 0xa8, 0x4d, 0xe6, 0x41, 0x28, 0x41, 0xe2, 0xcd, 0xc9, 0x13, 0x93, 0x6f, 0x1c, 0xde, 0xda,
	0xa7, 0x62, 0x2a, 0x5f, 0xe2, 0x17, 0xec, 0xb5, 0x5a, 0x40, 0x96, 0xa6, 0x2b, 0x13, 0x5b, 0xed,
	0xfb, 0xeb, 0x02, 0xc0, 0x38, 0xc4, 0x6d, 0x7b, 0x75, 0x93, 0x58, 0xa6, 0xff, 0x22, 0x39, 0x8d,
	0xee, 0xb5, 0x1c, 0xb4, 0xda, 0x9b, 0x3c, 0xb9, 0x4f, 0x63, 0x97, 0x3c, 0x88, 0xee, 0x9f, 0x0a,
	0x65, 0xda, 0x1d, 0x72, 0x3f, 0x3a, 0x3d, 0x79, 0xd2, 0xed, 0xca, 0xef, 0xda, 0xc1, 0x35, 0x41,
	0x59, 0x0c, 0x7c, 0x75, 0x5f, 0xa5, 0x5b, 0x58, 0x66, 0xfe, 0x9a, 0x9d, 0x60, 0x5d, 0x28, 0x8d,
	0x21, 0x65, 0x01, 0xbe, 0x3e, 0xe1, 0x35, 0x15, 0x67, 0x5a, 0xef, 0x22, 0x0b, 0xa8, 0x62, 0x59,
	0x8e, 0xd1, 0xae, 0x99, 0xeb, 0xf8, 0xdd, 0xe4, 0x61, 0xb4, 0x54, 0x84, 0x66, 0x36, 0xde, 0x33,
	0x11, 0xb9, 0xbe, 0xa2, 0x34, 0x75, 0x75, 0xb6, 0xa9, 0x94, 0xf8, 0xbd, 0x13, 0x91, 0x4f, 0x60,
	0x99, 0xfe, 0x4b, 0x76, 0x88, 0x07, 0x4a, 0x10, 0xbf, 0x8f, 0x9c, 0x43, 0x0f, 0x16, 0xc2, 0x99,
	0x95, 0xf7, 0xdb, 0xa7, 0xa8, 0x09, 0xca, 0x34, 0x79, 0x7d, 0xc5, 0x94, 0xb8, 0x67, 0x9f, 0xa2,
	0x7d, 0x60, 0x66, 0xe1, 0x03, 0x76, 0xc9, 0xc5, 0x7d, 0x3b, 0x0a, 0xe0, 0xc6, 0x96, 0x1c, 0x60,
	0x6a, 0x77, 0x11, 0x1b, 0xc9, 0x74, 0xfb, 0x76, 0xa6, 0xae, 0x43, 0xbf, 0xd6, 0x6e, 0xb9, 0x30,
	0x60, 0x52, 0x81, 0x88, 0xcf, 0xc8, 0x36, 0xf5, 0x40, 0x62, 0xb0, 0xb3, 0x9d, 0xb0, 0x9e, 0xe7,
	0xfd, 0xf4, 0xa8, 0x6f, 0xdb, 0x47, 0x71, 0x3f, 0xba, 0xa1, 0x54, 0x94, 0x79, 0xdb, 0x21, 0x8f,
	0xa1, 0xf3, 0x45, 0xcc, 0x75, 0x2e, 0xf4, 0x8c, 0xc8, 0xc8, 0x8c, 0x9c, 0xb6, 0x96, 0x05, 0xc3,
	0x3a, 0xd5, 0x17, 0xcd, 0x26, 0x28, 0xfc, 0x23, 0x87, 0x3c, 0x68, 0xad, 0xcb, 0x82, 0x32, 0xe5,
	0x1f, 0x3b, 0x53, 0xb5, 0x3b, 0xa0, 0xf0, 0x4f, 0x1c, 0xb2, 0x90, 0x67, 0x3c, 0x83, 0xd6, 0x20,
	0x00, 0x05, 0xf8, 0xa7, 0x0e, 0x39, 0x9b, 0x57, 0x45, 0xae, 0x18, 0xd7, 0xf3, 0xcf, 0x1c, 0xf2,
	0x50, 0x5e, 0x16, 0x93, 0x60, 0xe6, 0xfa, 0xe7, 0x0e, 0x59, 0xcc, 0x47, 0xe0, 0x16, 0xd5, 0xb9,
	0xec, 0x80, 0x5a, 0x63, 0x02, 0x3c, 0xc5, 0xc5, 0x18, 0xff, 0xca, 0x21, 0xe7, 0x51, 0xb5, 0x98,
	0x90, 0x59, 0xfa, 0xf5, 0xa4, 0xbb, 0x94, 0x68, 0xb6, 0x89, 0x8f, 0x94, 0x9e, 0x82, 0xbf, 0x71,
	0xc8, 0x63, 0xf9, 0xe8, 0x99, 0x4e, 0xca, 0x2c, 0xfe, 0xd6, 0x21, 0x8f, 0xe4, 0x45, 0x99, 0x91,
	0xeb, 0x01, 0x83, 0x50, 0xe9, 0xba, 0x30, 0x46, 0x7f, 0xe7, 0x90, 0x55, 0xf4, 0xe8, 0x2d, 0x79,
	0x99, 0xdd, 0xdf, 0x3b, 0xe4, 0x94, 0x75, 0x1d, 0x00, 0x75, 0x25, 0xd2, 0x3d, 0x44, 0xe2, 0x3f,
	0x4c, 0x24, 0x23, 0x07, 0x32, 0xcd, 0x3f, 0xea, 0x2b, 0xc6, 0xc9, 0x83, 0x17, 0x89, 0x0b, 0xf8,
	0xcf, 0x25, 0x7b, 0xf5, 0xba, 0xf8, 0x47, 0xc2, 0xdb, 0xa1, 0x12, 0xba, 0x62, 0x24, 0x95, 0xce,
	0xf9, 0x48, 0xe2, 0xbf, 0x94, 0xec, 0xd5, 0x4f, 0x27, 0x65, 0xbe, 0xfe, 0x5a, 0x22, 0x67, 0xf2,
	0x46, 0x98, 0x0c, 0xcb, 0x74, 0x2a, 0xfe, 0xad, 0x44, 0xce, 0x59, 0x3d, 0xa3, 0x6e, 0x4e, 0xeb,
	0x35, 0xea, 0x25, 0x46, 0x92, 0x47, 0x00, 0xfc, 0xf7, 0x92, 0x5d, 0x3c, 0xf5, 0x1d, 0xf0, 0x76,
	0xd7, 0x05, 0x83, 0xd0, 0x97, 0x3b, 0x2c, 0xc2, 0xff, 0x28, 0x91, 0x87, 0xf3, 0xf3, 0xba, 0x0f,
	0xcd, 0xc2, 0xf8, 0x67, 0x89, 0x54, 0x27, 0x9a, 0x6e, 0x9b, 0x0a, 0x15, 0x82, 0x30, 0x2e, 0x37,
	0x59, 0xb8, 0x8b, 0xff, 0x55, 0x22, 0x2b, 0xe8, 0xdc, 0x4d, 0x39, 0x99, 0xbd, 0x7f, 0x97, 0xec,
	0x1c, 0xaf, 0xb5, 0x0d, 0x75, 0x8b, 0x79, 0x82, 0x77, 0x6f, 0x84, 0x12, 0xbf, 0x5c, 0xb6, 0x0b,
	0xee, 0x20, 0x21, 0xb3, 0xf4, 0xd1, 0xb2, 0x1d, 0xd9, 0xd4, 0xb7, 0x17, 0xfc, 0xb1, 0xb2, 0x9d,
	0xa8, 0xa2, 0xd7, 0x12, 0xfc, 0xf1, 0x32, 0x79, 0x20, 0xef, 0x8e, 0x07, 0x5e, 0x27, 0xf0, 0x27,
	0xcb, 0xe4, 0x69, 0xf4, 0xb8, 0xb5, 0xc0, 0xe2, 0xff, 0x4a, 0x69, 0x9f, 0xf9, 0x54, 0x99, 0x5c,
	0x40, 0x4f, 0x1c, 0x52, 0xc5, 0xac, 0xe8, 0xd3, 0x65, 0xbb, 0x90, 0x8b, 0xff, 0x45, 0xa4, 0x3e,
	0x3e, 0x53, 0x26, 0x4f, 0xa2, 0x95, 0xc3, 0xf0, 0x8d, 0x83, 0x57, 0xca, 0xe4, 0x12, 0x7a, 0x32,
	0x55, 0xb8, 0xd5, 0x75, 0x3d, 0x75, 0xf3, 0xd9, 0x32, 0x79, 0x06, 0x3d, 0x75, 0x78, 0x2d, 0xe3,
	0xec, 0xd5, 0xf2, 0xca, 0x9f, 0x1c, 0x34, 0xdb, 0xe8, 0x5c, 0xc9, 0xaf, 0xf0, 0xf1, 0xef, 0x5e,
	0x5d, 0x80, 0x1e, 0x7c, 0xf7, 0x4e, 0x08, 0x93, 0x0a, 0xc7, 0xf7, 0x91, 0x7b, 0x10, 0xce, 0x84,
	0x6b, 0x20, 0x95, 0xe0, 0x63, 0x7c, 0xca, 0xf4, 0x74, 0xa3, 0xaf, 0x1b, 0x59, 0x67, 0xd4, 0x97,
	0x9e, 0x60, 0x7d, 0xf0, 0x71, 0xc5, 0x5c, 0xe3, 0x2d, 0xf4, 0x6a, 0x28, 0x73, 0xfc, 0xb4, 0x99,
	0x5a, 0xb6, 0xa3, 0x74, 0xc0, 0xe0, 0x33, 0x66, 0x6a, 0x1d, 0x34, 0x1d, 0x25, 0x85, 0x04, 0xde,
	0x2e, 0x3e, 0x6b, 0xc6, 0x63, 0x01, 0xc9, 0x85, 0x6d, 0x01, 0x72, 0x07, 0x2f, 0xac, 0xfc, 0x72,
	0x06, 0xe1, 0x46, 0xb3, 0xae, 0x9b, 0x42, 0xd6, 0x7f, 0xcc, 0x39, 0x8e, 0x4f, 0x6a, 0x22, 0xbc,
	0x0e, 0x81, 0xc7, 0x87, 0x80, 0xbf, 0xba, 0x68, 0x63, 0x9d, 0xf8, 0xc2, 0x9f, 0x62, 0x5f, 0x5b,
	0x34, 0xbd, 0xc6, 0xd2, 0xdb, 0x80, 0x20, 0xe0, 0xf8, 0xeb, 0x13, 0x48, 0xa2, 0x95, 0x20, 0xdf,
	0x58, 0x34, 0x5d, 0xc8, 0xd2, 0xa9, 0xf3, 0x30, 0x84, 0xf8, 0x1a, 0x6a, 0xba, 0xd0, 0x37, 0x27,
	0x48, 0x89, 0xfa, 0x01, 0xd2, 0xb7, 0x16, 0xcd, 0x31, 0xdd, 0xef, 0xdd, 0x1c, 0x47, 0xfc, 0xed,
	0xc5, 0x83, 0xcb, 0x4a, 0x08, 0xd7, 0xf1, 0x77, 0x8a, 0x30, 0xf7, 0x02, 0x7e, 0xa3, 0x10, 0xbb,
	0x88, 0xbf, 0x5b, 0x88, 0x5d, 0xc2, 0xdf, 0x5b, 0x5c, 0xf9, 0xc4, 0x0c, 0x42, 0x8d, 0x66, 0xbd,
	0xcb, 0xe3, 0x3a, 0xcc, 0xba, 0xa3, 0xf9, 0x4e, 0xfa, 0x7e, 0xcd, 0xdb, 0xc5, 0x9f, 0x77, 0xb2,
	0xc6, 0xb0, 0x1f, 0xcb, 0x8a, 0xf3, 0x0b, 0xf9, 0x0c, 0x30, 0x1c, 0x3d, 0x25, 0xc0, 0xc7, 0xaf,
	0xe5, 0x03, 0x77, 0x02, 0x48, 0xfe, 0x48, 0x7e, 0xd1, 0xc9, 0x23, 0x9c, 0x68, 0xc9, 0xad, 0x36,
	0x7e, 0x3d, 0x1d, 0xc6, 0xf1, 0x95, 0x25, 0x3e, 0x3a, 0x39, 0xf8, 0x25, 0x27, 0x4f, 0xfa, 0x7e,
	0x30, 0x0b, 0xea, 0xcb, 0xf9, 0xc0, 0x9b, 0x08, 0x3c, 0xfe, 0xbb, 0x38, 0x8a, 0xea, 0x7c, 0x18,
	0xc5, 0x63, 0xff, 0x2b, 0xce, 0xca, 0xf7, 0x4b, 0xe8, 0x64, 0x63, 0xe2, 0x2d, 0x2c, 0x79, 0x11,
	0x4c, 0x2e, 0xc8, 0x07, 0x81, 0x5e, 0xfe, 0xbf, 0x39, 0xb9, 0xbf, 0x4f, 0xa1, 0x5c, 0xa6, 0xfe,
	0x00, 0xb0, 0x63, 0x2e, 0x93, 0x53, 0x08, 0xfa, 0xc4, 0xd7, 0xa9, 0xf0, 0xf1, 0x8c, 0xb9, 0x1a,
	0x4d, 0xe1, 0xb4, 0x05, 0xdf, 0x66, 0x01, 0x5c, 0xa6, 0xde, 0xee, 0x40, 0xf0, 0x51, 0xe8, 0xe3,
	0x52, 0xb1, 0xc1, 0xc6, 0x90, 0x2b, 0xe6, 0xf1, 0x10, 0x97, 0xcd, 0xf9, 0x9a, 0x16, 0x15, 0xe7,
	0x3a, 0x07, 0x6d, 0xea, 0xed, 0xe2, 0x23, 0xe6, 0x02, 0x38, 0x85, 0x56, 0xe7, 0xa1, 0x1c, 0x0d,
	0x69, 0x3f, 0x00, 0x3c, 0x5b, 0x9c, 0x05, 0xbd, 0x82, 0x26, 0xe7, 0xf8, 0x28, 0x79, 0x34, 0x1e,
	0x58, 0xc5, 0x0b, 0xd8, 0xe2, 0x3e, 0xdb, 0x66, 0x20, 0xf0, 0xb1, 0xe2, 0x84, 0x75, 0x3c, 0x08,
	0x01, 0xcf, 0x15, 0x07, 0xd5, 0xa1, 0xba, 0x86, 0xf5, 0x37, 0x46, 0x2b, 0xbf, 0x28, 0xa1, 0x53,
	0x93, 0xa4, 0xfc, 0x7d, 0x74, 0xca, 0xea, 0x33, 0xd0, 0xda, 0xba, 0xe4, 0xea, 0x5a, 0x40, 0xd3,
	0x3b, 0x73, 0x99, 0x0b, 0x1f, 0x04, 0x76, 0x4c, 0x4f, 0x2b, 0x60, 0x6e, 0xc2, 0x1e, 0x04, 0x78,
	0x66, 0x5a, 0x0e, 0x2c, 0xaf, 0x52, 0x8e, 0xcc, 0x94, 0xc4, 0x25, 0xf3, 0x60, 0x50, 0x40, 0xed,
	0x0a, 0xea, 0xeb, 0xcc, 0x77, 0xd9, 0x10, 0x70, 0x99, 0x3c, 0x8e, 0x96, 0x8b, 0xb9, 0x1d, 0xc5,
	0x05, 0xe8, 0xcd, 0xa4, 0x03, 0x68, 0xad, 0xe1, 0x23, 0xe4, 0xa9, 0x78, 0xb0, 0x16, 0xad, 0x69,
	0x42, 0x1c, 0x45, 0xad, 0x35, 0x3c, 0x4b, 0x9e, 0x44, 0x8f, 0x1d, 0x52, 0xa3, 0x3b, 0x8e, 0x00,
	0x1f, 0x25, 0x17, 0xe3, 0x99, 0x57, 0xa0, 0x60, 0xef, 0x37, 0x88, 0x46, 0xa8, 0x17, 0xe2, 0xe3,
	0x63, 0x37, 0xcf, 0x75, 0xe3, 0x46, 0xc4, 0xc4, 0x38, 0x5e, 0xef, 0xdc, 0xe5, 0x23, 0x1b, 0xce,
	0xcb, 0xce, 0x1d, 0xff, 0x09, 0x00, 0x00, 0xff, 0xff, 0xa3, 0x1a, 0x58, 0xe9, 0x1c, 0x1a, 0x00,
	0x00,
}
