// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_deviceauth.steamclient.proto

package unified

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package unified is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package unified to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CDeviceAuth_GetOwnAuthorizedDevices_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IncludeCanceled      *bool    `protobuf:"varint,2,opt,name=include_canceled" json:"include_canceled,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) Reset() {
	*m = CDeviceAuth_GetOwnAuthorizedDevices_Request{}
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Request) ProtoMessage() {}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{0}
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Request.Merge(m, src)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Request.Size(m)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Request proto.InternalMessageInfo

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Request) GetIncludeCanceled() bool {
	if m != nil && m.IncludeCanceled != nil {
		return *m.IncludeCanceled
	}
	return false
}

type CDeviceAuth_GetOwnAuthorizedDevices_Response struct {
	Devices              []*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) Reset() {
	*m = CDeviceAuth_GetOwnAuthorizedDevices_Response{}
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response) ProtoMessage() {}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{1}
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response.Merge(m, src)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response.Size(m)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response proto.InternalMessageInfo

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response) GetDevices() []*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type CDeviceAuth_GetOwnAuthorizedDevices_Response_Device struct {
	AuthDeviceToken      *uint64  `protobuf:"fixed64,1,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	DeviceName           *string  `protobuf:"bytes,2,opt,name=device_name" json:"device_name,omitempty"`
	IsPending            *bool    `protobuf:"varint,3,opt,name=is_pending" json:"is_pending,omitempty"`
	IsCanceled           *bool    `protobuf:"varint,4,opt,name=is_canceled" json:"is_canceled,omitempty"`
	LastTimeUsed         *uint32  `protobuf:"varint,5,opt,name=last_time_used" json:"last_time_used,omitempty"`
	LastBorrowerId       *uint64  `protobuf:"fixed64,6,opt,name=last_borrower_id" json:"last_borrower_id,omitempty"`
	LastAppPlayed        *uint32  `protobuf:"varint,7,opt,name=last_app_played" json:"last_app_played,omitempty"`
	IsLimited            *bool    `protobuf:"varint,8,opt,name=is_limited" json:"is_limited,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) Reset() {
	*m = CDeviceAuth_GetOwnAuthorizedDevices_Response_Device{}
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) ProtoMessage() {}
func (*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{1, 0}
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response_Device.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response_Device.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response_Device.Merge(m, src)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response_Device.Size(m)
}
func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response_Device.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetOwnAuthorizedDevices_Response_Device proto.InternalMessageInfo

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetIsPending() bool {
	if m != nil && m.IsPending != nil {
		return *m.IsPending
	}
	return false
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetIsCanceled() bool {
	if m != nil && m.IsCanceled != nil {
		return *m.IsCanceled
	}
	return false
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetLastTimeUsed() uint32 {
	if m != nil && m.LastTimeUsed != nil {
		return *m.LastTimeUsed
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetLastBorrowerId() uint64 {
	if m != nil && m.LastBorrowerId != nil {
		return *m.LastBorrowerId
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetLastAppPlayed() uint32 {
	if m != nil && m.LastAppPlayed != nil {
		return *m.LastAppPlayed
	}
	return 0
}

func (m *CDeviceAuth_GetOwnAuthorizedDevices_Response_Device) GetIsLimited() bool {
	if m != nil && m.IsLimited != nil {
		return *m.IsLimited
	}
	return false
}

type CDeviceAuth_AcceptAuthorizationRequest_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthDeviceToken      *uint64  `protobuf:"fixed64,2,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	AuthCode             *uint64  `protobuf:"fixed64,3,opt,name=auth_code" json:"auth_code,omitempty"`
	FromSteamid          *uint64  `protobuf:"fixed64,4,opt,name=from_steamid" json:"from_steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) Reset() {
	*m = CDeviceAuth_AcceptAuthorizationRequest_Request{}
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AcceptAuthorizationRequest_Request) ProtoMessage() {}
func (*CDeviceAuth_AcceptAuthorizationRequest_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{2}
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Request.Merge(m, src)
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Request.Size(m)
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Request proto.InternalMessageInfo

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetAuthCode() uint64 {
	if m != nil && m.AuthCode != nil {
		return *m.AuthCode
	}
	return 0
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Request) GetFromSteamid() uint64 {
	if m != nil && m.FromSteamid != nil {
		return *m.FromSteamid
	}
	return 0
}

type CDeviceAuth_AcceptAuthorizationRequest_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) Reset() {
	*m = CDeviceAuth_AcceptAuthorizationRequest_Response{}
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AcceptAuthorizationRequest_Response) ProtoMessage() {}
func (*CDeviceAuth_AcceptAuthorizationRequest_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{3}
}

func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Response.Merge(m, src)
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Response.Size(m)
}
func (m *CDeviceAuth_AcceptAuthorizationRequest_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_AcceptAuthorizationRequest_Response proto.InternalMessageInfo

type CDeviceAuth_AuthorizeRemoteDevice_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthDeviceToken      *uint64  `protobuf:"fixed64,2,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) Reset() {
	*m = CDeviceAuth_AuthorizeRemoteDevice_Request{}
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) String() string { return proto.CompactTextString(m) }
func (*CDeviceAuth_AuthorizeRemoteDevice_Request) ProtoMessage()    {}
func (*CDeviceAuth_AuthorizeRemoteDevice_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{4}
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Request.Merge(m, src)
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Request.Size(m)
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Request proto.InternalMessageInfo

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Request) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

type CDeviceAuth_AuthorizeRemoteDevice_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) Reset() {
	*m = CDeviceAuth_AuthorizeRemoteDevice_Response{}
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AuthorizeRemoteDevice_Response) ProtoMessage() {}
func (*CDeviceAuth_AuthorizeRemoteDevice_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{5}
}

func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Response.Merge(m, src)
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Response.Size(m)
}
func (m *CDeviceAuth_AuthorizeRemoteDevice_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_AuthorizeRemoteDevice_Response proto.InternalMessageInfo

type CDeviceAuth_DeauthorizeRemoteDevice_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	AuthDeviceToken      *uint64  `protobuf:"fixed64,2,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) Reset() {
	*m = CDeviceAuth_DeauthorizeRemoteDevice_Request{}
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Request) ProtoMessage() {}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{6}
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Request.Merge(m, src)
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Request.Size(m)
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Request proto.InternalMessageInfo

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Request) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

type CDeviceAuth_DeauthorizeRemoteDevice_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) Reset() {
	*m = CDeviceAuth_DeauthorizeRemoteDevice_Response{}
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Response) ProtoMessage() {}
func (*CDeviceAuth_DeauthorizeRemoteDevice_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{7}
}

func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Response.Merge(m, src)
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Response.Size(m)
}
func (m *CDeviceAuth_DeauthorizeRemoteDevice_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_DeauthorizeRemoteDevice_Response proto.InternalMessageInfo

type CDeviceAuth_GetUsedAuthorizedDevices_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) Reset() {
	*m = CDeviceAuth_GetUsedAuthorizedDevices_Request{}
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Request) ProtoMessage() {}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{8}
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Request.Merge(m, src)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Request.Size(m)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Request proto.InternalMessageInfo

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CDeviceAuth_GetUsedAuthorizedDevices_Response struct {
	Devices              []*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device `protobuf:"bytes,1,rep,name=devices" json:"devices,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                `json:"-"`
	XXX_unrecognized     []byte                                                  `json:"-"`
	XXX_sizecache        int32                                                   `json:"-"`
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) Reset() {
	*m = CDeviceAuth_GetUsedAuthorizedDevices_Response{}
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response) ProtoMessage() {}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{9}
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response.Merge(m, src)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response.Size(m)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response proto.InternalMessageInfo

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response) GetDevices() []*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device {
	if m != nil {
		return m.Devices
	}
	return nil
}

type CDeviceAuth_GetUsedAuthorizedDevices_Response_Device struct {
	AuthDeviceToken      *uint64  `protobuf:"fixed64,1,opt,name=auth_device_token" json:"auth_device_token,omitempty"`
	DeviceName           *string  `protobuf:"bytes,2,opt,name=device_name" json:"device_name,omitempty"`
	OwnerSteamid         *uint64  `protobuf:"fixed64,3,opt,name=owner_steamid" json:"owner_steamid,omitempty"`
	LastTimeUsed         *uint32  `protobuf:"varint,4,opt,name=last_time_used" json:"last_time_used,omitempty"`
	LastAppPlayed        *uint32  `protobuf:"varint,5,opt,name=last_app_played" json:"last_app_played,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) Reset() {
	*m = CDeviceAuth_GetUsedAuthorizedDevices_Response_Device{}
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) ProtoMessage() {}
func (*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{9, 0}
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response_Device.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response_Device.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response_Device.Merge(m, src)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response_Device.Size(m)
}
func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response_Device.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetUsedAuthorizedDevices_Response_Device proto.InternalMessageInfo

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetAuthDeviceToken() uint64 {
	if m != nil && m.AuthDeviceToken != nil {
		return *m.AuthDeviceToken
	}
	return 0
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetDeviceName() string {
	if m != nil && m.DeviceName != nil {
		return *m.DeviceName
	}
	return ""
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetOwnerSteamid() uint64 {
	if m != nil && m.OwnerSteamid != nil {
		return *m.OwnerSteamid
	}
	return 0
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetLastTimeUsed() uint32 {
	if m != nil && m.LastTimeUsed != nil {
		return *m.LastTimeUsed
	}
	return 0
}

func (m *CDeviceAuth_GetUsedAuthorizedDevices_Response_Device) GetLastAppPlayed() uint32 {
	if m != nil && m.LastAppPlayed != nil {
		return *m.LastAppPlayed
	}
	return 0
}

type CDeviceAuth_GetAuthorizedBorrowers_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IncludeCanceled      *bool    `protobuf:"varint,2,opt,name=include_canceled" json:"include_canceled,omitempty"`
	IncludePending       *bool    `protobuf:"varint,3,opt,name=include_pending" json:"include_pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) Reset() {
	*m = CDeviceAuth_GetAuthorizedBorrowers_Request{}
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedBorrowers_Request) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedBorrowers_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{10}
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Request.Merge(m, src)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Request.Size(m)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Request proto.InternalMessageInfo

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) GetIncludeCanceled() bool {
	if m != nil && m.IncludeCanceled != nil {
		return *m.IncludeCanceled
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Request) GetIncludePending() bool {
	if m != nil && m.IncludePending != nil {
		return *m.IncludePending
	}
	return false
}

type CDeviceAuth_GetAuthorizedBorrowers_Response struct {
	Borrowers            []*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower `protobuf:"bytes,1,rep,name=borrowers" json:"borrowers,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                `json:"-"`
	XXX_unrecognized     []byte                                                  `json:"-"`
	XXX_sizecache        int32                                                   `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) Reset() {
	*m = CDeviceAuth_GetAuthorizedBorrowers_Response{}
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{11}
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response.Merge(m, src)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response.Size(m)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response proto.InternalMessageInfo

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response) GetBorrowers() []*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower {
	if m != nil {
		return m.Borrowers
	}
	return nil
}

type CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IsPending            *bool    `protobuf:"varint,2,opt,name=is_pending" json:"is_pending,omitempty"`
	IsCanceled           *bool    `protobuf:"varint,3,opt,name=is_canceled" json:"is_canceled,omitempty"`
	TimeCreated          *uint32  `protobuf:"varint,4,opt,name=time_created" json:"time_created,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) Reset() {
	*m = CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower{}
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{11, 0}
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower.Merge(m, src)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower.Size(m)
}
func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower proto.InternalMessageInfo

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetIsPending() bool {
	if m != nil && m.IsPending != nil {
		return *m.IsPending
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetIsCanceled() bool {
	if m != nil && m.IsCanceled != nil {
		return *m.IsCanceled
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower) GetTimeCreated() uint32 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

type CDeviceAuth_AddAuthorizedBorrowers_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	SteamidBorrower      []uint64 `protobuf:"fixed64,2,rep,name=steamid_borrower" json:"steamid_borrower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) Reset() {
	*m = CDeviceAuth_AddAuthorizedBorrowers_Request{}
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AddAuthorizedBorrowers_Request) ProtoMessage() {}
func (*CDeviceAuth_AddAuthorizedBorrowers_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{12}
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Request.Merge(m, src)
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Request.Size(m)
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Request proto.InternalMessageInfo

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Request) GetSteamidBorrower() []uint64 {
	if m != nil {
		return m.SteamidBorrower
	}
	return nil
}

type CDeviceAuth_AddAuthorizedBorrowers_Response struct {
	SecondsToWait        *int32   `protobuf:"varint,1,opt,name=seconds_to_wait" json:"seconds_to_wait,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) Reset() {
	*m = CDeviceAuth_AddAuthorizedBorrowers_Response{}
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_AddAuthorizedBorrowers_Response) ProtoMessage() {}
func (*CDeviceAuth_AddAuthorizedBorrowers_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{13}
}

func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Response.Merge(m, src)
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Response.Size(m)
}
func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_AddAuthorizedBorrowers_Response proto.InternalMessageInfo

func (m *CDeviceAuth_AddAuthorizedBorrowers_Response) GetSecondsToWait() int32 {
	if m != nil && m.SecondsToWait != nil {
		return *m.SecondsToWait
	}
	return 0
}

type CDeviceAuth_RemoveAuthorizedBorrowers_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	SteamidBorrower      []uint64 `protobuf:"fixed64,2,rep,name=steamid_borrower" json:"steamid_borrower,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) Reset() {
	*m = CDeviceAuth_RemoveAuthorizedBorrowers_Request{}
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Request) ProtoMessage() {}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{14}
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Request.Merge(m, src)
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Request.Size(m)
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Request proto.InternalMessageInfo

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Request) GetSteamidBorrower() []uint64 {
	if m != nil {
		return m.SteamidBorrower
	}
	return nil
}

type CDeviceAuth_RemoveAuthorizedBorrowers_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) Reset() {
	*m = CDeviceAuth_RemoveAuthorizedBorrowers_Response{}
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Response) ProtoMessage() {}
func (*CDeviceAuth_RemoveAuthorizedBorrowers_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{15}
}

func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Response.Merge(m, src)
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Response.Size(m)
}
func (m *CDeviceAuth_RemoveAuthorizedBorrowers_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_RemoveAuthorizedBorrowers_Response proto.InternalMessageInfo

type CDeviceAuth_GetAuthorizedAsBorrower_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	IncludeCanceled      *bool    `protobuf:"varint,2,opt,name=include_canceled" json:"include_canceled,omitempty"`
	IncludePending       *bool    `protobuf:"varint,3,opt,name=include_pending" json:"include_pending,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) Reset() {
	*m = CDeviceAuth_GetAuthorizedAsBorrower_Request{}
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedAsBorrower_Request) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedAsBorrower_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{16}
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Request.Merge(m, src)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Request.Size(m)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Request proto.InternalMessageInfo

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) GetIncludeCanceled() bool {
	if m != nil && m.IncludeCanceled != nil {
		return *m.IncludeCanceled
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Request) GetIncludePending() bool {
	if m != nil && m.IncludePending != nil {
		return *m.IncludePending
	}
	return false
}

type CDeviceAuth_GetAuthorizedAsBorrower_Response struct {
	Lenders              []*CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender `protobuf:"bytes,1,rep,name=lenders" json:"lenders,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                               `json:"-"`
	XXX_unrecognized     []byte                                                 `json:"-"`
	XXX_sizecache        int32                                                  `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response) Reset() {
	*m = CDeviceAuth_GetAuthorizedAsBorrower_Response{}
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedAsBorrower_Response) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedAsBorrower_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{17}
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response.Merge(m, src)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response.Size(m)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response proto.InternalMessageInfo

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response) GetLenders() []*CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender {
	if m != nil {
		return m.Lenders
	}
	return nil
}

type CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	TimeCreated          *uint32  `protobuf:"varint,2,opt,name=time_created" json:"time_created,omitempty"`
	IsPending            *bool    `protobuf:"varint,3,opt,name=is_pending" json:"is_pending,omitempty"`
	IsCanceled           *bool    `protobuf:"varint,4,opt,name=is_canceled" json:"is_canceled,omitempty"`
	IsUsed               *bool    `protobuf:"varint,5,opt,name=is_used" json:"is_used,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) Reset() {
	*m = CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender{}
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) ProtoMessage() {}
func (*CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{17, 0}
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender.Merge(m, src)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender.Size(m)
}
func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender proto.InternalMessageInfo

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) GetTimeCreated() uint32 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) GetIsPending() bool {
	if m != nil && m.IsPending != nil {
		return *m.IsPending
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) GetIsCanceled() bool {
	if m != nil && m.IsCanceled != nil {
		return *m.IsCanceled
	}
	return false
}

func (m *CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender) GetIsUsed() bool {
	if m != nil && m.IsUsed != nil {
		return *m.IsUsed
	}
	return false
}

type CDeviceAuth_GetExcludedGamesInLibrary_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Request) Reset() {
	*m = CDeviceAuth_GetExcludedGamesInLibrary_Request{}
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetExcludedGamesInLibrary_Request) ProtoMessage() {}
func (*CDeviceAuth_GetExcludedGamesInLibrary_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{18}
}

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Request.Merge(m, src)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Request.Size(m)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Request proto.InternalMessageInfo

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CDeviceAuth_GetExcludedGamesInLibrary_Response struct {
	ExcludedGames        []*CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame `protobuf:"bytes,1,rep,name=excluded_games" json:"excluded_games,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                       `json:"-"`
	XXX_unrecognized     []byte                                                         `json:"-"`
	XXX_sizecache        int32                                                          `json:"-"`
}

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response) Reset() {
	*m = CDeviceAuth_GetExcludedGamesInLibrary_Response{}
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetExcludedGamesInLibrary_Response) ProtoMessage() {}
func (*CDeviceAuth_GetExcludedGamesInLibrary_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{19}
}

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response.Merge(m, src)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response.Size(m)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response proto.InternalMessageInfo

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response) GetExcludedGames() []*CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame {
	if m != nil {
		return m.ExcludedGames
	}
	return nil
}

type CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame struct {
	Appid                *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	GameName             *string  `protobuf:"bytes,2,opt,name=game_name" json:"game_name,omitempty"`
	VacBanned            *bool    `protobuf:"varint,3,opt,name=vac_banned" json:"vac_banned,omitempty"`
	PackageExcluded      *bool    `protobuf:"varint,4,opt,name=package_excluded" json:"package_excluded,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) Reset() {
	*m = CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame{}
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) ProtoMessage() {}
func (*CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{19, 0}
}

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame.Merge(m, src)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame.Size(m)
}
func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame proto.InternalMessageInfo

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) GetGameName() string {
	if m != nil && m.GameName != nil {
		return *m.GameName
	}
	return ""
}

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) GetVacBanned() bool {
	if m != nil && m.VacBanned != nil {
		return *m.VacBanned
	}
	return false
}

func (m *CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame) GetPackageExcluded() bool {
	if m != nil && m.PackageExcluded != nil {
		return *m.PackageExcluded
	}
	return false
}

type CDeviceAuth_GetBorrowerPlayHistory_Request struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Request) Reset() {
	*m = CDeviceAuth_GetBorrowerPlayHistory_Request{}
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetBorrowerPlayHistory_Request) ProtoMessage() {}
func (*CDeviceAuth_GetBorrowerPlayHistory_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{20}
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Request.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Request.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Request.Merge(m, src)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Request) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Request.Size(m)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Request proto.InternalMessageInfo

func (m *CDeviceAuth_GetBorrowerPlayHistory_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CDeviceAuth_GetBorrowerPlayHistory_Response struct {
	LenderHistory        []*CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory `protobuf:"bytes,1,rep,name=lender_history" json:"lender_history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                     `json:"-"`
	XXX_unrecognized     []byte                                                       `json:"-"`
	XXX_sizecache        int32                                                        `json:"-"`
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response) Reset() {
	*m = CDeviceAuth_GetBorrowerPlayHistory_Response{}
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetBorrowerPlayHistory_Response) ProtoMessage() {}
func (*CDeviceAuth_GetBorrowerPlayHistory_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{21}
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response.Merge(m, src)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response.Size(m)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response proto.InternalMessageInfo

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response) GetLenderHistory() []*CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory {
	if m != nil {
		return m.LenderHistory
	}
	return nil
}

type CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory struct {
	Appid                *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	TimeLast             *uint32  `protobuf:"varint,2,opt,name=time_last" json:"time_last,omitempty"`
	TimeTotal            *uint32  `protobuf:"varint,3,opt,name=time_total" json:"time_total,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) Reset() {
	*m = CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory{}
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) ProtoMessage() {}
func (*CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{21, 0}
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory.Merge(m, src)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory.Size(m)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory proto.InternalMessageInfo

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) GetTimeLast() uint32 {
	if m != nil && m.TimeLast != nil {
		return *m.TimeLast
	}
	return 0
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory) GetTimeTotal() uint32 {
	if m != nil && m.TimeTotal != nil {
		return *m.TimeTotal
	}
	return 0
}

type CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory struct {
	Steamid              *uint64                                                    `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	GameHistory          []*CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory `protobuf:"bytes,2,rep,name=game_history" json:"game_history,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                   `json:"-"`
	XXX_unrecognized     []byte                                                     `json:"-"`
	XXX_sizecache        int32                                                      `json:"-"`
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) Reset() {
	*m = CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory{}
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) String() string {
	return proto.CompactTextString(m)
}
func (*CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) ProtoMessage() {}
func (*CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) Descriptor() ([]byte, []int) {
	return fileDescriptor_ae200bdec1a460f6, []int{21, 1}
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory.Unmarshal(m, b)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory.Marshal(b, m, deterministic)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory.Merge(m, src)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) XXX_Size() int {
	return xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory.Size(m)
}
func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) XXX_DiscardUnknown() {
	xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory.DiscardUnknown(m)
}

var xxx_messageInfo_CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory proto.InternalMessageInfo

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory) GetGameHistory() []*CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory {
	if m != nil {
		return m.GameHistory
	}
	return nil
}

func init() {
	proto.RegisterType((*CDeviceAuth_GetOwnAuthorizedDevices_Request)(nil), "CDeviceAuth_GetOwnAuthorizedDevices_Request")
	proto.RegisterType((*CDeviceAuth_GetOwnAuthorizedDevices_Response)(nil), "CDeviceAuth_GetOwnAuthorizedDevices_Response")
	proto.RegisterType((*CDeviceAuth_GetOwnAuthorizedDevices_Response_Device)(nil), "CDeviceAuth_GetOwnAuthorizedDevices_Response.Device")
	proto.RegisterType((*CDeviceAuth_AcceptAuthorizationRequest_Request)(nil), "CDeviceAuth_AcceptAuthorizationRequest_Request")
	proto.RegisterType((*CDeviceAuth_AcceptAuthorizationRequest_Response)(nil), "CDeviceAuth_AcceptAuthorizationRequest_Response")
	proto.RegisterType((*CDeviceAuth_AuthorizeRemoteDevice_Request)(nil), "CDeviceAuth_AuthorizeRemoteDevice_Request")
	proto.RegisterType((*CDeviceAuth_AuthorizeRemoteDevice_Response)(nil), "CDeviceAuth_AuthorizeRemoteDevice_Response")
	proto.RegisterType((*CDeviceAuth_DeauthorizeRemoteDevice_Request)(nil), "CDeviceAuth_DeauthorizeRemoteDevice_Request")
	proto.RegisterType((*CDeviceAuth_DeauthorizeRemoteDevice_Response)(nil), "CDeviceAuth_DeauthorizeRemoteDevice_Response")
	proto.RegisterType((*CDeviceAuth_GetUsedAuthorizedDevices_Request)(nil), "CDeviceAuth_GetUsedAuthorizedDevices_Request")
	proto.RegisterType((*CDeviceAuth_GetUsedAuthorizedDevices_Response)(nil), "CDeviceAuth_GetUsedAuthorizedDevices_Response")
	proto.RegisterType((*CDeviceAuth_GetUsedAuthorizedDevices_Response_Device)(nil), "CDeviceAuth_GetUsedAuthorizedDevices_Response.Device")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedBorrowers_Request)(nil), "CDeviceAuth_GetAuthorizedBorrowers_Request")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedBorrowers_Response)(nil), "CDeviceAuth_GetAuthorizedBorrowers_Response")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedBorrowers_Response_Borrower)(nil), "CDeviceAuth_GetAuthorizedBorrowers_Response.Borrower")
	proto.RegisterType((*CDeviceAuth_AddAuthorizedBorrowers_Request)(nil), "CDeviceAuth_AddAuthorizedBorrowers_Request")
	proto.RegisterType((*CDeviceAuth_AddAuthorizedBorrowers_Response)(nil), "CDeviceAuth_AddAuthorizedBorrowers_Response")
	proto.RegisterType((*CDeviceAuth_RemoveAuthorizedBorrowers_Request)(nil), "CDeviceAuth_RemoveAuthorizedBorrowers_Request")
	proto.RegisterType((*CDeviceAuth_RemoveAuthorizedBorrowers_Response)(nil), "CDeviceAuth_RemoveAuthorizedBorrowers_Response")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedAsBorrower_Request)(nil), "CDeviceAuth_GetAuthorizedAsBorrower_Request")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedAsBorrower_Response)(nil), "CDeviceAuth_GetAuthorizedAsBorrower_Response")
	proto.RegisterType((*CDeviceAuth_GetAuthorizedAsBorrower_Response_Lender)(nil), "CDeviceAuth_GetAuthorizedAsBorrower_Response.Lender")
	proto.RegisterType((*CDeviceAuth_GetExcludedGamesInLibrary_Request)(nil), "CDeviceAuth_GetExcludedGamesInLibrary_Request")
	proto.RegisterType((*CDeviceAuth_GetExcludedGamesInLibrary_Response)(nil), "CDeviceAuth_GetExcludedGamesInLibrary_Response")
	proto.RegisterType((*CDeviceAuth_GetExcludedGamesInLibrary_Response_ExcludedGame)(nil), "CDeviceAuth_GetExcludedGamesInLibrary_Response.ExcludedGame")
	proto.RegisterType((*CDeviceAuth_GetBorrowerPlayHistory_Request)(nil), "CDeviceAuth_GetBorrowerPlayHistory_Request")
	proto.RegisterType((*CDeviceAuth_GetBorrowerPlayHistory_Response)(nil), "CDeviceAuth_GetBorrowerPlayHistory_Response")
	proto.RegisterType((*CDeviceAuth_GetBorrowerPlayHistory_Response_GameHistory)(nil), "CDeviceAuth_GetBorrowerPlayHistory_Response.GameHistory")
	proto.RegisterType((*CDeviceAuth_GetBorrowerPlayHistory_Response_LenderHistory)(nil), "CDeviceAuth_GetBorrowerPlayHistory_Response.LenderHistory")
}

func init() {
	proto.RegisterFile("steammessages_deviceauth.steamclient.proto", fileDescriptor_ae200bdec1a460f6)
}

var fileDescriptor_ae200bdec1a460f6 = []byte{
	// 1304 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xac, 0x57, 0xdd, 0x6e, 0xdc, 0x44,
	0x14, 0x96, 0x37, 0xed, 0x26, 0x9d, 0x66, 0x9b, 0x76, 0x68, 0x9b, 0xa9, 0x2f, 0x60, 0x30, 0x20,
	0x85, 0x76, 0xe3, 0xa6, 0x55, 0x10, 0xa5, 0x34, 0xd0, 0xf4, 0x2f, 0x45, 0xaa, 0x00, 0x05, 0x50,
	0xa1, 0x17, 0x58, 0x13, 0x7b, 0xb2, 0x3b, 0xca, 0xee, 0xd8, 0xf5, 0xcc, 0x26, 0x84, 0xab, 0xca,
	0x12, 0x2f, 0x51, 0xde, 0x80, 0x1b, 0x10, 0x92, 0xa5, 0x22, 0xb8, 0x40, 0xbc, 0x02, 0x2f, 0xc0,
	0x15, 0x0f, 0xc1, 0x15, 0xf2, 0x78, 0xbc, 0xbb, 0x5e, 0xdb, 0x9b, 0x75, 0x94, 0x3b, 0xef, 0xfc,
	0x9c, 0xf9, 0xce, 0x37, 0xdf, 0x39, 0xf3, 0x2d, 0xb8, 0x2a, 0x24, 0x25, 0xfd, 0x3e, 0x15, 0x82,
	0x74, 0xa8, 0x70, 0x3c, 0xba, 0xcf, 0x5c, 0x4a, 0x06, 0xb2, 0x6b, 0xab, 0x09, 0xb7, 0xc7, 0x28,
	0x97, 0x76, 0x10, 0xfa, 0xd2, 0x37, 0xdb, 0xf9, 0xb5, 0x03, 0xce, 0x76, 0x19, 0xf5, 0x9c, 0x1d,
	0x22, 0x68, 0x71, 0xb5, 0xf5, 0x35, 0xb8, 0x76, 0xff, 0x81, 0x0a, 0xb7, 0x39, 0x90, 0x5d, 0x67,
	0x8b, 0xca, 0xcf, 0x0e, 0x78, 0xf2, 0xe9, 0x87, 0xec, 0x7b, 0xea, 0xa5, 0x53, 0xc2, 0xd9, 0xa6,
	0xcf, 0x07, 0x54, 0x48, 0xb8, 0x04, 0xe6, 0x55, 0x0c, 0xe6, 0x21, 0x03, 0x1b, 0x2b, 0x4d, 0x88,
	0xc0, 0x79, 0xc6, 0xdd, 0xde, 0xc0, 0xa3, 0x8e, 0x4b, 0xb8, 0x4b, 0x7b, 0xd4, 0x43, 0x0d, 0x6c,
	0xac, 0x2c, 0x58, 0xaf, 0x1a, 0xa0, 0x3d, 0x5b, 0x68, 0x11, 0xf8, 0x5c, 0x50, 0xf8, 0x10, 0xcc,
	0xa7, 0x89, 0x09, 0x64, 0xe0, 0xb9, 0x95, 0xb3, 0x37, 0xd7, 0xed, 0x3a, 0xfb, 0xed, 0x74, 0xc0,
	0xfc, 0xd3, 0x00, 0xcd, 0xf4, 0x13, 0x5e, 0x01, 0x17, 0x12, 0x92, 0x34, 0x5f, 0x8e, 0xf4, 0xf7,
	0x28, 0xd7, 0xb8, 0x5f, 0x03, 0x67, 0xf5, 0x28, 0x27, 0x7d, 0xaa, 0x20, 0x9f, 0x81, 0x10, 0x00,
	0x26, 0x9c, 0x80, 0x72, 0x8f, 0xf1, 0x0e, 0x9a, 0x4b, 0xd2, 0x48, 0x16, 0x32, 0x31, 0xca, 0xed,
	0x94, 0x1a, 0xbc, 0x0c, 0xce, 0xf5, 0x88, 0x90, 0x8e, 0x64, 0x7d, 0xea, 0x0c, 0x04, 0xf5, 0xd0,
	0x69, 0x6c, 0xac, 0xb4, 0x12, 0x36, 0xd4, 0xf8, 0x8e, 0x1f, 0x86, 0xfe, 0x01, 0x0d, 0x1d, 0xe6,
	0xa1, 0xa6, 0x3a, 0x6f, 0x19, 0x2c, 0xa9, 0x19, 0x12, 0x04, 0x4e, 0xd0, 0x23, 0x87, 0xd4, 0x43,
	0xf3, 0x6a, 0x4b, 0x7a, 0x66, 0x8f, 0xf5, 0x99, 0xa4, 0x1e, 0x5a, 0x50, 0xd4, 0xfd, 0x60, 0x80,
	0x5c, 0xea, 0x9b, 0xae, 0x4b, 0x03, 0x99, 0xa5, 0x4e, 0x24, 0xf3, 0xb9, 0xbe, 0x90, 0xea, 0x8b,
	0x29, 0xcd, 0xbd, 0xa1, 0xa6, 0x2e, 0x80, 0x33, 0x6a, 0xca, 0xf5, 0x3d, 0xaa, 0xb2, 0x6c, 0xc2,
	0x8b, 0x60, 0x71, 0x37, 0xf4, 0xfb, 0x4e, 0x16, 0x23, 0x49, 0xb3, 0x69, 0xdd, 0x00, 0xd7, 0x67,
	0x86, 0x91, 0x5e, 0x82, 0xf5, 0x14, 0xbc, 0x9b, 0xdb, 0x92, 0x5d, 0xd7, 0x36, 0xed, 0xfb, 0x92,
	0xa6, 0x33, 0xc7, 0x01, 0x6d, 0xb5, 0xc1, 0xd5, 0x59, 0x02, 0x6b, 0x18, 0xdf, 0xe4, 0x65, 0xfd,
	0x40, 0x15, 0xcb, 0xc9, 0x00, 0xb1, 0xf3, 0xb2, 0xae, 0x0e, 0xad, 0xa1, 0x7c, 0x5c, 0x28, 0x83,
	0xaf, 0x04, 0xf5, 0x66, 0x2f, 0x31, 0xeb, 0x3f, 0x03, 0xac, 0xce, 0x18, 0x41, 0x57, 0xd2, 0xa3,
	0xc9, 0x4a, 0x7a, 0xcf, 0xae, 0x15, 0x20, 0x2b, 0xa5, 0x17, 0xc7, 0x2f, 0xa5, 0x4b, 0xa0, 0xe5,
	0x1f, 0x70, 0x1a, 0x0e, 0x15, 0x95, 0xea, 0xac, 0x58, 0x38, 0xa7, 0x54, 0x15, 0x94, 0x94, 0x87,
	0xaa, 0x28, 0x2b, 0xc8, 0x5f, 0xfb, 0x16, 0x95, 0x23, 0xd8, 0xf7, 0x74, 0x95, 0x1d, 0xa7, 0x3d,
	0x25, 0x27, 0x66, 0x33, 0xb9, 0x82, 0xb7, 0xfe, 0x36, 0x0a, 0x2d, 0xb1, 0xfc, 0x48, 0x4d, 0xf6,
	0x63, 0x70, 0x26, 0x2b, 0xf7, 0x4a, 0xba, 0xa7, 0x05, 0xb0, 0xb3, 0x21, 0xf3, 0x19, 0x58, 0xc8,
	0xbe, 0x8b, 0x99, 0xe4, 0x7b, 0x53, 0xa3, 0xac, 0x37, 0xa5, 0x0d, 0xeb, 0x22, 0x58, 0x54, 0xec,
	0xba, 0x21, 0x25, 0x32, 0x23, 0xd8, 0x7a, 0x3a, 0x51, 0x3e, 0x9e, 0x57, 0x97, 0x47, 0x3d, 0x30,
	0xec, 0x6d, 0xa8, 0x81, 0xe7, 0x56, 0x9a, 0xd6, 0xa3, 0x3c, 0x5b, 0x95, 0x81, 0x35, 0x5b, 0xcb,
	0x60, 0x49, 0x50, 0xd7, 0xe7, 0x9e, 0x70, 0xa4, 0xef, 0x1c, 0x10, 0x26, 0xd5, 0x09, 0xa7, 0xad,
	0x67, 0x79, 0x91, 0x27, 0xb5, 0xb4, 0x4f, 0x4f, 0x08, 0xe3, 0x5a, 0xbe, 0x9d, 0x4e, 0x8b, 0xad,
	0x8b, 0xf6, 0xf9, 0x14, 0x0d, 0x6c, 0x8a, 0x6c, 0xc3, 0x89, 0xea, 0xee, 0x1f, 0xa3, 0xd0, 0x28,
	0x2a, 0xce, 0x1c, 0xbd, 0x97, 0x3d, 0xca, 0xbd, 0x91, 0xec, 0xd6, 0xed, 0x3a, 0xfb, 0xed, 0x27,
	0x6a, 0xb3, 0xc9, 0x40, 0x33, 0xfd, 0x2a, 0x66, 0x31, 0x29, 0xa5, 0xc6, 0xd8, 0x8b, 0x35, 0xc3,
	0x2b, 0xb9, 0x04, 0xe6, 0x99, 0x18, 0x3d, 0x8f, 0x0b, 0xd6, 0xdd, 0x42, 0x23, 0x7b, 0xf8, 0x9d,
	0xa2, 0xc2, 0xdb, 0x22, 0x7d, 0x2a, 0x3e, 0xe1, 0x4f, 0xd8, 0x4e, 0x48, 0xc2, 0xc3, 0xea, 0x5e,
	0xf8, 0xef, 0xc4, 0xcb, 0x38, 0x2d, 0x84, 0xa6, 0xe9, 0x4b, 0x70, 0x8e, 0xea, 0x25, 0x4e, 0x27,
	0x59, 0xa3, 0xd9, 0xba, 0x53, 0x33, 0x90, 0x3d, 0x3e, 0x6f, 0x7e, 0x0b, 0x16, 0xc7, 0x7f, 0xc3,
	0x16, 0x38, 0x4d, 0x82, 0x40, 0xe3, 0x6c, 0x25, 0x4f, 0x6c, 0x72, 0xd6, 0x84, 0xb9, 0xd8, 0x27,
	0xae, 0xb3, 0x43, 0x38, 0x1f, 0xd6, 0x2a, 0x02, 0xe7, 0x03, 0xe2, 0xee, 0x91, 0x0e, 0x75, 0x32,
	0x8c, 0x29, 0x77, 0xd6, 0x46, 0xa1, 0xef, 0x65, 0x17, 0xf8, 0x79, 0x8f, 0x1c, 0x3e, 0x66, 0x42,
	0xfa, 0xd3, 0x78, 0x7a, 0xd5, 0x28, 0x08, 0xb8, 0x7c, 0xbf, 0x26, 0x69, 0x1b, 0x9c, 0x4b, 0xb5,
	0xe4, 0x74, 0xd3, 0x29, 0x4d, 0xd2, 0x6d, 0xbb, 0x46, 0x14, 0xad, 0x28, 0x3d, 0x6c, 0xde, 0x07,
	0x67, 0x13, 0x6a, 0xf4, 0xcf, 0x12, 0x86, 0x94, 0xb6, 0x92, 0xb6, 0x3f, 0x12, 0x96, 0x1a, 0x92,
	0xbe, 0x24, 0x3d, 0xc5, 0x50, 0xcb, 0x0c, 0x40, 0x2b, 0x17, 0xb5, 0x28, 0xd2, 0x4f, 0xc1, 0xa2,
	0xa2, 0x3a, 0x03, 0xde, 0x50, 0xc0, 0x6f, 0xd5, 0x02, 0x3e, 0x86, 0xf3, 0xe6, 0x5f, 0x4b, 0x00,
	0x8c, 0xb6, 0xc2, 0x97, 0x06, 0x58, 0xae, 0xb0, 0x9e, 0xb0, 0x6d, 0xd7, 0xf0, 0xce, 0xe6, 0x6a,
	0x2d, 0x3b, 0x6b, 0x59, 0x51, 0x8c, 0x5e, 0xdf, 0xa2, 0x12, 0xf7, 0x98, 0x90, 0xd8, 0xdf, 0xc5,
	0x43, 0x9f, 0xe1, 0x61, 0xfd, 0xba, 0xc3, 0xd8, 0x00, 0x66, 0xb5, 0x2b, 0x83, 0xd7, 0x6b, 0xba,
	0x48, 0x73, 0xcd, 0xae, 0xeb, 0xf7, 0xd6, 0xa3, 0x18, 0xad, 0xa5, 0x0b, 0x31, 0xe1, 0x43, 0x8c,
	0x6a, 0x31, 0x0e, 0xd3, 0xd5, 0x78, 0xe7, 0x10, 0x13, 0xee, 0xcb, 0x2e, 0x0d, 0xf1, 0x40, 0xd0,
	0x50, 0xc0, 0x9f, 0x0c, 0x70, 0xa9, 0xd4, 0xc1, 0xc1, 0xab, 0xf6, 0xcc, 0xf6, 0xd1, 0xbc, 0x66,
	0xd7, 0x70, 0x84, 0xb7, 0xa2, 0x18, 0xad, 0x0f, 0xd7, 0x60, 0xff, 0x20, 0x81, 0x97, 0x2c, 0xd4,
	0x64, 0x62, 0xd9, 0x25, 0x12, 0x77, 0x89, 0xc0, 0xba, 0xb3, 0x65, 0xe8, 0xe1, 0x8f, 0x06, 0x58,
	0xae, 0x70, 0x79, 0x13, 0x0a, 0x38, 0xc2, 0x66, 0x4e, 0x28, 0xe0, 0x48, 0xe7, 0xf8, 0x56, 0x14,
	0xa3, 0x37, 0xb6, 0xe9, 0xbe, 0xbf, 0x97, 0xe2, 0xd5, 0x40, 0x73, 0x1c, 0xc3, 0xdf, 0x0d, 0x80,
	0xaa, 0x0c, 0x1d, 0x5c, 0xb5, 0xeb, 0x58, 0x4f, 0xd3, 0xae, 0x67, 0x13, 0xad, 0xbb, 0x51, 0x8c,
	0xee, 0x4c, 0x97, 0xa8, 0xba, 0x70, 0x9c, 0x5a, 0x3a, 0xac, 0x9f, 0x65, 0x0f, 0xab, 0x3e, 0x8c,
	0x7d, 0x0e, 0x7f, 0x35, 0xc0, 0xe5, 0x72, 0x7f, 0x04, 0xaf, 0xd9, 0xb3, 0x1b, 0x3f, 0xb3, 0x5d,
	0xc7, 0x71, 0x59, 0x1b, 0x51, 0x8c, 0x3e, 0x18, 0xc7, 0xad, 0x54, 0x99, 0x2a, 0xc0, 0x25, 0x5c,
	0xe3, 0xc4, 0x3e, 0x1f, 0x97, 0xf4, 0x30, 0x27, 0xf8, 0x8b, 0x01, 0x2e, 0x97, 0xfb, 0x9c, 0x09,
	0xd0, 0xd3, 0x5d, 0xd6, 0x04, 0xe8, 0x23, 0x9c, 0x93, 0xf5, 0x61, 0x14, 0xa3, 0xf7, 0x37, 0x3d,
	0xaf, 0x1a, 0xac, 0xfe, 0x13, 0x59, 0xd6, 0x28, 0xfe, 0x30, 0xc0, 0x95, 0x4a, 0xdb, 0x03, 0x6d,
	0xbb, 0x96, 0xf5, 0x32, 0xaf, 0xd7, 0xb5, 0x53, 0x1f, 0x45, 0x31, 0xba, 0x9d, 0xae, 0x3b, 0x16,
	0xfc, 0xdf, 0xd2, 0x26, 0x5c, 0xe6, 0x67, 0x60, 0xdb, 0xae, 0xe1, 0xd4, 0x8a, 0x4d, 0x78, 0xaa,
	0x47, 0xb2, 0x36, 0xa3, 0x18, 0x6d, 0x8c, 0x2b, 0x45, 0x3b, 0xae, 0x14, 0xff, 0x18, 0xd2, 0x0e,
	0xdb, 0xa7, 0x1c, 0x13, 0xd7, 0xf5, 0x07, 0x5c, 0x62, 0x22, 0x32, 0xad, 0x87, 0xf0, 0x67, 0x03,
	0x5c, 0xa9, 0x74, 0x17, 0xd0, 0xb6, 0x6b, 0x39, 0xa2, 0x09, 0xea, 0x8f, 0x76, 0x2d, 0xd6, 0x8d,
	0x28, 0x46, 0xab, 0xe3, 0x19, 0x64, 0x46, 0x43, 0x17, 0x21, 0xe3, 0xc3, 0x9c, 0x7a, 0x1a, 0xd3,
	0xcb, 0xb4, 0x28, 0x4b, 0x5e, 0xcc, 0x62, 0x51, 0x4e, 0x71, 0x25, 0xc5, 0xa2, 0x9c, 0xf6, 0x06,
	0x5b, 0xef, 0x44, 0x31, 0x7a, 0x73, 0x08, 0x54, 0x77, 0x8c, 0x14, 0xe3, 0x18, 0x9d, 0xe6, 0xdb,
	0x51, 0x8c, 0xb0, 0xce, 0x12, 0x7f, 0xd1, 0x25, 0x61, 0xd2, 0xaa, 0x05, 0x95, 0x92, 0xf1, 0x8e,
	0xc0, 0x82, 0x86, 0xc9, 0x81, 0xf7, 0xe6, 0x5e, 0x18, 0xc6, 0xff, 0x01, 0x00, 0x00, 0xff, 0xff,
	0xb5, 0x78, 0x80, 0x8f, 0x36, 0x13, 0x00, 0x00,
}
