// Code generated by protoc-gen-go. DO NOT EDIT.
// source: steammessages_gamenotifications.steamclient.proto

package unified

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package unified is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package unified to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type CGameNotifications_Variable struct {
	Key                  *string  `protobuf:"bytes,1,opt,name=key" json:"key,omitempty"`
	Value                *string  `protobuf:"bytes,2,opt,name=value" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameNotifications_Variable) Reset()         { *m = CGameNotifications_Variable{} }
func (m *CGameNotifications_Variable) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_Variable) ProtoMessage()    {}
func (*CGameNotifications_Variable) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{0}
}

func (m *CGameNotifications_Variable) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_Variable.Unmarshal(m, b)
}
func (m *CGameNotifications_Variable) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_Variable.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_Variable) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_Variable.Merge(m, src)
}
func (m *CGameNotifications_Variable) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_Variable.Size(m)
}
func (m *CGameNotifications_Variable) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_Variable.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_Variable proto.InternalMessageInfo

func (m *CGameNotifications_Variable) GetKey() string {
	if m != nil && m.Key != nil {
		return *m.Key
	}
	return ""
}

func (m *CGameNotifications_Variable) GetValue() string {
	if m != nil && m.Value != nil {
		return *m.Value
	}
	return ""
}

type CGameNotifications_LocalizedText struct {
	Token                *string                        `protobuf:"bytes,1,opt,name=token" json:"token,omitempty"`
	Variables            []*CGameNotifications_Variable `protobuf:"bytes,2,rep,name=variables" json:"variables,omitempty"`
	RenderedText         *string                        `protobuf:"bytes,3,opt,name=rendered_text" json:"rendered_text,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CGameNotifications_LocalizedText) Reset()         { *m = CGameNotifications_LocalizedText{} }
func (m *CGameNotifications_LocalizedText) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_LocalizedText) ProtoMessage()    {}
func (*CGameNotifications_LocalizedText) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{1}
}

func (m *CGameNotifications_LocalizedText) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_LocalizedText.Unmarshal(m, b)
}
func (m *CGameNotifications_LocalizedText) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_LocalizedText.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_LocalizedText) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_LocalizedText.Merge(m, src)
}
func (m *CGameNotifications_LocalizedText) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_LocalizedText.Size(m)
}
func (m *CGameNotifications_LocalizedText) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_LocalizedText.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_LocalizedText proto.InternalMessageInfo

func (m *CGameNotifications_LocalizedText) GetToken() string {
	if m != nil && m.Token != nil {
		return *m.Token
	}
	return ""
}

func (m *CGameNotifications_LocalizedText) GetVariables() []*CGameNotifications_Variable {
	if m != nil {
		return m.Variables
	}
	return nil
}

func (m *CGameNotifications_LocalizedText) GetRenderedText() string {
	if m != nil && m.RenderedText != nil {
		return *m.RenderedText
	}
	return ""
}

type CGameNotifications_UserStatus struct {
	Steamid              *uint64                           `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	State                *string                           `protobuf:"bytes,2,opt,name=state" json:"state,omitempty"`
	Title                *CGameNotifications_LocalizedText `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Message              *CGameNotifications_LocalizedText `protobuf:"bytes,4,opt,name=message" json:"message,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CGameNotifications_UserStatus) Reset()         { *m = CGameNotifications_UserStatus{} }
func (m *CGameNotifications_UserStatus) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_UserStatus) ProtoMessage()    {}
func (*CGameNotifications_UserStatus) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{2}
}

func (m *CGameNotifications_UserStatus) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_UserStatus.Unmarshal(m, b)
}
func (m *CGameNotifications_UserStatus) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_UserStatus.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_UserStatus) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_UserStatus.Merge(m, src)
}
func (m *CGameNotifications_UserStatus) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_UserStatus.Size(m)
}
func (m *CGameNotifications_UserStatus) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_UserStatus.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_UserStatus proto.InternalMessageInfo

func (m *CGameNotifications_UserStatus) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CGameNotifications_UserStatus) GetState() string {
	if m != nil && m.State != nil {
		return *m.State
	}
	return ""
}

func (m *CGameNotifications_UserStatus) GetTitle() *CGameNotifications_LocalizedText {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *CGameNotifications_UserStatus) GetMessage() *CGameNotifications_LocalizedText {
	if m != nil {
		return m.Message
	}
	return nil
}

type CGameNotifications_CreateSession_Request struct {
	Appid                *uint32                           `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	Context              *uint64                           `protobuf:"varint,2,opt,name=context" json:"context,omitempty"`
	Title                *CGameNotifications_LocalizedText `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Users                []*CGameNotifications_UserStatus  `protobuf:"bytes,4,rep,name=users" json:"users,omitempty"`
	Steamid              *uint64                           `protobuf:"fixed64,5,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CGameNotifications_CreateSession_Request) Reset() {
	*m = CGameNotifications_CreateSession_Request{}
}
func (m *CGameNotifications_CreateSession_Request) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_CreateSession_Request) ProtoMessage()    {}
func (*CGameNotifications_CreateSession_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{3}
}

func (m *CGameNotifications_CreateSession_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_CreateSession_Request.Unmarshal(m, b)
}
func (m *CGameNotifications_CreateSession_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_CreateSession_Request.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_CreateSession_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_CreateSession_Request.Merge(m, src)
}
func (m *CGameNotifications_CreateSession_Request) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_CreateSession_Request.Size(m)
}
func (m *CGameNotifications_CreateSession_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_CreateSession_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_CreateSession_Request proto.InternalMessageInfo

func (m *CGameNotifications_CreateSession_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CGameNotifications_CreateSession_Request) GetContext() uint64 {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return 0
}

func (m *CGameNotifications_CreateSession_Request) GetTitle() *CGameNotifications_LocalizedText {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *CGameNotifications_CreateSession_Request) GetUsers() []*CGameNotifications_UserStatus {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *CGameNotifications_CreateSession_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CGameNotifications_CreateSession_Response struct {
	Sessionid            *uint64  `protobuf:"varint,1,opt,name=sessionid" json:"sessionid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameNotifications_CreateSession_Response) Reset() {
	*m = CGameNotifications_CreateSession_Response{}
}
func (m *CGameNotifications_CreateSession_Response) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_CreateSession_Response) ProtoMessage()    {}
func (*CGameNotifications_CreateSession_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{4}
}

func (m *CGameNotifications_CreateSession_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_CreateSession_Response.Unmarshal(m, b)
}
func (m *CGameNotifications_CreateSession_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_CreateSession_Response.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_CreateSession_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_CreateSession_Response.Merge(m, src)
}
func (m *CGameNotifications_CreateSession_Response) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_CreateSession_Response.Size(m)
}
func (m *CGameNotifications_CreateSession_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_CreateSession_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_CreateSession_Response proto.InternalMessageInfo

func (m *CGameNotifications_CreateSession_Response) GetSessionid() uint64 {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return 0
}

type CGameNotifications_DeleteSession_Request struct {
	Sessionid            *uint64  `protobuf:"varint,1,opt,name=sessionid" json:"sessionid,omitempty"`
	Appid                *uint32  `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	Steamid              *uint64  `protobuf:"fixed64,3,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameNotifications_DeleteSession_Request) Reset() {
	*m = CGameNotifications_DeleteSession_Request{}
}
func (m *CGameNotifications_DeleteSession_Request) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_DeleteSession_Request) ProtoMessage()    {}
func (*CGameNotifications_DeleteSession_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{5}
}

func (m *CGameNotifications_DeleteSession_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_DeleteSession_Request.Unmarshal(m, b)
}
func (m *CGameNotifications_DeleteSession_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_DeleteSession_Request.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_DeleteSession_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_DeleteSession_Request.Merge(m, src)
}
func (m *CGameNotifications_DeleteSession_Request) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_DeleteSession_Request.Size(m)
}
func (m *CGameNotifications_DeleteSession_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_DeleteSession_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_DeleteSession_Request proto.InternalMessageInfo

func (m *CGameNotifications_DeleteSession_Request) GetSessionid() uint64 {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return 0
}

func (m *CGameNotifications_DeleteSession_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CGameNotifications_DeleteSession_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CGameNotifications_DeleteSession_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameNotifications_DeleteSession_Response) Reset() {
	*m = CGameNotifications_DeleteSession_Response{}
}
func (m *CGameNotifications_DeleteSession_Response) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_DeleteSession_Response) ProtoMessage()    {}
func (*CGameNotifications_DeleteSession_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{6}
}

func (m *CGameNotifications_DeleteSession_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_DeleteSession_Response.Unmarshal(m, b)
}
func (m *CGameNotifications_DeleteSession_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_DeleteSession_Response.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_DeleteSession_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_DeleteSession_Response.Merge(m, src)
}
func (m *CGameNotifications_DeleteSession_Response) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_DeleteSession_Response.Size(m)
}
func (m *CGameNotifications_DeleteSession_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_DeleteSession_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_DeleteSession_Response proto.InternalMessageInfo

type CGameNotifications_UpdateSession_Request struct {
	Sessionid            *uint64                           `protobuf:"varint,1,opt,name=sessionid" json:"sessionid,omitempty"`
	Appid                *uint32                           `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	Title                *CGameNotifications_LocalizedText `protobuf:"bytes,3,opt,name=title" json:"title,omitempty"`
	Users                []*CGameNotifications_UserStatus  `protobuf:"bytes,4,rep,name=users" json:"users,omitempty"`
	Steamid              *uint64                           `protobuf:"fixed64,6,opt,name=steamid" json:"steamid,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CGameNotifications_UpdateSession_Request) Reset() {
	*m = CGameNotifications_UpdateSession_Request{}
}
func (m *CGameNotifications_UpdateSession_Request) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_UpdateSession_Request) ProtoMessage()    {}
func (*CGameNotifications_UpdateSession_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{7}
}

func (m *CGameNotifications_UpdateSession_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_UpdateSession_Request.Unmarshal(m, b)
}
func (m *CGameNotifications_UpdateSession_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_UpdateSession_Request.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_UpdateSession_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_UpdateSession_Request.Merge(m, src)
}
func (m *CGameNotifications_UpdateSession_Request) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_UpdateSession_Request.Size(m)
}
func (m *CGameNotifications_UpdateSession_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_UpdateSession_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_UpdateSession_Request proto.InternalMessageInfo

func (m *CGameNotifications_UpdateSession_Request) GetSessionid() uint64 {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return 0
}

func (m *CGameNotifications_UpdateSession_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CGameNotifications_UpdateSession_Request) GetTitle() *CGameNotifications_LocalizedText {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *CGameNotifications_UpdateSession_Request) GetUsers() []*CGameNotifications_UserStatus {
	if m != nil {
		return m.Users
	}
	return nil
}

func (m *CGameNotifications_UpdateSession_Request) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

type CGameNotifications_UpdateSession_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameNotifications_UpdateSession_Response) Reset() {
	*m = CGameNotifications_UpdateSession_Response{}
}
func (m *CGameNotifications_UpdateSession_Response) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_UpdateSession_Response) ProtoMessage()    {}
func (*CGameNotifications_UpdateSession_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{8}
}

func (m *CGameNotifications_UpdateSession_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_UpdateSession_Response.Unmarshal(m, b)
}
func (m *CGameNotifications_UpdateSession_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_UpdateSession_Response.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_UpdateSession_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_UpdateSession_Response.Merge(m, src)
}
func (m *CGameNotifications_UpdateSession_Response) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_UpdateSession_Response.Size(m)
}
func (m *CGameNotifications_UpdateSession_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_UpdateSession_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_UpdateSession_Response proto.InternalMessageInfo

type CGameNotifications_EnumerateSessions_Request struct {
	Appid                  *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	IncludeAllUserMessages *bool    `protobuf:"varint,3,opt,name=include_all_user_messages" json:"include_all_user_messages,omitempty"`
	IncludeAuthUserMessage *bool    `protobuf:"varint,4,opt,name=include_auth_user_message" json:"include_auth_user_message,omitempty"`
	Language               *string  `protobuf:"bytes,5,opt,name=language" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *CGameNotifications_EnumerateSessions_Request) Reset() {
	*m = CGameNotifications_EnumerateSessions_Request{}
}
func (m *CGameNotifications_EnumerateSessions_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CGameNotifications_EnumerateSessions_Request) ProtoMessage() {}
func (*CGameNotifications_EnumerateSessions_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{9}
}

func (m *CGameNotifications_EnumerateSessions_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_EnumerateSessions_Request.Unmarshal(m, b)
}
func (m *CGameNotifications_EnumerateSessions_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_EnumerateSessions_Request.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_EnumerateSessions_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_EnumerateSessions_Request.Merge(m, src)
}
func (m *CGameNotifications_EnumerateSessions_Request) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_EnumerateSessions_Request.Size(m)
}
func (m *CGameNotifications_EnumerateSessions_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_EnumerateSessions_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_EnumerateSessions_Request proto.InternalMessageInfo

func (m *CGameNotifications_EnumerateSessions_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CGameNotifications_EnumerateSessions_Request) GetIncludeAllUserMessages() bool {
	if m != nil && m.IncludeAllUserMessages != nil {
		return *m.IncludeAllUserMessages
	}
	return false
}

func (m *CGameNotifications_EnumerateSessions_Request) GetIncludeAuthUserMessage() bool {
	if m != nil && m.IncludeAuthUserMessage != nil {
		return *m.IncludeAuthUserMessage
	}
	return false
}

func (m *CGameNotifications_EnumerateSessions_Request) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

type CGameNotifications_Session struct {
	Sessionid            *uint64                           `protobuf:"varint,1,opt,name=sessionid" json:"sessionid,omitempty"`
	Appid                *uint64                           `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	Context              *uint64                           `protobuf:"varint,3,opt,name=context" json:"context,omitempty"`
	Title                *CGameNotifications_LocalizedText `protobuf:"bytes,4,opt,name=title" json:"title,omitempty"`
	TimeCreated          *uint32                           `protobuf:"varint,5,opt,name=time_created" json:"time_created,omitempty"`
	TimeUpdated          *uint32                           `protobuf:"varint,6,opt,name=time_updated" json:"time_updated,omitempty"`
	UserStatus           []*CGameNotifications_UserStatus  `protobuf:"bytes,7,rep,name=user_status" json:"user_status,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                          `json:"-"`
	XXX_unrecognized     []byte                            `json:"-"`
	XXX_sizecache        int32                             `json:"-"`
}

func (m *CGameNotifications_Session) Reset()         { *m = CGameNotifications_Session{} }
func (m *CGameNotifications_Session) String() string { return proto.CompactTextString(m) }
func (*CGameNotifications_Session) ProtoMessage()    {}
func (*CGameNotifications_Session) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{10}
}

func (m *CGameNotifications_Session) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_Session.Unmarshal(m, b)
}
func (m *CGameNotifications_Session) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_Session.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_Session) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_Session.Merge(m, src)
}
func (m *CGameNotifications_Session) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_Session.Size(m)
}
func (m *CGameNotifications_Session) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_Session.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_Session proto.InternalMessageInfo

func (m *CGameNotifications_Session) GetSessionid() uint64 {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return 0
}

func (m *CGameNotifications_Session) GetAppid() uint64 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CGameNotifications_Session) GetContext() uint64 {
	if m != nil && m.Context != nil {
		return *m.Context
	}
	return 0
}

func (m *CGameNotifications_Session) GetTitle() *CGameNotifications_LocalizedText {
	if m != nil {
		return m.Title
	}
	return nil
}

func (m *CGameNotifications_Session) GetTimeCreated() uint32 {
	if m != nil && m.TimeCreated != nil {
		return *m.TimeCreated
	}
	return 0
}

func (m *CGameNotifications_Session) GetTimeUpdated() uint32 {
	if m != nil && m.TimeUpdated != nil {
		return *m.TimeUpdated
	}
	return 0
}

func (m *CGameNotifications_Session) GetUserStatus() []*CGameNotifications_UserStatus {
	if m != nil {
		return m.UserStatus
	}
	return nil
}

type CGameNotifications_EnumerateSessions_Response struct {
	Sessions             []*CGameNotifications_Session `protobuf:"bytes,1,rep,name=sessions" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CGameNotifications_EnumerateSessions_Response) Reset() {
	*m = CGameNotifications_EnumerateSessions_Response{}
}
func (m *CGameNotifications_EnumerateSessions_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CGameNotifications_EnumerateSessions_Response) ProtoMessage() {}
func (*CGameNotifications_EnumerateSessions_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{11}
}

func (m *CGameNotifications_EnumerateSessions_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_EnumerateSessions_Response.Unmarshal(m, b)
}
func (m *CGameNotifications_EnumerateSessions_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_EnumerateSessions_Response.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_EnumerateSessions_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_EnumerateSessions_Response.Merge(m, src)
}
func (m *CGameNotifications_EnumerateSessions_Response) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_EnumerateSessions_Response.Size(m)
}
func (m *CGameNotifications_EnumerateSessions_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_EnumerateSessions_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_EnumerateSessions_Response proto.InternalMessageInfo

func (m *CGameNotifications_EnumerateSessions_Response) GetSessions() []*CGameNotifications_Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type CGameNotifications_GetSessionDetails_Request struct {
	Sessions             []*CGameNotifications_GetSessionDetails_Request_RequestedSession `protobuf:"bytes,1,rep,name=sessions" json:"sessions,omitempty"`
	Appid                *uint32                                                          `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	Language             *string                                                          `protobuf:"bytes,3,opt,name=language" json:"language,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                                                         `json:"-"`
	XXX_unrecognized     []byte                                                           `json:"-"`
	XXX_sizecache        int32                                                            `json:"-"`
}

func (m *CGameNotifications_GetSessionDetails_Request) Reset() {
	*m = CGameNotifications_GetSessionDetails_Request{}
}
func (m *CGameNotifications_GetSessionDetails_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CGameNotifications_GetSessionDetails_Request) ProtoMessage() {}
func (*CGameNotifications_GetSessionDetails_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{12}
}

func (m *CGameNotifications_GetSessionDetails_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_GetSessionDetails_Request.Unmarshal(m, b)
}
func (m *CGameNotifications_GetSessionDetails_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_GetSessionDetails_Request.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_GetSessionDetails_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_GetSessionDetails_Request.Merge(m, src)
}
func (m *CGameNotifications_GetSessionDetails_Request) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_GetSessionDetails_Request.Size(m)
}
func (m *CGameNotifications_GetSessionDetails_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_GetSessionDetails_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_GetSessionDetails_Request proto.InternalMessageInfo

func (m *CGameNotifications_GetSessionDetails_Request) GetSessions() []*CGameNotifications_GetSessionDetails_Request_RequestedSession {
	if m != nil {
		return m.Sessions
	}
	return nil
}

func (m *CGameNotifications_GetSessionDetails_Request) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CGameNotifications_GetSessionDetails_Request) GetLanguage() string {
	if m != nil && m.Language != nil {
		return *m.Language
	}
	return ""
}

type CGameNotifications_GetSessionDetails_Request_RequestedSession struct {
	Sessionid              *uint64  `protobuf:"varint,1,opt,name=sessionid" json:"sessionid,omitempty"`
	IncludeAuthUserMessage *bool    `protobuf:"varint,3,opt,name=include_auth_user_message" json:"include_auth_user_message,omitempty"`
	XXX_NoUnkeyedLiteral   struct{} `json:"-"`
	XXX_unrecognized       []byte   `json:"-"`
	XXX_sizecache          int32    `json:"-"`
}

func (m *CGameNotifications_GetSessionDetails_Request_RequestedSession) Reset() {
	*m = CGameNotifications_GetSessionDetails_Request_RequestedSession{}
}
func (m *CGameNotifications_GetSessionDetails_Request_RequestedSession) String() string {
	return proto.CompactTextString(m)
}
func (*CGameNotifications_GetSessionDetails_Request_RequestedSession) ProtoMessage() {}
func (*CGameNotifications_GetSessionDetails_Request_RequestedSession) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{12, 0}
}

func (m *CGameNotifications_GetSessionDetails_Request_RequestedSession) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_GetSessionDetails_Request_RequestedSession.Unmarshal(m, b)
}
func (m *CGameNotifications_GetSessionDetails_Request_RequestedSession) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_GetSessionDetails_Request_RequestedSession.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_GetSessionDetails_Request_RequestedSession) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_GetSessionDetails_Request_RequestedSession.Merge(m, src)
}
func (m *CGameNotifications_GetSessionDetails_Request_RequestedSession) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_GetSessionDetails_Request_RequestedSession.Size(m)
}
func (m *CGameNotifications_GetSessionDetails_Request_RequestedSession) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_GetSessionDetails_Request_RequestedSession.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_GetSessionDetails_Request_RequestedSession proto.InternalMessageInfo

func (m *CGameNotifications_GetSessionDetails_Request_RequestedSession) GetSessionid() uint64 {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return 0
}

func (m *CGameNotifications_GetSessionDetails_Request_RequestedSession) GetIncludeAuthUserMessage() bool {
	if m != nil && m.IncludeAuthUserMessage != nil {
		return *m.IncludeAuthUserMessage
	}
	return false
}

type CGameNotifications_GetSessionDetails_Response struct {
	Sessions             []*CGameNotifications_Session `protobuf:"bytes,1,rep,name=sessions" json:"sessions,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                      `json:"-"`
	XXX_unrecognized     []byte                        `json:"-"`
	XXX_sizecache        int32                         `json:"-"`
}

func (m *CGameNotifications_GetSessionDetails_Response) Reset() {
	*m = CGameNotifications_GetSessionDetails_Response{}
}
func (m *CGameNotifications_GetSessionDetails_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CGameNotifications_GetSessionDetails_Response) ProtoMessage() {}
func (*CGameNotifications_GetSessionDetails_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{13}
}

func (m *CGameNotifications_GetSessionDetails_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_GetSessionDetails_Response.Unmarshal(m, b)
}
func (m *CGameNotifications_GetSessionDetails_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_GetSessionDetails_Response.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_GetSessionDetails_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_GetSessionDetails_Response.Merge(m, src)
}
func (m *CGameNotifications_GetSessionDetails_Response) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_GetSessionDetails_Response.Size(m)
}
func (m *CGameNotifications_GetSessionDetails_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_GetSessionDetails_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_GetSessionDetails_Response proto.InternalMessageInfo

func (m *CGameNotifications_GetSessionDetails_Response) GetSessions() []*CGameNotifications_Session {
	if m != nil {
		return m.Sessions
	}
	return nil
}

type GameNotificationSettings struct {
	Appid                *uint32  `protobuf:"varint,1,opt,name=appid" json:"appid,omitempty"`
	AllowNotifications   *bool    `protobuf:"varint,2,opt,name=allow_notifications" json:"allow_notifications,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GameNotificationSettings) Reset()         { *m = GameNotificationSettings{} }
func (m *GameNotificationSettings) String() string { return proto.CompactTextString(m) }
func (*GameNotificationSettings) ProtoMessage()    {}
func (*GameNotificationSettings) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{14}
}

func (m *GameNotificationSettings) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GameNotificationSettings.Unmarshal(m, b)
}
func (m *GameNotificationSettings) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GameNotificationSettings.Marshal(b, m, deterministic)
}
func (m *GameNotificationSettings) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GameNotificationSettings.Merge(m, src)
}
func (m *GameNotificationSettings) XXX_Size() int {
	return xxx_messageInfo_GameNotificationSettings.Size(m)
}
func (m *GameNotificationSettings) XXX_DiscardUnknown() {
	xxx_messageInfo_GameNotificationSettings.DiscardUnknown(m)
}

var xxx_messageInfo_GameNotificationSettings proto.InternalMessageInfo

func (m *GameNotificationSettings) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *GameNotificationSettings) GetAllowNotifications() bool {
	if m != nil && m.AllowNotifications != nil {
		return *m.AllowNotifications
	}
	return false
}

type CGameNotifications_UpdateNotificationSettings_Request struct {
	GameNotificationSettings []*GameNotificationSettings `protobuf:"bytes,1,rep,name=game_notification_settings" json:"game_notification_settings,omitempty"`
	XXX_NoUnkeyedLiteral     struct{}                    `json:"-"`
	XXX_unrecognized         []byte                      `json:"-"`
	XXX_sizecache            int32                       `json:"-"`
}

func (m *CGameNotifications_UpdateNotificationSettings_Request) Reset() {
	*m = CGameNotifications_UpdateNotificationSettings_Request{}
}
func (m *CGameNotifications_UpdateNotificationSettings_Request) String() string {
	return proto.CompactTextString(m)
}
func (*CGameNotifications_UpdateNotificationSettings_Request) ProtoMessage() {}
func (*CGameNotifications_UpdateNotificationSettings_Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{15}
}

func (m *CGameNotifications_UpdateNotificationSettings_Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Request.Unmarshal(m, b)
}
func (m *CGameNotifications_UpdateNotificationSettings_Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Request.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_UpdateNotificationSettings_Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Request.Merge(m, src)
}
func (m *CGameNotifications_UpdateNotificationSettings_Request) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Request.Size(m)
}
func (m *CGameNotifications_UpdateNotificationSettings_Request) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Request.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Request proto.InternalMessageInfo

func (m *CGameNotifications_UpdateNotificationSettings_Request) GetGameNotificationSettings() []*GameNotificationSettings {
	if m != nil {
		return m.GameNotificationSettings
	}
	return nil
}

type CGameNotifications_UpdateNotificationSettings_Response struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameNotifications_UpdateNotificationSettings_Response) Reset() {
	*m = CGameNotifications_UpdateNotificationSettings_Response{}
}
func (m *CGameNotifications_UpdateNotificationSettings_Response) String() string {
	return proto.CompactTextString(m)
}
func (*CGameNotifications_UpdateNotificationSettings_Response) ProtoMessage() {}
func (*CGameNotifications_UpdateNotificationSettings_Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{16}
}

func (m *CGameNotifications_UpdateNotificationSettings_Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Response.Unmarshal(m, b)
}
func (m *CGameNotifications_UpdateNotificationSettings_Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Response.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_UpdateNotificationSettings_Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Response.Merge(m, src)
}
func (m *CGameNotifications_UpdateNotificationSettings_Response) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Response.Size(m)
}
func (m *CGameNotifications_UpdateNotificationSettings_Response) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Response.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_UpdateNotificationSettings_Response proto.InternalMessageInfo

type CGameNotifications_OnNotificationsRequested_Notification struct {
	Steamid              *uint64  `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Appid                *uint32  `protobuf:"varint,2,opt,name=appid" json:"appid,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CGameNotifications_OnNotificationsRequested_Notification) Reset() {
	*m = CGameNotifications_OnNotificationsRequested_Notification{}
}
func (m *CGameNotifications_OnNotificationsRequested_Notification) String() string {
	return proto.CompactTextString(m)
}
func (*CGameNotifications_OnNotificationsRequested_Notification) ProtoMessage() {}
func (*CGameNotifications_OnNotificationsRequested_Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{17}
}

func (m *CGameNotifications_OnNotificationsRequested_Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_OnNotificationsRequested_Notification.Unmarshal(m, b)
}
func (m *CGameNotifications_OnNotificationsRequested_Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_OnNotificationsRequested_Notification.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_OnNotificationsRequested_Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_OnNotificationsRequested_Notification.Merge(m, src)
}
func (m *CGameNotifications_OnNotificationsRequested_Notification) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_OnNotificationsRequested_Notification.Size(m)
}
func (m *CGameNotifications_OnNotificationsRequested_Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_OnNotificationsRequested_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_OnNotificationsRequested_Notification proto.InternalMessageInfo

func (m *CGameNotifications_OnNotificationsRequested_Notification) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CGameNotifications_OnNotificationsRequested_Notification) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

type CGameNotifications_OnUserStatusChanged_Notification struct {
	Steamid              *uint64                        `protobuf:"fixed64,1,opt,name=steamid" json:"steamid,omitempty"`
	Sessionid            *uint64                        `protobuf:"varint,2,opt,name=sessionid" json:"sessionid,omitempty"`
	Appid                *uint32                        `protobuf:"varint,3,opt,name=appid" json:"appid,omitempty"`
	Status               *CGameNotifications_UserStatus `protobuf:"bytes,4,opt,name=status" json:"status,omitempty"`
	Removed              *bool                          `protobuf:"varint,5,opt,name=removed" json:"removed,omitempty"`
	XXX_NoUnkeyedLiteral struct{}                       `json:"-"`
	XXX_unrecognized     []byte                         `json:"-"`
	XXX_sizecache        int32                          `json:"-"`
}

func (m *CGameNotifications_OnUserStatusChanged_Notification) Reset() {
	*m = CGameNotifications_OnUserStatusChanged_Notification{}
}
func (m *CGameNotifications_OnUserStatusChanged_Notification) String() string {
	return proto.CompactTextString(m)
}
func (*CGameNotifications_OnUserStatusChanged_Notification) ProtoMessage() {}
func (*CGameNotifications_OnUserStatusChanged_Notification) Descriptor() ([]byte, []int) {
	return fileDescriptor_d73f3ce78278ce26, []int{18}
}

func (m *CGameNotifications_OnUserStatusChanged_Notification) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CGameNotifications_OnUserStatusChanged_Notification.Unmarshal(m, b)
}
func (m *CGameNotifications_OnUserStatusChanged_Notification) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CGameNotifications_OnUserStatusChanged_Notification.Marshal(b, m, deterministic)
}
func (m *CGameNotifications_OnUserStatusChanged_Notification) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CGameNotifications_OnUserStatusChanged_Notification.Merge(m, src)
}
func (m *CGameNotifications_OnUserStatusChanged_Notification) XXX_Size() int {
	return xxx_messageInfo_CGameNotifications_OnUserStatusChanged_Notification.Size(m)
}
func (m *CGameNotifications_OnUserStatusChanged_Notification) XXX_DiscardUnknown() {
	xxx_messageInfo_CGameNotifications_OnUserStatusChanged_Notification.DiscardUnknown(m)
}

var xxx_messageInfo_CGameNotifications_OnUserStatusChanged_Notification proto.InternalMessageInfo

func (m *CGameNotifications_OnUserStatusChanged_Notification) GetSteamid() uint64 {
	if m != nil && m.Steamid != nil {
		return *m.Steamid
	}
	return 0
}

func (m *CGameNotifications_OnUserStatusChanged_Notification) GetSessionid() uint64 {
	if m != nil && m.Sessionid != nil {
		return *m.Sessionid
	}
	return 0
}

func (m *CGameNotifications_OnUserStatusChanged_Notification) GetAppid() uint32 {
	if m != nil && m.Appid != nil {
		return *m.Appid
	}
	return 0
}

func (m *CGameNotifications_OnUserStatusChanged_Notification) GetStatus() *CGameNotifications_UserStatus {
	if m != nil {
		return m.Status
	}
	return nil
}

func (m *CGameNotifications_OnUserStatusChanged_Notification) GetRemoved() bool {
	if m != nil && m.Removed != nil {
		return *m.Removed
	}
	return false
}

func init() {
	proto.RegisterType((*CGameNotifications_Variable)(nil), "CGameNotifications_Variable")
	proto.RegisterType((*CGameNotifications_LocalizedText)(nil), "CGameNotifications_LocalizedText")
	proto.RegisterType((*CGameNotifications_UserStatus)(nil), "CGameNotifications_UserStatus")
	proto.RegisterType((*CGameNotifications_CreateSession_Request)(nil), "CGameNotifications_CreateSession_Request")
	proto.RegisterType((*CGameNotifications_CreateSession_Response)(nil), "CGameNotifications_CreateSession_Response")
	proto.RegisterType((*CGameNotifications_DeleteSession_Request)(nil), "CGameNotifications_DeleteSession_Request")
	proto.RegisterType((*CGameNotifications_DeleteSession_Response)(nil), "CGameNotifications_DeleteSession_Response")
	proto.RegisterType((*CGameNotifications_UpdateSession_Request)(nil), "CGameNotifications_UpdateSession_Request")
	proto.RegisterType((*CGameNotifications_UpdateSession_Response)(nil), "CGameNotifications_UpdateSession_Response")
	proto.RegisterType((*CGameNotifications_EnumerateSessions_Request)(nil), "CGameNotifications_EnumerateSessions_Request")
	proto.RegisterType((*CGameNotifications_Session)(nil), "CGameNotifications_Session")
	proto.RegisterType((*CGameNotifications_EnumerateSessions_Response)(nil), "CGameNotifications_EnumerateSessions_Response")
	proto.RegisterType((*CGameNotifications_GetSessionDetails_Request)(nil), "CGameNotifications_GetSessionDetails_Request")
	proto.RegisterType((*CGameNotifications_GetSessionDetails_Request_RequestedSession)(nil), "CGameNotifications_GetSessionDetails_Request.RequestedSession")
	proto.RegisterType((*CGameNotifications_GetSessionDetails_Response)(nil), "CGameNotifications_GetSessionDetails_Response")
	proto.RegisterType((*GameNotificationSettings)(nil), "GameNotificationSettings")
	proto.RegisterType((*CGameNotifications_UpdateNotificationSettings_Request)(nil), "CGameNotifications_UpdateNotificationSettings_Request")
	proto.RegisterType((*CGameNotifications_UpdateNotificationSettings_Response)(nil), "CGameNotifications_UpdateNotificationSettings_Response")
	proto.RegisterType((*CGameNotifications_OnNotificationsRequested_Notification)(nil), "CGameNotifications_OnNotificationsRequested_Notification")
	proto.RegisterType((*CGameNotifications_OnUserStatusChanged_Notification)(nil), "CGameNotifications_OnUserStatusChanged_Notification")
}

func init() {
	proto.RegisterFile("steammessages_gamenotifications.steamclient.proto", fileDescriptor_d73f3ce78278ce26)
}

var fileDescriptor_d73f3ce78278ce26 = []byte{
	// 2262 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xd4, 0x59, 0xcd, 0x8f, 0x1c, 0x47,
	0x15, 0x57, 0xef, 0xec, 0xda, 0xeb, 0x32, 0x96, 0x70, 0x07, 0x89, 0xca, 0xd8, 0x71, 0xca, 0x1d,
	0x1c, 0xdb, 0xf1, 0x6e, 0x19, 0x6f, 0x88, 0x3f, 0x80, 0x44, 0x78, 0xd6, 0x91, 0x89, 0x64, 0x36,
	0x89, 0xed, 0x04, 0x0b, 0x21, 0x46, 0x35, 0xdd, 0x6f, 0x76, 0x2a, 0xdb, 0xd3, 0x3d, 0x74, 0x55,
	0xef, 0x78, 0x73, 0x20, 0xa8, 0xf9, 0x3a, 0x85, 0x20, 0x92, 0x08, 0x10, 0x52, 0x24, 0x24, 0x14,
	0x71, 0xe0, 0xc2, 0xa1, 0x8f, 0x20, 0xa4, 0x48, 0x1c, 0x39, 0xe6, 0x0a, 0x67, 0xfe, 0x0a, 0x54,
	0xd5, 0x55, 0xfd, 0x31, 0xd3, 0x63, 0xef, 0x2e, 0x12, 0x51, 0x2e, 0x96, 0xa7, 0xab, 0xde, 0xab,
	0xdf, 0x7b, 0xef, 0xf7, 0x3e, 0xaa, 0x16, 0x5d, 0x11, 0x12, 0xd8, 0x78, 0x0c, 0x42, 0xb0, 0x6d,
	0x10, 0xfd, 0x6d, 0x36, 0x86, 0x28, 0x96, 0x7c, 0xc8, 0x7d, 0x26, 0x79, 0x1c, 0x09, 0xaa, 0xd7,
	0xfd, 0x90, 0x43, 0x24, 0xe9, 0x24, 0x89, 0x65, 0xdc, 0x5d, 0x6b, 0x8a, 0xa4, 0x11, 0x1f, 0x72,
	0x08, 0xfa, 0x03, 0x26, 0x60, 0x7e, 0xb7, 0xf7, 0xef, 0x25, 0x74, 0x6a, 0xf3, 0x36, 0x1b, 0xc3,
	0x56, 0x5d, 0x6d, 0xff, 0x4d, 0x96, 0x70, 0x36, 0x08, 0xc1, 0xfd, 0xd8, 0x41, 0x9d, 0x1d, 0xd8,
	0xc3, 0x0e, 0x71, 0x2e, 0x1c, 0xeb, 0xfd, 0xd6, 0xc9, 0x72, 0xfc, 0xbe, 0x73, 0x7f, 0x04, 0x24,
	0x62, 0x63, 0x20, 0xf1, 0x90, 0xc8, 0x11, 0x90, 0x5d, 0xb3, 0x9b, 0xf0, 0x48, 0xff, 0x0e, 0x63,
	0x9f, 0x85, 0xfc, 0x6d, 0x08, 0x88, 0x84, 0x87, 0x92, 0xac, 0xaf, 0x13, 0x16, 0xed, 0x4d, 0x47,
	0x90, 0x00, 0x91, 0x23, 0x26, 0xc9, 0x39, 0x2b, 0xa0, 0x94, 0x9c, 0x23, 0x5c, 0x90, 0x61, 0x9c,
	0x46, 0x01, 0x99, 0x72, 0x39, 0x32, 0x2a, 0xb4, 0x20, 0x97, 0x64, 0xca, 0xc3, 0x90, 0x0c, 0x80,
	0x88, 0x74, 0x20, 0x24, 0x97, 0x69, 0x00, 0xc5, 0x36, 0xbd, 0x69, 0x9b, 0xef, 0x42, 0x44, 0x76,
	0x59, 0x98, 0x82, 0xfb, 0x1b, 0x07, 0xad, 0xe8, 0xff, 0xe1, 0x25, 0x0d, 0xf5, 0x17, 0x0a, 0x6a,
	0xa6, 0xa1, 0xea, 0xcf, 0x73, 0x58, 0x65, 0x5c, 0x2a, 0x95, 0x8b, 0x90, 0xf3, 0x88, 0x4c, 0x42,
	0xe6, 0x97, 0xc2, 0xf6, 0xc0, 0x42, 0x05, 0x25, 0x64, 0x93, 0x45, 0x84, 0x4b, 0x01, 0xe1, 0x50,
	0x81, 0x64, 0x56, 0x5e, 0x7b, 0x91, 0xc8, 0x78, 0x07, 0x22, 0xea, 0xfd, 0xac, 0x83, 0x48, 0x8b,
	0x8b, 0xef, 0xd8, 0xa3, 0xee, 0xc3, 0x43, 0xe9, 0x7e, 0x1b, 0xad, 0xe8, 0xed, 0xc6, 0xd1, 0x37,
	0xb2, 0x1c, 0xbf, 0x70, 0xb3, 0x45, 0x5d, 0xe1, 0xc0, 0x31, 0x9b, 0x08, 0x65, 0x80, 0xc2, 0x14,
	0x80, 0xe0, 0x09, 0x04, 0x44, 0xc8, 0x84, 0x47, 0xdb, 0xd4, 0x7d, 0xd7, 0x41, 0xc7, 0x2c, 0x42,
	0x81, 0x97, 0x48, 0xe7, 0xc2, 0xf1, 0x8d, 0xd3, 0xf4, 0x11, 0x31, 0xee, 0x7d, 0x3f, 0xcb, 0xf1,
	0x83, 0x9b, 0x24, 0xe4, 0x42, 0x2a, 0x43, 0x4b, 0xe1, 0xc2, 0x71, 0x62, 0xde, 0x53, 0x2c, 0xda,
	0xab, 0xed, 0x2a, 0x62, 0x37, 0xe7, 0x40, 0x8b, 0xe7, 0xe7, 0x0e, 0x3a, 0x91, 0x40, 0x14, 0x40,
	0x02, 0x41, 0x5f, 0x79, 0x15, 0x77, 0xb4, 0x89, 0x71, 0x96, 0xe3, 0x1d, 0x65, 0x3b, 0xb1, 0xab,
	0x56, 0x47, 0x02, 0x3f, 0x4c, 0x41, 0x48, 0x08, 0x48, 0xc8, 0xa2, 0xed, 0x94, 0x6d, 0xc3, 0x1a,
	0xf1, 0xe3, 0xf1, 0x24, 0x04, 0x09, 0x45, 0xf0, 0xcb, 0x20, 0x96, 0xb8, 0x94, 0x45, 0x6b, 0x84,
	0x0f, 0x55, 0x0c, 0x8c, 0x10, 0x99, 0x32, 0x41, 0xc4, 0x04, 0x7c, 0x9d, 0x00, 0xd4, 0xfb, 0x70,
	0x19, 0x3d, 0xd5, 0xe2, 0x86, 0x37, 0x04, 0x24, 0xf7, 0x24, 0x93, 0xa9, 0x70, 0xaf, 0xa0, 0xa3,
	0x3a, 0x43, 0x78, 0xa0, 0xc3, 0x70, 0xa4, 0x47, 0xb2, 0x1c, 0x9f, 0x56, 0x14, 0x32, 0x6a, 0x7c,
	0x92, 0x0a, 0x48, 0xce, 0x0b, 0x62, 0xb6, 0x51, 0xf7, 0x8f, 0x0e, 0x5a, 0x11, 0x92, 0x49, 0x4b,
	0xbb, 0x0f, 0x14, 0xed, 0xde, 0xd3, 0xb4, 0x2b, 0xb7, 0x32, 0xa9, 0xa8, 0x92, 0x00, 0x0b, 0xf6,
	0x54, 0x2e, 0x48, 0xb3, 0xa6, 0x78, 0x5f, 0x7c, 0x94, 0xb1, 0xa2, 0xd9, 0x1e, 0x25, 0x64, 0xca,
	0xb8, 0xe4, 0xd1, 0xb6, 0xda, 0xa6, 0x54, 0xa8, 0x7c, 0x57, 0xdb, 0xec, 0xe7, 0x58, 0xf9, 0x9e,
	0x30, 0x5f, 0xf3, 0x61, 0x98, 0xc4, 0xe3, 0x52, 0x19, 0x2d, 0x3d, 0x14, 0xac, 0x15, 0x54, 0x35,
	0xa2, 0xf1, 0x2e, 0x24, 0xd4, 0xfd, 0xa9, 0x83, 0x56, 0x24, 0x97, 0x21, 0x68, 0xe7, 0x1f, 0xdf,
	0x38, 0x4b, 0x1f, 0xc7, 0xc8, 0xde, 0xdd, 0x2c, 0xc7, 0x5b, 0xf7, 0x95, 0x8c, 0x65, 0xbf, 0x00,
	0x21, 0x0a, 0x22, 0x92, 0x80, 0x0b, 0x85, 0xb8, 0xe0, 0x20, 0x17, 0xc6, 0x1e, 0x1d, 0x3e, 0x9e,
	0x94, 0x4c, 0x52, 0x40, 0x77, 0x4b, 0x39, 0x41, 0xdd, 0x5f, 0x3b, 0xe8, 0xa8, 0xa9, 0x4c, 0x78,
	0x79, 0xbf, 0x40, 0x7e, 0x90, 0xe5, 0xf8, 0x7b, 0xf7, 0xd2, 0x81, 0x3c, 0x08, 0x16, 0xfd, 0x4f,
	0x55, 0x4f, 0x1e, 0x01, 0xca, 0x7b, 0x7f, 0x05, 0x5d, 0x68, 0x01, 0xb1, 0x99, 0x00, 0x93, 0x70,
	0xaf, 0xd8, 0xd6, 0xbf, 0x5b, 0x70, 0xd2, 0xbd, 0x86, 0x56, 0xd8, 0x64, 0x62, 0x08, 0x72, 0xa2,
	0x77, 0x21, 0xcb, 0xf1, 0x57, 0x54, 0xa4, 0xf4, 0x47, 0x05, 0xc1, 0xd7, 0x62, 0x0d, 0x8c, 0xc3,
	0x38, 0xa1, 0xee, 0x3b, 0xe8, 0xa8, 0x1f, 0x47, 0x9a, 0xff, 0x8a, 0x29, 0xcb, 0xbd, 0x28, 0xcb,
	0xf1, 0x5b, 0xea, 0xd8, 0xf5, 0x92, 0xa3, 0xc4, 0xec, 0x30, 0x15, 0xab, 0x0c, 0xa3, 0xcf, 0x22,
	0x65, 0x90, 0xd6, 0xcf, 0x84, 0x88, 0x7d, 0x3e, 0x7b, 0x84, 0xce, 0x0a, 0x11, 0xab, 0x92, 0x3c,
	0x78, 0x0b, 0x7c, 0xa9, 0x98, 0x52, 0x98, 0x3d, 0x60, 0xfe, 0x0e, 0x44, 0x01, 0x75, 0x7f, 0x72,
	0x70, 0x0a, 0xbc, 0x9e, 0xe5, 0xf8, 0x3b, 0xca, 0xba, 0x45, 0xae, 0x1f, 0x80, 0xf5, 0x3e, 0x94,
	0xd5, 0x1b, 0x98, 0x3f, 0xb2, 0xdc, 0xb7, 0x3e, 0xaf, 0x18, 0xc0, 0xd0, 0x8a, 0x5a, 0x13, 0x78,
	0x59, 0x17, 0xa6, 0x33, 0xf4, 0x91, 0x19, 0xd9, 0xdb, 0xc8, 0x72, 0x4c, 0x15, 0x02, 0x1e, 0x71,
	0xc9, 0x59, 0x58, 0x64, 0x93, 0x0e, 0x63, 0x18, 0xea, 0x53, 0x84, 0xad, 0x1a, 0xe6, 0x0c, 0xea,
	0x7e, 0xe2, 0x54, 0x69, 0xbc, 0xa2, 0xd3, 0xf8, 0x2f, 0x2a, 0x29, 0xff, 0xec, 0x5c, 0x78, 0x75,
	0xa2, 0x0e, 0x60, 0xe1, 0x45, 0x9b, 0xbf, 0xca, 0x86, 0x31, 0xdb, 0x81, 0x7a, 0xd9, 0x51, 0xae,
	0x1b, 0xc0, 0x88, 0x85, 0x43, 0x75, 0xcc, 0xfa, 0xba, 0x2a, 0x2a, 0x65, 0x84, 0xd6, 0xaa, 0xec,
	0x1d, 0xa7, 0x42, 0x2a, 0x07, 0x34, 0x8f, 0x27, 0x2c, 0x0a, 0x6a, 0xd8, 0x06, 0xa0, 0xd2, 0x96,
	0x05, 0x41, 0x11, 0xbc, 0xfa, 0x46, 0x2b, 0x3f, 0x4c, 0x38, 0x44, 0x81, 0xa8, 0xba, 0x9a, 0x4e,
	0x67, 0x8f, 0xa3, 0x8b, 0xfb, 0x20, 0xa5, 0x98, 0xc4, 0x91, 0x00, 0xf7, 0x9b, 0xe8, 0x98, 0x51,
	0x6b, 0x98, 0xb9, 0xdc, 0xbb, 0x98, 0xe5, 0xf8, 0xdc, 0xfd, 0xea, 0x3c, 0x1e, 0xd8, 0xf8, 0x15,
	0x0c, 0x0d, 0x4a, 0x87, 0x79, 0xef, 0x2d, 0xb5, 0x26, 0xc0, 0x2d, 0x50, 0xe5, 0x64, 0x36, 0x01,
	0x2e, 0xcf, 0x1f, 0x75, 0x3a, 0xcb, 0x31, 0x6e, 0x1e, 0xa5, 0xd2, 0x52, 0x8b, 0x53, 0xf7, 0xaa,
	0xcd, 0x98, 0x25, 0x9d, 0x31, 0xe7, 0xb3, 0x1c, 0x3f, 0x53, 0x65, 0x4c, 0x4b, 0x3a, 0x1b, 0xb9,
	0xb7, 0xab, 0x28, 0x76, 0x74, 0x14, 0x79, 0x96, 0x63, 0xf8, 0x7f, 0xc4, 0x90, 0x7a, 0x97, 0x5a,
	0x9d, 0x3f, 0xeb, 0x90, 0xc2, 0xf9, 0xde, 0x5f, 0xdb, 0xeb, 0xc7, 0x1b, 0x93, 0x80, 0xfd, 0x0f,
	0xee, 0x4b, 0xb5, 0xf8, 0xc1, 0xdd, 0x67, 0xe5, 0x7e, 0x75, 0xf0, 0x74, 0xd7, 0x85, 0xb6, 0xe6,
	0x60, 0x3d, 0xe6, 0xc1, 0xb4, 0x35, 0xfb, 0x29, 0x21, 0xaf, 0x0c, 0x49, 0x14, 0xcb, 0x59, 0xbf,
	0x16, 0x9b, 0xf5, 0xd8, 0xa6, 0x56, 0x07, 0x40, 0xfc, 0x11, 0x8b, 0xb6, 0x21, 0xa0, 0xee, 0x3f,
	0x9d, 0x83, 0x25, 0xff, 0x47, 0x2a, 0x6d, 0x7f, 0x57, 0x4f, 0xdb, 0x6a, 0x48, 0x29, 0xd2, 0x6b,
	0x3a, 0x8a, 0x05, 0x98, 0x9a, 0x60, 0x27, 0xc5, 0xc2, 0x01, 0xda, 0x87, 0x09, 0x0c, 0x43, 0x55,
	0x0c, 0xab, 0xd1, 0xcd, 0x34, 0xe3, 0x57, 0x86, 0x25, 0x07, 0x04, 0x61, 0x09, 0x68, 0xa8, 0x2c,
	0x2c, 0xba, 0x71, 0x93, 0x0c, 0xda, 0xaa, 0xbd, 0x52, 0x7b, 0x99, 0xca, 0x5c, 0x36, 0x2b, 0xcd,
	0x91, 0xcf, 0x6d, 0xa5, 0x69, 0x27, 0xfb, 0x2c, 0x7d, 0x0d, 0xd9, 0xff, 0xb0, 0x8c, 0xd6, 0x5a,
	0x76, 0xbf, 0x1c, 0xa5, 0x63, 0x48, 0x2a, 0x01, 0x51, 0x12, 0xfe, 0x47, 0xcd, 0x86, 0x59, 0x4c,
	0x7d, 0xb3, 0x64, 0xb7, 0x0e, 0x09, 0x40, 0x32, 0x1e, 0x0a, 0xdd, 0x31, 0x89, 0xf5, 0x21, 0x6d,
	0x61, 0x9a, 0xb2, 0x5b, 0xd6, 0x66, 0x2c, 0x73, 0x6a, 0x19, 0xa6, 0x04, 0x64, 0x9a, 0x44, 0x8a,
	0x74, 0xbf, 0x74, 0xd0, 0x93, 0x3c, 0xf2, 0xc3, 0x34, 0x80, 0x3e, 0x0b, 0xc3, 0xbe, 0x92, 0xe8,
	0xdb, 0xdb, 0x91, 0xce, 0x8d, 0xd5, 0xde, 0x4e, 0x96, 0xe3, 0xed, 0x5a, 0xcc, 0x7a, 0x71, 0x1c,
	0x02, 0x8b, 0x14, 0x1c, 0x48, 0xc6, 0x3c, 0x52, 0x9e, 0x9d, 0x8e, 0x40, 0x8e, 0x20, 0xd1, 0xa7,
	0x1a, 0x71, 0x05, 0xb3, 0x16, 0x01, 0x31, 0x8a, 0xd3, 0x30, 0x28, 0x02, 0xa5, 0xcf, 0x0b, 0x28,
	0xb9, 0x05, 0x43, 0x96, 0x86, 0x52, 0xcf, 0xd0, 0x43, 0x16, 0x0a, 0xa0, 0xee, 0xef, 0xeb, 0x80,
	0x52, 0x39, 0x6a, 0x20, 0xd2, 0x53, 0xd1, 0x6a, 0xef, 0x61, 0x96, 0x63, 0x79, 0x48, 0x40, 0xea,
	0xb7, 0xd2, 0x0b, 0x91, 0x54, 0xe1, 0x81, 0xa0, 0x20, 0xd1, 0x3e, 0xd1, 0xf5, 0xd0, 0xaa, 0x9d,
	0x9f, 0x75, 0xf3, 0x3c, 0xd6, 0xfb, 0x6a, 0x96, 0xe3, 0xb5, 0x1a, 0x96, 0x3b, 0x76, 0xbc, 0x96,
	0x71, 0x39, 0xed, 0xd7, 0xae, 0x6c, 0x11, 0xf5, 0x3e, 0x59, 0x46, 0xdd, 0x16, 0x8e, 0x18, 0x6a,
	0xb8, 0x57, 0xe7, 0x4b, 0xe0, 0x33, 0x59, 0x8e, 0x9f, 0x6e, 0xb2, 0xa2, 0x30, 0x85, 0x8b, 0xaa,
	0xaf, 0xaf, 0xd7, 0x2b, 0xe1, 0x72, 0xef, 0x4c, 0x96, 0xe3, 0x6e, 0x55, 0x09, 0xad, 0xe9, 0xe5,
	0xf6, 0xda, 0xc0, 0xd5, 0xf9, 0x4c, 0x06, 0xae, 0x07, 0xb6, 0x00, 0xef, 0x7b, 0xd2, 0x7d, 0x36,
	0xcb, 0xb1, 0xa7, 0x4c, 0xf2, 0xd3, 0x24, 0x81, 0x48, 0x9a, 0x62, 0x3a, 0x67, 0xda, 0x37, 0xd0,
	0x17, 0x24, 0x1f, 0x43, 0xdf, 0x74, 0x72, 0x1d, 0xa8, 0x13, 0xbd, 0x73, 0x59, 0x8e, 0xcf, 0x16,
	0xd3, 0xda, 0x78, 0x06, 0x2c, 0x13, 0xb6, 0xeb, 0x53, 0xf7, 0x5b, 0x46, 0xd8, 0xd4, 0x49, 0x5d,
	0xb8, 0x4e, 0xf4, 0x9e, 0xcb, 0x72, 0xfc, 0xac, 0x12, 0x0e, 0x99, 0x90, 0xed, 0x1a, 0x8c, 0x00,
	0x75, 0x03, 0x74, 0x5c, 0x73, 0x56, 0xe8, 0x32, 0x8d, 0x8f, 0xee, 0xab, 0x98, 0x5f, 0xce, 0x72,
	0x7c, 0x49, 0x87, 0x58, 0xff, 0xb6, 0x23, 0x5c, 0x55, 0x86, 0x67, 0x7b, 0x70, 0xe6, 0xa0, 0xf5,
	0x7d, 0x56, 0x1a, 0x33, 0x05, 0xbd, 0x8e, 0x56, 0x6d, 0x21, 0xc0, 0x8e, 0x06, 0x75, 0x8a, 0x2e,
	0xe6, 0x61, 0xcf, 0xcb, 0x72, 0x7c, 0xa6, 0xea, 0x28, 0x2d, 0xe5, 0x84, 0x7a, 0x9f, 0x76, 0x5a,
	0xcb, 0xdd, 0x6d, 0x90, 0x46, 0xcb, 0xad, 0xa2, 0x62, 0x95, 0xe5, 0xee, 0xb5, 0x39, 0x0c, 0x2f,
	0xd1, 0x83, 0x28, 0xa0, 0x77, 0xed, 0xe5, 0xd7, 0xa6, 0x0b, 0x6d, 0x0e, 0x00, 0x4f, 0x67, 0x39,
	0x3e, 0xb5, 0x90, 0xf6, 0x82, 0xba, 0xd7, 0x6a, 0x19, 0x5c, 0xdc, 0xb4, 0x35, 0x31, 0x1e, 0x9b,
	0xb6, 0xdd, 0xff, 0x38, 0xe8, 0x8b, 0x73, 0xa7, 0x5f, 0x9f, 0x4f, 0xd6, 0x92, 0x67, 0x8d, 0x12,
	0xbe, 0x0d, 0xcd, 0xf2, 0xfd, 0x98, 0x3a, 0xd7, 0xf9, 0x6c, 0xeb, 0x9c, 0xf7, 0x4e, 0x2b, 0xb9,
	0xda, 0xc2, 0x62, 0xc8, 0xb5, 0x75, 0x30, 0x72, 0x95, 0x61, 0xb2, 0x3e, 0x99, 0x19, 0x9f, 0xbc,
	0x3f, 0x39, 0x08, 0xcf, 0x8a, 0xdf, 0x03, 0xa9, 0xae, 0xf9, 0xe2, 0xf0, 0xb7, 0xcc, 0x7b, 0xe8,
	0x09, 0x16, 0x86, 0xf1, 0xb4, 0xdf, 0x78, 0x25, 0xd4, 0xd4, 0x59, 0xed, 0x5d, 0xcd, 0x72, 0xbc,
	0xf1, 0xdd, 0x9a, 0x3b, 0xb5, 0xc3, 0xf4, 0x7e, 0x41, 0xea, 0x02, 0x55, 0xf1, 0x65, 0x93, 0x09,
	0xf5, 0x76, 0xd1, 0x0b, 0x0b, 0x07, 0x84, 0x36, 0xf8, 0x65, 0x32, 0xbc, 0x88, 0xba, 0xaa, 0x9c,
	0x36, 0xc0, 0xf4, 0x85, 0xd9, 0x65, 0xbc, 0xf8, 0x24, 0x5d, 0xe4, 0x05, 0xef, 0x3a, 0xba, 0x7a,
	0xd0, 0x73, 0xcd, 0x94, 0xf2, 0x0f, 0x07, 0x5d, 0x6f, 0x11, 0x7d, 0x35, 0x6a, 0xfc, 0x2e, 0xc9,
	0xde, 0xaf, 0x7f, 0x76, 0xb7, 0x66, 0x5f, 0x81, 0x5e, 0xcc, 0x72, 0x7c, 0xc3, 0xce, 0x71, 0xb5,
	0x4a, 0xa1, 0xc6, 0xcf, 0x86, 0xdf, 0x04, 0x99, 0x42, 0x52, 0x7f, 0xbf, 0xd2, 0x31, 0xf9, 0x7a,
	0x33, 0x81, 0x2f, 0x65, 0x39, 0x3e, 0x5f, 0x0b, 0xe6, 0x88, 0xc9, 0x9a, 0x44, 0xf3, 0x75, 0xd7,
	0xfb, 0x5b, 0x07, 0x3d, 0xdf, 0x6a, 0x48, 0x55, 0x59, 0x37, 0x8b, 0xf1, 0xba, 0x69, 0xc3, 0x4b,
	0xb3, 0x36, 0xac, 0x67, 0x39, 0xbe, 0xb8, 0xc0, 0x06, 0x51, 0x16, 0xe5, 0x72, 0x54, 0x7f, 0x50,
	0x4f, 0xfb, 0xa2, 0xdf, 0xbe, 0x9c, 0xe5, 0xf8, 0x66, 0xeb, 0x85, 0xb2, 0x6c, 0x12, 0xe6, 0x85,
	0xb7, 0xf1, 0xf4, 0x95, 0x8a, 0xa2, 0xfd, 0x58, 0xcd, 0x77, 0xac, 0x37, 0x3a, 0xda, 0x1b, 0xda,
	0xb7, 0x0b, 0xef, 0x33, 0x8b, 0x34, 0x96, 0xda, 0xde, 0x44, 0x47, 0x4c, 0x17, 0x2a, 0x9a, 0xec,
	0xe3, 0xba, 0x90, 0xee, 0xb0, 0xb5, 0x82, 0xb3, 0x05, 0xd3, 0x5a, 0x43, 0x2a, 0x67, 0x62, 0xf7,
	0x36, 0x3a, 0x9a, 0xc0, 0x38, 0xde, 0x35, 0xcd, 0xd5, 0xe4, 0x4e, 0x4d, 0x50, 0xe9, 0x24, 0x23,
	0xa6, 0xe6, 0x6e, 0x88, 0x88, 0xd9, 0x5b, 0x3d, 0xc9, 0xd9, 0x34, 0xdf, 0xf8, 0x78, 0x15, 0x9d,
	0x9c, 0x43, 0xe4, 0xbe, 0xeb, 0xa0, 0x93, 0x4a, 0x43, 0xe3, 0x3a, 0xef, 0x5e, 0xa4, 0xfb, 0x7d,
	0x86, 0xea, 0x3e, 0x47, 0xf7, 0xfd, 0x38, 0xe0, 0x9d, 0xcd, 0x72, 0xfc, 0x54, 0xb1, 0x26, 0xf4,
	0xf3, 0xa1, 0xd8, 0x8b, 0xfc, 0x62, 0xce, 0x31, 0x30, 0x4b, 0x3c, 0x8d, 0x1b, 0x6e, 0x3b, 0x9e,
	0xd6, 0x57, 0x81, 0x76, 0x3c, 0x0b, 0xee, 0xcb, 0x1a, 0x4f, 0xb1, 0xf6, 0x38, 0x3c, 0x8d, 0x4b,
	0x48, 0x3b, 0x9e, 0xd6, 0x6b, 0x76, 0x3b, 0x9e, 0x05, 0x57, 0x1a, 0x8d, 0xa7, 0x58, 0x5b, 0x84,
	0xe7, 0x03, 0x07, 0x9d, 0x9c, 0x1b, 0x3c, 0xdc, 0x75, 0x7a, 0x90, 0x9b, 0x50, 0x97, 0xd2, 0x03,
	0x8d, 0x33, 0x9e, 0x7e, 0x7c, 0x2e, 0xd7, 0x05, 0x61, 0xb3, 0xe3, 0x89, 0xfb, 0x91, 0x83, 0x4e,
	0xce, 0xb5, 0xac, 0x76, 0x58, 0x0b, 0x07, 0x8e, 0x76, 0x58, 0x8b, 0x1b, 0xa1, 0xa7, 0x27, 0xc5,
	0xdb, 0x20, 0xcd, 0x1f, 0x1f, 0xca, 0x8e, 0x4f, 0x58, 0xf5, 0x4a, 0x6e, 0xfd, 0xf6, 0xa9, 0x83,
	0xba, 0x8b, 0xeb, 0xb5, 0x7b, 0x95, 0x1e, 0xaa, 0xaf, 0x74, 0xaf, 0xd1, 0x43, 0xf6, 0x85, 0xdb,
	0x59, 0x8e, 0x37, 0x6d, 0xa8, 0xed, 0x60, 0xc1, 0x1a, 0x7d, 0x50, 0xc7, 0xbd, 0x59, 0xd4, 0x67,
	0x8c, 0x63, 0x93, 0x49, 0xf7, 0xb5, 0x2c, 0xc7, 0x77, 0x6e, 0x12, 0x01, 0xc9, 0x2e, 0xf7, 0x8b,
	0x79, 0x64, 0x98, 0x46, 0x7e, 0xb1, 0x3f, 0x81, 0xd0, 0xbe, 0x40, 0xe8, 0x21, 0x45, 0xf1, 0x29,
	0x89, 0xa3, 0x38, 0x6d, 0xd1, 0xae, 0x55, 0x40, 0x42, 0x37, 0xfe, 0xb5, 0x84, 0xbe, 0x3c, 0x67,
	0xd4, 0xa6, 0xfe, 0x53, 0x9d, 0xfb, 0xa1, 0x83, 0xf0, 0xa2, 0xde, 0xe5, 0xde, 0xa0, 0x87, 0xed,
	0x74, 0xdd, 0xe3, 0x74, 0x2b, 0x2e, 0x7d, 0x73, 0x25, 0xcb, 0xf1, 0xba, 0xd9, 0x28, 0x8a, 0xb6,
	0x54, 0x36, 0x89, 0x78, 0xa2, 0x46, 0x44, 0x39, 0xd3, 0xed, 0x54, 0x9a, 0x3e, 0xd1, 0xd2, 0x8a,
	0xdc, 0xaf, 0xd1, 0x43, 0xf4, 0xac, 0x26, 0x9a, 0xe7, 0xb3, 0x1c, 0x5f, 0xae, 0x2f, 0x37, 0x11,
	0x55, 0xad, 0x60, 0x54, 0x35, 0x97, 0xee, 0xe9, 0x2c, 0xc7, 0x5f, 0x2a, 0x7c, 0xd6, 0x44, 0xfa,
	0xf7, 0x1c, 0x2f, 0xf5, 0x3a, 0x3f, 0x76, 0x9c, 0xff, 0x06, 0x00, 0x00, 0xff, 0xff, 0x0c, 0x81,
	0x5e, 0xd6, 0x51, 0x1d, 0x00, 0x00,
}
